import { useEffect, useState } from "react";
import { Calculator, Grid2X2, List, X } from "lucide-react";
import { BottomSheet, BottomSheetContent, BottomSheetHeader, BottomSheetTitle } from "@/components/ui/bottom-sheet";
import { cn } from "@/lib/utils";

type ViewMode = "grid" | "list";
const VIEW_KEY = "strap-sell-product-view";
const keys = ["7","8","9","÷","4","5","6","×","1","2","3","−","0",".","+","="];
export function BusinessCalculatorFab(){
 const [open,setOpen]=useState(false),[view,setView]=useState<ViewMode>("grid"),[display,setDisplay]=useState("0"),[stored,setStored]=useState<number|null>(null),[op,setOp]=useState<string|null>(null),[fresh,setFresh]=useState(true);
 useEffect(()=>{try{const v=localStorage.getItem(VIEW_KEY);if(v==="grid"||v==="list")setView(v)}catch{}},[]);
 useEffect(()=>{try{localStorage.setItem(VIEW_KEY,view)}catch{} const root=document.querySelector('[data-tour="sell"]');const grid=root?.parentElement?.querySelector("button.surface-card")?.parentElement;if(grid){grid.classList.toggle("sell-products-list",view==="list");grid.classList.toggle("grid-cols-1",view==="list");grid.classList.toggle("grid-cols-2",view==="grid");grid.classList.toggle("sm:grid-cols-3",view==="grid")}},[view]);
 const calculate=(a:number,b:number,o:string)=>o==="+"?a+b:o==="−"?a-b:o==="×"?a*b:o==="÷"?(b===0?NaN:a/b):b;
 const press=(k:string)=>{if(/[0-9.]/.test(k)){setDisplay(d=>fresh?(k==="."?"0.":k):(d==="0"&&k!=="."?k:d+k));setFresh(false);return}if(k==="="){if(stored!==null&&op){const r=calculate(stored,Number(display),op);setDisplay(Number.isFinite(r)?String(r):"Error");setStored(null);setOp(null);setFresh(true)}return}if(op&&stored!==null&&!fresh){const r=calculate(stored,Number(display),op);setStored(r);setDisplay(String(r))}else setStored(Number(display));setOp(k);setFresh(true)};
 const clear=()=>{setDisplay("0");setStored(null);setOp(null);setFresh(true)};
 return <><div className="fixed right-3 top-2 z-[60] flex items-center gap-1 rounded-xl border border-border bg-surface/95 p-1 shadow-sm backdrop-blur-none lg:right-6 lg:top-3"><button type="button" aria-label="Grid product view" onClick={()=>setView("grid")} className={cn("flex size-9 items-center justify-center rounded-lg",view==="grid"?"bg-secondary text-foreground":"text-muted-foreground hover:bg-secondary")}><Grid2X2 className="size-4"/></button><button type="button" aria-label="List product view" onClick={()=>setView("list")} className={cn("flex size-9 items-center justify-center rounded-lg",view==="list"?"bg-secondary text-foreground":"text-muted-foreground hover:bg-secondary")}><List className="size-4"/></button><button type="button" aria-label="Open calculator" onClick={()=>setOpen(true)} className="flex size-9 items-center justify-center rounded-lg bg-foreground text-background"><Calculator className="size-4"/></button></div><BottomSheet open={open} onOpenChange={setOpen}><BottomSheetContent className="mx-auto w-full max-w-sm"><BottomSheetHeader><BottomSheetTitle className="flex items-center justify-between"><span className="flex items-center gap-2"><Calculator className="size-5"/>Calculator</span><button onClick={()=>setOpen(false)} aria-label="Close calculator"><X className="size-4"/></button></BottomSheetTitle></BottomSheetHeader><div className="px-4 pb-6"><div className="mb-4 rounded-2xl bg-secondary px-4 py-5 text-right"><p className="numeric min-h-8 break-all text-3xl font-bold">{display}</p></div><div className="grid grid-cols-4 gap-2">{keys.map(k=><button key={k} type="button" onClick={()=>press(k)} className={cn("h-14 rounded-xl border border-border text-lg font-semibold transition active:scale-[.97]",k==="="?"bg-foreground text-background":"bg-surface hover:bg-secondary")}>{k}</button>)}<button type="button" onClick={clear} className="col-span-4 h-12 rounded-xl border border-border text-sm font-semibold hover:bg-secondary">Clear</button></div></div></BottomSheetContent></BottomSheet></>;
}
