import { useEffect, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { ImagePlus, Package, Plus, ScanLine, X, LoaderCircle, ChevronDown } from "lucide-react";
import { z } from "zod";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { errorMessage } from "@/lib/format";
import type { ProductWithStock } from "@/lib/pos-types";
import { Button } from "@/components/ui/button";
import { BottomSheet, BottomSheetContent, BottomSheetDescription, BottomSheetHeader, BottomSheetTitle } from "@/components/ui/bottom-sheet";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { BarcodeScannerDialog } from "@/components/pos/BarcodeScannerDialog";
import { createShelf, fetchShelves } from "@/lib/shelves";

const schema=z.object({name:z.string().trim().min(1,"Product name is required").max(120),sku:z.string().trim().max(60),barcode:z.string().trim().max(60),category:z.string().trim().max(60),price:z.number().min(0),cost:z.number().min(0),lowStockThreshold:z.number().int().min(0),quantity:z.number().int().min(0),unitsPerPack:z.number().int().min(1),packPrice:z.number().min(0),piecePrice:z.number().min(0)});
type Props={open:boolean;onOpenChange:(open:boolean)=>void;storeId:string;branchId:string;product:ProductWithStock|null;onSaved:()=>Promise<void>|void}; type ProductImage={id:string;image_url:string;sort_order:number}; type PendingImage={file:File;preview:string};

export function ProductFormDialog({open,onOpenChange,storeId,branchId,product,onSaved}:Props){
 const[name,setName]=useState("");const[sku,setSku]=useState("");const[barcode,setBarcode]=useState("");const[category,setCategory]=useState("");const[price,setPrice]=useState("0");const[cost,setCost]=useState("0");const[threshold,setThreshold]=useState("5");const[quantity,setQuantity]=useState("0");const[packMode,setPackMode]=useState(false);const[unitsPerPack,setUnitsPerPack]=useState("1");const[packPrice,setPackPrice]=useState("0");const[piecePrice,setPiecePrice]=useState("0");const[errors,setErrors]=useState<Record<string,string>>({});const[saving,setSaving]=useState(false);const[scanning,setScanning]=useState(false);const[shelfId,setShelfId]=useState("none");const[newShelf,setNewShelf]=useState("");const[addingShelf,setAddingShelf]=useState(false);const[creatingShelf,setCreatingShelf]=useState(false);const[existingImages,setExistingImages]=useState<ProductImage[]>([]);const[pendingImages,setPendingImages]=useState<PendingImage[]>([]);const[advanced,setAdvanced]=useState(false);const queryClient=useQueryClient();
 const shelvesQuery=useQuery({queryKey:["shelves",storeId],enabled:Boolean(storeId)&&open,queryFn:()=>fetchShelves(storeId)});const shelves=shelvesQuery.data??[];const imageCount=existingImages.length+pendingImages.length;const canAddImages=imageCount<6;
 useEffect(()=>{if(!open)return;const p=product as any;setErrors({});setName(product?.name??"");setSku(product?.sku??"");setBarcode(product?.barcode??"");setCategory(product?.category??"");setPrice(product?String(product.price):"0");setCost(product?String(product.cost):"0");setThreshold(product?String(product.low_stock_threshold):"5");setQuantity(product?String(product.quantity):"0");setShelfId(product?.shelf_id??"none");const isPack=Number(p?.units_per_pack??1)>1;setPackMode(isPack);setUnitsPerPack(String(p?.units_per_pack??1));setPiecePrice(String(p?.piece_price??product?.price??0));setPackPrice(String(p?.pack_price??Number(p?.units_per_pack??1)*Number(product?.price??0)));setAddingShelf(false);setNewShelf("");setPendingImages([]);setExistingImages([]);setAdvanced(Boolean(product));if(product?.id)void(async()=>{const db=supabase as any;const{data}=await db.from("product_images").select("id,image_url,sort_order").eq("product_id",product.id).order("sort_order");setExistingImages((data??[]) as ProductImage[])})();},[open,product]);
 useEffect(()=>()=>pendingImages.forEach(i=>URL.revokeObjectURL(i.preview)),[pendingImages]);
 async function handleCreateShelf(){if(!newShelf.trim())return;setCreatingShelf(true);try{const shelf=await createShelf(storeId,newShelf.trim());await queryClient.invalidateQueries({queryKey:["shelves",storeId]});setShelfId(shelf.id);setNewShelf("");setAddingShelf(false);toast.success(`Shelf "${shelf.name}" created`)}catch(e){toast.error(errorMessage(e,"We couldn't create that shelf."))}finally{setCreatingShelf(false)}}
 function chooseImages(files:FileList|null){if(!files||!canAddImages)return;const selected=Array.from(files).slice(0,6-imageCount);const invalid=selected.find(f=>!f.type.startsWith("image/")||f.size>5e6);if(invalid){toast.error("Images must be valid image files smaller than 5 MB each.");return}setPendingImages(c=>[...c,...selected.map(file=>({file,preview:URL.createObjectURL(file)}))])}
 function removePending(index:number){setPendingImages(c=>{const t=c[index];if(t)URL.revokeObjectURL(t.preview);return c.filter((_,i)=>i!==index)})}
 async function saveImages(productId:string){if(!pendingImages.length)return;const db=supabase as any;const rows:Array<{product_id:string;store_id:string;image_url:string;sort_order:number}>=[];for(let i=0;i<pendingImages.length;i++){const item=pendingImages[i];const ext=item.file.name.split(".").pop()?.toLowerCase()||"jpg";const path=`${storeId}/products/${productId}/${crypto.randomUUID()}.${ext}`;const upload=await supabase.storage.from("kudi-store-assets").upload(path,item.file,{upsert:false,contentType:item.file.type});if(upload.error)throw new Error(upload.error.message);const url=supabase.storage.from("kudi-store-assets").getPublicUrl(path).data.publicUrl;rows.push({product_id:productId,store_id:storeId,image_url:url,sort_order:existingImages.length+i})}const{error}=await db.from("product_images").insert(rows);if(error)throw new Error(error.message);if(!existingImages.length&&rows[0]){const{error:e}=await db.from("products").update({image_url:rows[0].image_url}).eq("id",productId);if(e)throw new Error(e.message)}}
 async function handleSubmit(event:React.FormEvent){event.preventDefault();const parsed=schema.safeParse({name,sku,barcode,category,price:Number(price),cost:Number(cost),lowStockThreshold:Number(threshold),quantity:Number(quantity),unitsPerPack:packMode?Number(unitsPerPack):1,packPrice:packMode?Number(packPrice):0,piecePrice:packMode?Number(piecePrice):Number(price)});if(!parsed.success){const n:Record<string,string>={};for(const issue of parsed.error.issues)n[String(issue.path[0])]=issue.message;setErrors(n);return}setErrors({});setSaving(true);try{const v=parsed.data;const normalizedPiece=packMode?v.piecePrice:v.price;const payload={store_id:storeId,name:v.name,sku:v.sku,barcode:v.barcode,category:v.category,price:normalizedPiece,cost:v.cost,low_stock_threshold:v.lowStockThreshold,shelf_id:shelfId==="none"?null:shelfId,units_per_pack:packMode?v.unitsPerPack:1,pack_price:packMode?v.packPrice:0,piece_price:normalizedPiece};const db=supabase as any;let id=product?.id??null;if(id){const{error}=await db.from("products").update(payload).eq("id",id);if(error)throw new Error(error.message)}else{const{data,error}=await db.from("products").insert(payload).select("id").single();if(error)throw new Error(error.message);id=data?.id}if(!id)throw new Error("The product was not saved. Please try again.");const{error:se}=await supabase.from("branch_stock").upsert({branch_id:branchId,product_id:id,store_id:storeId,quantity:v.quantity},{onConflict:"branch_id,product_id"});if(se)throw new Error(se.message);await saveImages(id);await onSaved();toast.success(product?"Product updated":"Product added");onOpenChange(false)}catch(e){toast.error(errorMessage(e,"We couldn't save this product."))}finally{setSaving(false)}}
 return <><BottomSheet open={open} onOpenChange={onOpenChange}><BottomSheetContent className="mx-auto max-h-[96dvh] w-full max-w-xl overflow-hidden p-0"><div className="flex max-h-[96dvh] flex-col"><BottomSheetHeader className="shrink-0 border-b border-border px-4 pb-3 pt-4 sm:px-6"><BottomSheetTitle className="text-xl">{product?"Edit product":"Add product"}</BottomSheetTitle><BottomSheetDescription>Set up the essentials first. You can add advanced details when you need them.</BottomSheetDescription></BottomSheetHeader>
 <form onSubmit={handleSubmit} className="min-h-0 flex-1 overflow-y-auto px-4 py-4 pb-28 sm:px-6">
  <section className="space-y-4"><SectionTitle step="1" title="Product basics"/><Field label="Product name" error={errors.name}><Input value={name} onChange={e=>setName(e.target.value)} className="h-12 text-base" maxLength={120} placeholder="e.g. Peak Milk 400g" autoFocus={!product}/></Field><Field label="Product images"><div className="grid grid-cols-3 gap-2 sm:grid-cols-5">{existingImages.map(image=><div key={image.id} className="aspect-square overflow-hidden rounded-xl border border-border bg-secondary"><img src={image.image_url} alt="" className="h-full w-full object-cover"/></div>)}{pendingImages.map((image,i)=><div key={image.preview} className="relative aspect-square overflow-hidden rounded-xl border border-accent"><img src={image.preview} alt="New product" className="h-full w-full object-cover"/><button type="button" onClick={()=>removePending(i)} aria-label="Remove image" className="absolute right-1 top-1 flex size-7 items-center justify-center rounded-full bg-foreground text-background"><X className="size-3.5"/></button></div>)}{canAddImages&&<label className="flex aspect-square cursor-pointer flex-col items-center justify-center rounded-xl border border-dashed border-border bg-secondary/40"><ImagePlus className="size-6 text-muted-foreground"/><span className="mt-1 text-[11px] font-semibold">Add photo</span><input type="file" accept="image/*" multiple className="hidden" onChange={e=>chooseImages(e.target.files)}/></label>}</div><p className="text-xs text-muted-foreground">Up to 6 photos · 5 MB each</p></Field></section>
  <section className="mt-7 space-y-4"><SectionTitle step="2" title="How you sell it"/><button type="button" onClick={()=>setPackMode(v=>!v)} className={`flex min-h-16 w-full items-center justify-between rounded-2xl border p-4 text-left transition ${packMode?"border-accent bg-accent-soft":"border-border bg-secondary/30"}`}><span className="flex min-w-0 items-center gap-3"><span className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-background"><Package className="size-5"/></span><span className="min-w-0"><span className="block font-semibold">Sell by pack and piece</span><span className="block text-xs text-muted-foreground">Set a pack size and separate prices.</span></span></span><span className="ml-3 shrink-0 rounded-full bg-background px-3 py-1 text-xs font-bold">{packMode?"ON":"OFF"}</span></button>{packMode&&<div className="grid gap-3 rounded-2xl border border-border bg-secondary/40 p-4 sm:grid-cols-3"><Field label="Pieces / pack" error={errors.unitsPerPack}><Input value={unitsPerPack} onChange={e=>setUnitsPerPack(e.target.value)} className="h-11" inputMode="numeric" placeholder="12"/></Field><Field label="Pack price" error={errors.packPrice}><Input value={packPrice} onChange={e=>setPackPrice(e.target.value)} className="h-11" inputMode="decimal" placeholder="5000"/></Field><Field label="Piece price" error={errors.piecePrice}><Input value={piecePrice} onChange={e=>setPiecePrice(e.target.value)} className="h-11" inputMode="decimal" placeholder="500"/></Field><p className="sm:col-span-3 text-xs text-muted-foreground">Kudi stores stock as individual pieces, so 10 packs × 12 = 120 pieces. You can sell either 1 pack or individual pieces.</p></div>}</section>
  <section className="mt-7 space-y-4"><SectionTitle step="3" title="Stock & price"/><div className="grid gap-4 sm:grid-cols-2"><Field label={packMode?"Opening stock (pieces)":"Stock at this location"} error={errors.quantity}><Input value={quantity} onChange={e=>setQuantity(e.target.value)} className="h-12 text-base" inputMode="numeric" placeholder="0"/></Field><Field label="Low-stock alert at" error={errors.lowStockThreshold}><Input value={threshold} onChange={e=>setThreshold(e.target.value)} className="h-12" inputMode="numeric"/></Field><Field label={packMode?"Piece selling price":"Selling price"} error={errors.price}><Input value={packMode?piecePrice:price} onChange={e=>packMode?setPiecePrice(e.target.value):setPrice(e.target.value)} className="h-12 text-base" inputMode="decimal"/></Field><Field label="Cost price" error={errors.cost}><Input value={cost} onChange={e=>setCost(e.target.value)} className="h-12" inputMode="decimal"/></Field></div></section>
  <button type="button" onClick={()=>setAdvanced(v=>!v)} className="mt-7 flex w-full items-center justify-between rounded-2xl border border-border px-4 py-4 text-left"><span><span className="block font-semibold">Advanced details</span><span className="text-xs text-muted-foreground">SKU, barcode, category and shelf</span></span><ChevronDown className={`size-5 transition ${advanced?"rotate-180":""}`}/></button>{advanced&&<section className="mt-3 space-y-4 rounded-2xl border border-border bg-secondary/20 p-4"><Field label="Barcode" error={errors.barcode}><div className="flex gap-2"><Input value={barcode} onChange={e=>setBarcode(e.target.value)} className="h-12" maxLength={60} placeholder="Scan or type barcode"/><Button type="button" variant="outline" className="h-12 shrink-0" onClick={()=>setScanning(true)}><ScanLine className="size-4"/><span className="hidden sm:inline">Scan</span></Button></div></Field><Field label="SKU" error={errors.sku}><Input value={sku} onChange={e=>setSku(e.target.value)} className="h-12" maxLength={60} placeholder="Optional SKU"/></Field><Field label="Category" error={errors.category}><Input value={category} onChange={e=>setCategory(e.target.value)} className="h-12" maxLength={60} placeholder="e.g. Drinks"/></Field><Field label="Shelf"><div className="flex gap-2">{addingShelf?<><Input value={newShelf} onChange={e=>setNewShelf(e.target.value)} className="h-12" placeholder="Shelf name" maxLength={60}/><Button type="button" className="h-12 shrink-0" disabled={creatingShelf} onClick={()=>void handleCreateShelf()}>{creatingShelf?<LoaderCircle className="size-4 animate-spin"/>:"Save"}</Button></>:<><Select value={shelfId} onValueChange={setShelfId}><SelectTrigger className="h-12 flex-1"><SelectValue placeholder="No shelf"/></SelectTrigger><SelectContent><SelectItem value="none">No shelf</SelectItem>{shelves.map(s=><SelectItem key={s.id} value={s.id}>{s.name}</SelectItem>)}</SelectContent></Select><Button type="button" variant="outline" className="h-12 shrink-0" onClick={()=>setAddingShelf(true)}><Plus className="size-4"/><span className="hidden sm:inline">New</span></Button></>}</div></Field></section>}
 </form><div className="absolute inset-x-0 bottom-0 z-10 border-t border-border bg-background/95 p-3 pb-[max(.75rem,env(safe-area-inset-bottom))] backdrop-blur sm:p-4"><Button type="submit" onClick={handleSubmit} disabled={saving||creatingShelf} className="h-12 w-full rounded-xl text-base">{saving?<><LoaderCircle className="mr-2 size-5 animate-spin"/>Saving product…</>:product?"Save changes":"Add product"}</Button></div></div></BottomSheetContent></BottomSheet><BarcodeScannerDialog open={scanning} onOpenChange={setScanning} onDetected={value=>{setBarcode(value);setScanning(false)}}/></>;
}
function SectionTitle({step,title}:{step:string;title:string}){return <div className="flex items-center gap-3"><span className="flex size-7 items-center justify-center rounded-full bg-foreground text-xs font-bold text-background">{step}</span><h3 className="font-display text-base font-bold">{title}</h3></div>}
function Field({label,error,children}:{label:string;error?:string;children:React.ReactNode}){return <div className="space-y-1.5"><Label className="text-sm font-semibold">{label}</Label>{children}{error&&<p className="text-xs font-medium text-destructive">{error}</p>}</div>}
