import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { Outlet, createRootRouteWithContext, useRouter, HeadContent, Scripts } from "@tanstack/react-router";
import { useEffect, useState, type ReactNode } from "react";
import appCss from "../styles.css?url";
import landingCss from "../landing-modern.css?url";
import modernAppCss from "../kudi-modern.css?url";
import mobileNativeCss from "../mobile-native.css?url";
import mobileNavCss from "../mobile-nav.css?url";
import marketplaceCss from "../marketplace.css?url";
import tokensCss from "../tokens.css?url";
import strap2FinalCss from "../strap2-final.css?url";
import { reportLovableError } from "../lib/lovable-error-reporting";
import { supabase } from "@/integrations/supabase/client";
import { Toaster } from "@/components/ui/sonner";
import { NotFoundScreen } from "@/components/shell/NotFoundScreen";
import { StoreFeedbackFloating } from "@/components/site/StoreFeedbackFloating";
import { StoreCustomerAccess } from "@/components/site/StoreCustomerAccess";
import { CookieConsent } from "@/components/site/CookieConsent";
import { QuickFindHost } from "@/components/shell/QuickFind";
import { MobileNav } from "@/components/shell/MobileNav";
import { ThemeProvider } from "@/components/shell/ThemeProvider";
import { Button } from "@/components/ui/button";

const SITE_URL = "https://storefront-flow.vercel.app";
const SITE_TITLE = "Strap — Retail Commerce, POS, Inventory & Online Store";
const SITE_DESCRIPTION = "Strap is a retail commerce platform for managing products, inventory, point of sale, customers, staff, branches, expenses, orders, reports, and online storefronts in one workspace.";
const KEYWORDS = "Strap, retail management software, retail POS, point of sale, inventory management, stock management, online store builder, ecommerce platform, ecommerce software, shop management, small business software, retail business management, Shopify alternative, Wix alternative, ecommerce Nigeria";
const STRUCTURED_DATA = { "@context": "https://schema.org", "@graph": [{ "@type": "Organization", "@id": `${SITE_URL}/#organization`, name: "Kryonara", url: SITE_URL, brand: { "@type": "Brand", name: "Strap" } }, { "@type": "WebSite", "@id": `${SITE_URL}/#website`, name: "Strap", url: SITE_URL, description: SITE_DESCRIPTION, publisher: { "@id": `${SITE_URL}/#organization` }, inLanguage: "en-NG" }, { "@type": "SoftwareApplication", "@id": `${SITE_URL}/#software`, name: "Strap", applicationCategory: "BusinessApplication", operatingSystem: "Web", url: SITE_URL, description: SITE_DESCRIPTION, publisher: { "@id": `${SITE_URL}/#organization` }, featureList: ["Retail point of sale", "Inventory management", "Product catalogue", "Customer management", "Staff and roles", "Branch management", "Expenses and reports", "Online storefront", "Online orders", "Store builder"] }] };

function getErrorVariant(error: Error) { const message = `${error.name} ${error.message}`.toLowerCase(); if (typeof navigator !== "undefined" && !navigator.onLine) return "offline" as const; if (/permission|forbidden|not authorized|unauthorized|403|rls/.test(message)) return "permission" as const; if (/not found|404|does not exist|missing/.test(message)) return "missing" as const; return "server" as const; }
function ErrorComponent({ error, reset }: { error: Error; reset: () => void }) { console.error(error); const router = useRouter(); const variant = getErrorVariant(error); useEffect(() => { reportLovableError(error, { boundary: `tanstack_root_${variant}_error` }); }, [error, variant]); const content = { offline: { eyebrow: "You're offline", title: "Your connection dropped", body: "Strap couldn't reach the service right now. Local work can continue where supported; reconnect and try again when you're ready." }, permission: { eyebrow: "Access restricted", title: "You don't have access to this area", body: "Your current role doesn't have permission to open this page. Ask the store owner or manager if you need access." }, missing: { eyebrow: "Not found", title: "This item no longer exists", body: "The page or record you're looking for may have been removed or the link may be out of date." }, server: { eyebrow: "Something went wrong", title: "Strap couldn't load this page", body: "We hit a problem while loading this workspace. Your existing store data is safe. Try again or return to the dashboard." } }[variant]; return <div className="flex min-h-screen items-center justify-center bg-background px-5"><div className="w-full max-w-md"><div className="rounded-2xl border border-border bg-surface p-7 text-center shadow-sm sm:p-9"><span className="mx-auto flex size-12 items-center justify-center rounded-2xl bg-secondary text-sm font-bold">{variant === "offline" ? "×" : variant === "permission" ? "!" : variant === "missing" ? "404" : "—"}</span><p className="mt-5 text-[10px] font-bold uppercase tracking-[0.16em] text-muted-foreground">{content.eyebrow}</p><h1 className="mt-2 text-2xl font-bold tracking-tight text-foreground">{content.title}</h1><p className="mt-3 text-sm leading-6 text-muted-foreground">{content.body}</p><div className="mt-7 flex flex-col gap-2.5 sm:flex-row sm:justify-center"><Button onClick={() => { router.invalidate(); reset(); }}>Try again</Button><Button variant="outline" asChild><a href="/dashboard">Go to dashboard</a></Button></div></div></div></div>; }

export const Route = createRootRouteWithContext<{ queryClient: QueryClient }>()({ head: () => ({ meta: [{ charSet: "utf-8" }, { name: "viewport", content: "width=device-width, initial-scale=1, viewport-fit=cover" }, { title: SITE_TITLE }, { name: "description", content: SITE_DESCRIPTION }, { name: "keywords", content: KEYWORDS }, { name: "author", content: "Kryonara" }, { name: "application-name", content: "Strap" }, { name: "apple-mobile-web-app-title", content: "Strap" }, { name: "theme-color", content: "#1D5FE0" }, { name: "robots", content: "index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1" }, { name: "googlebot", content: "index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1" }, { name: "bingbot", content: "index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1" }, { name: "google-site-verification", content: "C8nXbWzuOEhCjnzdPL7QJMSpJ7FEZYl0YO0xaV0v1vs" }, { property: "og:type", content: "website" }, { property: "og:site_name", content: "Strap" }, { property: "og:title", content: SITE_TITLE }, { property: "og:description", content: SITE_DESCRIPTION }, { property: "og:url", content: SITE_URL }, { property: "og:locale", content: "en_NG" }, { property: "og:image", content: `${SITE_URL}/favicon.svg` }, { name: "twitter:card", content: "summary_large_image" }, { name: "twitter:title", content: SITE_TITLE }, { name: "twitter:description", content: SITE_DESCRIPTION }, { name: "twitter:image", content: `${SITE_URL}/favicon.svg` }], links: [{ rel: "canonical", href: SITE_URL }, { rel: "sitemap", type: "application/xml", href: `${SITE_URL}/sitemap.xml` }, { rel: "alternate", type: "text/plain", href: `${SITE_URL}/llms.txt`, title: "AI-readable site summary" }, { rel: "stylesheet", href: appCss }, { rel: "stylesheet", href: landingCss }, { rel: "stylesheet", href: modernAppCss }, { rel: "stylesheet", href: mobileNativeCss }, { rel: "stylesheet", href: mobileNavCss }, { rel: "stylesheet", href: marketplaceCss }, { rel: "stylesheet", href: tokensCss }, { rel: "stylesheet", href: strap2FinalCss }, { rel: "preconnect", href: "https://fonts.googleapis.com" }, { rel: "stylesheet", href: "https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;500;600;700&family=Inter:wght@400;500;600;700&display=swap" }, { rel: "icon", href: "/favicon.svg", type: "image/svg+xml" }, { rel: "apple-touch-icon", href: "/favicon.svg" }] }), shellComponent: RootShell, component: RootComponent, notFoundComponent: NotFoundScreen, errorComponent: ErrorComponent });
function RootShell({ children }: { children: ReactNode }) { return <html lang="en"><head><HeadContent /></head><body>{children}<script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(STRUCTURED_DATA) }} /><Scripts /></body></html>; }
function DomainMoveNotice() { const [visible, setVisible] = useState(true); if (!visible) return null; return <div className="pointer-events-none fixed inset-x-0 top-[4.5rem] z-[70] flex justify-center px-3 sm:top-2"><div role="status" className="pointer-events-auto flex w-full max-w-md items-center gap-2 rounded-xl border border-accent/20 bg-accent-soft/95 px-3 py-2 text-[11px] font-semibold text-foreground"><span className="min-w-0 flex-1">Strap is moving to a new domain soon</span><button type="button" aria-label="Dismiss domain notice" onClick={() => setVisible(false)} className="flex size-6 shrink-0 items-center justify-center rounded-lg text-muted-foreground transition hover:bg-background/70 hover:text-foreground">×</button></div></div>; }
function RootComponent() { const { queryClient } = Route.useRouteContext(); const router = useRouter(); useEffect(() => { const { data } = supabase.auth.onAuthStateChange((event) => { if (event !== "SIGNED_IN" && event !== "SIGNED_OUT" && event !== "USER_UPDATED") return; router.invalidate(); if (event !== "SIGNED_OUT") queryClient.invalidateQueries(); }); return () => data.subscription.unsubscribe(); }, [router, queryClient]); return <ThemeProvider><QueryClientProvider client={queryClient}><DomainMoveNotice /><Outlet /><QuickFindHost /><MobileNav /><StoreFeedbackFloating /><StoreCustomerAccess /><CookieConsent /><Toaster position="top-center" richColors /></QueryClientProvider></ThemeProvider>; }
