import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { SlidersHorizontal } from "lucide-react";
import { AppShell } from "@/components/shell/AppShell";
import { Switch } from "@/components/ui/switch";
import { supabase } from "@/integrations/supabase/client";
import { useStoreContext } from "@/components/shell/StoreProvider";

export const Route = createFileRoute("/advanced-settings")({ component: AdvancedSettingsPage });
const controls=["Low-stock alerts","Out-of-stock alerts","Order notifications","Customer notifications","Activity logging","Confirm destructive actions","Prevent negative stock","Barcode autofocus","POS sounds","Auto-print receipts","Customer accounts","14-day customer sessions","Storefront drafts","Search suggestions","Compact tables","Reduced motion","Require email verification","Session timeout","Staff PIN required","Default staff role","CSV exports","SEO controls","Social sharing","Inventory valuation","Branch-aware stock","Loyalty points","Discount codes","API access","Webhooks","AI automation"];

type Values=Record<string,boolean>;
function AdvancedSettingsPage(){const{store}=useStoreContext();const[values,setValues]=useState<Values>({});const[saving,setSaving]=useState<string>("");const[loaded,setLoaded]=useState(false);useEffect(()=>{if(!store?.id)return;let cancelled=false;(async()=>{const{data}=await supabase.from("store_advanced_settings").select("settings").eq("store_id",store.id).maybeSingle();if(cancelled)return;const stored=(data?.settings??{}) as Values;setValues(Object.fromEntries(controls.map(c=>[c,stored[c]??true])));setLoaded(true)})();return()=>{cancelled=true}},[store?.id]);async function toggle(name:string,value:boolean){if(!store?.id)return;const next={...values,[name]:value};setValues(next);setSaving(name);const{error}=await supabase.from("store_advanced_settings").upsert({store_id:store.id,settings:next,updated_at:new Date().toISOString()},{onConflict:"store_id"});setSaving(error?"error":"");setTimeout(()=>setSaving(""),800)}return <AppShell title="Advanced settings"><div className="rounded-2xl border border-border bg-surface p-5 sm:p-7"><div className="flex items-start gap-4 border-b border-border pb-6"><span className="flex size-11 items-center justify-center rounded-xl bg-accent-soft"><SlidersHorizontal className="size-5 text-accent-ink"/></span><div><h2 className="text-xl font-bold">Advanced store controls</h2><p className="mt-1 text-sm text-muted-foreground">Fine-tune how Strap behaves for this store. Settings are saved to your store account.</p></div></div><div className="grid gap-3 py-6 md:grid-cols-2">{controls.map((name,i)=>{const soon=name==="API access"||name==="Webhooks"||name==="AI automation";return <div key={name} className="flex items-center justify-between gap-4 rounded-xl border border-border p-4"><div className="min-w-0"><p className="text-sm font-semibold">{name}{soon&&<span className="ml-2 rounded-full bg-secondary px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide text-muted-foreground">Coming soon</span>}</p><p className="mt-1 text-xs text-muted-foreground">{soon?"Not active yet":"Store-level preference"}</p></div><Switch checked={values[name]??false} disabled={!loaded||soon||saving===name} onCheckedChange={v=>void toggle(name,v)}/></div>})}</div></div></AppShell>}
