import { createFileRoute } from "@tanstack/react-router";
import { SiteFooter, SiteHeader } from "@/components/site/SiteChrome";

export const Route = createFileRoute("/privacy")({
  head: () => ({ meta: [{ title: "Privacy Policy — Strap" }, { name: "description", content: "Strap's detailed privacy notice for merchants, staff, customers and visitors." }] }),
  component: Privacy,
});

const Section = ({ title, children }: { title: string; children: React.ReactNode }) => <section className="space-y-3"><h2 className="font-display text-xl font-bold text-foreground">{title}</h2>{children}</section>;
const P = ({ children }: { children: React.ReactNode }) => <p>{children}</p>;
const UL = ({ children }: { children: React.ReactNode }) => <ul className="list-disc space-y-2 pl-5">{children}</ul>;

function Privacy() {
  return <div className="min-h-screen bg-surface"><SiteHeader /><main className="mx-auto max-w-4xl px-4 py-14 sm:px-6">
    <div className="border-b border-border pb-8"><p className="text-label-caps text-muted-foreground">Legal & privacy</p><h1 className="mt-2 text-display-md">Privacy Policy</h1><p className="mt-4 max-w-3xl text-muted-foreground">This Privacy Policy explains how Strap collects, uses, stores, shares and protects personal data when you use Strap, visit our website, operate a Strap store, buy from a Strap-powered storefront, contact support, or otherwise interact with us.</p><p className="mt-3 text-sm text-muted-foreground"><strong>Effective date:</strong> 19 August 2026 · <strong>Last updated:</strong> 19 August 2026</p></div>
    <div className="mt-10 space-y-8 text-[15px] leading-7 text-muted-foreground">
      <div className="rounded-2xl border border-warning/30 bg-warning-soft p-5"><strong className="text-foreground">Important before publication:</strong> Strap's operator should replace the bracketed legal-contact fields in this policy with the actual registered legal entity name, address, privacy contact/DPO details and any other required corporate information. This document is a product privacy notice, not a substitute for advice from a Nigerian privacy lawyer or licensed Data Protection Compliance Organisation (DPCO). Compliance depends on Strap's actual processing, contracts, security controls and regulatory status.</div>
      <Section title="1. Who is responsible for your data?"><P>Strap is a software platform for point-of-sale, inventory, customer, reporting and online-store operations. The platform operator is <strong className="text-foreground">[LEGAL ENTITY / BUSINESS NAME]</strong> (“Strap”, “we”, “us” or “our”), with registered/contact address <strong className="text-foreground">[BUSINESS ADDRESS]</strong> and privacy contact <strong className="text-foreground">[PRIVACY EMAIL / DPO EMAIL]</strong>.</P><P>For merchant-entered customer and staff information, Strap may act as a data processor/service provider on the merchant's instructions, while the merchant may remain the controller/data controller for its own business records. For information Strap collects for its own account, security, support, product and legal purposes, Strap may act as a controller. The exact role depends on the processing activity.</P></Section>
      <Section title="2. Scope"><P>This policy covers Strap accounts, the Strap web application, Strap-powered online storefronts, support and documentation, product-import features, receipt and hardware features, analytics and communications that Strap controls. A merchant's own privacy practices, refund policy and customer notices may apply separately to transactions made through that merchant.</P><P>Links to third-party services are governed by their own privacy notices. Strap does not control the privacy practices of independent merchants, payment providers, messaging platforms, browser vendors, device manufacturers or other third parties.</P></Section>
      <Section title="3. Information we may collect"><UL><li><strong className="text-foreground">Account data:</strong> name, email address, authentication identifiers, account status and security events.</li><li><strong className="text-foreground">Merchant/workspace data:</strong> business name, branch, address, phone, currency, product catalogue, prices, stock, expenses, reports, settings and staff permissions.</li><li><strong className="text-foreground">Customer data entered by merchants:</strong> name, phone, email, notes, purchase history, credit information and other information the merchant chooses to record.</li><li><strong className="text-foreground">Transaction data:</strong> products, quantities, totals, payment method, timestamps, order status, refunds or other transaction records supported by Strap.</li><li><strong className="text-foreground">Storefront data:</strong> public store name, catalogue, product images, descriptions, prices, banners, policies and public reviews/ratings or reports.</li><li><strong className="text-foreground">Support and feedback:</strong> messages, attachments, reports, ratings, contact details and information needed to investigate an issue.</li><li><strong className="text-foreground">Device/technical data:</strong> IP address where available, browser/device information, log data, approximate location inferred from technical information, crash/error information and security events.</li><li><strong className="text-foreground">Hardware/import data:</strong> scanner input, printer connection metadata, files or text you upload for catalogue import, and images you deliberately submit to Strap's import tools.</li><li><strong className="text-foreground">Payment information:</strong> where a third-party payment provider is used, payment credentials may be collected and processed directly by that provider. Strap should not receive or store full card credentials unless expressly stated in the applicable payment integration.</li></UL></Section>
      <Section title="4. How we use personal data"><UL><li>Provide, operate, maintain and improve Strap.</li><li>Authenticate users, manage stores, branches, roles and permissions.</li><li>Process sales, inventory changes, online orders, receipts, reports and other merchant instructions.</li><li>Provide support, troubleshooting, product education and security assistance.</li><li>Detect fraud, abuse, unauthorized access, malicious activity and technical failures.</li><li>Back up, synchronize and restore merchant records, including supported offline workflows.</li><li>Provide product-import and catalogue-management functionality.</li><li>Send transactional communications such as verification, security and service notices.</li><li>Send marketing communications only where permitted by applicable law and with the choices required by law.</li><li>Measure product performance, diagnose errors and develop new features using appropriate safeguards.</li><li>Comply with legal obligations, lawful requests, tax/accounting requirements and regulatory processes.</li><li>Establish, exercise or defend legal claims and protect the rights, safety and property of Strap, merchants and other users.</li></UL></Section>
      <Section title="5. Lawful bases"><P>Depending on the activity and applicable law, Strap may rely on performance of a contract, compliance with a legal obligation, consent, legitimate interests, vital interests or another lawful basis recognized by applicable data-protection law. Consent is not the only possible lawful basis and may be withdrawn where processing is based on consent.</P><P>Where a merchant enters a customer's information into Strap, the merchant is responsible for having an appropriate lawful basis and providing any required privacy notice to that customer. Strap does not decide what lawful basis a merchant should use for its independent business processing.</P></Section>
      <Section title="6. Product import, OCR and AI-assisted features"><P>Strap may provide tools that turn spreadsheets, copied text or images into structured product information. These tools are designed to reduce data-entry work but can make mistakes. Extracted product names, prices, quantities, SKUs, barcodes and categories must be reviewed by the merchant before publication or sale.</P><P>Where an image or text is sent to an external AI/OCR provider, Strap will identify that provider or applicable category of provider in the relevant product documentation and process the information under an appropriate contractual and legal framework. Strap will not represent an automated extraction as verified fact. Do not upload confidential personal information, payment credentials, passwords or documents that you are not authorized to share.</P></Section>
      <Section title="7. Sharing and service providers"><P>We may use carefully selected service providers for hosting, database infrastructure, authentication, storage, email delivery, analytics, error monitoring, customer support, security and other functions necessary to operate Strap. Service providers receive only information reasonably required for their service and should be bound by confidentiality, security and data-protection obligations appropriate to their role.</P><P>We may also disclose information where required by law, court order or lawful government request; to protect users and the platform; in connection with a merger, acquisition, financing or sale of assets; or where you direct us to share it.</P><P>Strap does not sell personal data as a commodity. We do not permit third parties to use merchant/customer data for unrelated advertising purposes merely because the data passes through Strap.</P></Section>
      <Section title="8. Public storefronts, ratings and reports"><P>Information a merchant deliberately publishes through a public Strap storefront can be visible to visitors. Public product information may include product name, description, images, price, availability and store information selected by the merchant.</P><P>Store ratings and reports are handled as platform safety/feedback records. Strap may use them to investigate abuse, fraud, misleading listings or other policy violations. Do not submit another person's private information in a public review or report unless it is necessary for a legitimate complaint and you are authorized to provide it.</P></Section>
      <Section title="9. Cookies and local storage"><P>Strap may use strictly necessary cookies or browser storage for authentication, session continuity, security, preferences, offline queues and application functionality. Optional analytics or marketing technologies, if introduced, will be subject to the choices and notices required by applicable law.</P><P>Offline functionality can temporarily store transaction information on a device. Users should secure devices used to operate Strap, use appropriate account credentials and avoid leaving a shared device unlocked.</P></Section>
      <Section title="10. Security"><P>We use technical and organizational measures appropriate to the risks of the processing, which may include authentication controls, role-based access, database policies, encryption in transit, protected infrastructure, logging, backups and monitoring. No internet service can guarantee absolute security.</P><P>Merchants are responsible for protecting passwords, PINs, devices, staff access and any credentials used with connected hardware. If you suspect unauthorized access, contact Strap promptly through <strong className="text-foreground">[SECURITY/PRIVACY EMAIL]</strong>.</P></Section>
      <Section title="11. Data breaches"><P>We maintain procedures for detecting, recording, assessing and responding to personal-data incidents. Where applicable law requires notification to the Nigeria Data Protection Commission, affected individuals or another authority, Strap will make the required notifications within the applicable statutory periods. We will not delay a required notification merely because an investigation is ongoing where the law requires earlier action.</P></Section>
      <Section title="12. International transfers"><P>Strap and its service providers may process data outside Nigeria. Where personal data is transferred across borders, Strap will use a lawful transfer mechanism and appropriate safeguards required by the Nigeria Data Protection Act and applicable regulations/directives. The applicable mechanism may include an adequacy decision, approved contractual or other safeguards, or another statutory basis.</P></Section>
      <Section title="13. Retention"><P>We keep information only for as long as reasonably necessary for the purpose for which it was collected, contractual obligations, security, dispute resolution, accounting, tax, fraud prevention and legal/regulatory requirements. Retention periods can differ by record type.</P><P>Deletion may be delayed where data must be retained to comply with law, establish or defend a legal claim, resolve a dispute, prevent fraud, complete a transaction, or preserve security records. Backups may also retain deleted information for a limited disaster-recovery period.</P></Section>
      <Section title="14. Your rights"><P>Subject to applicable legal exceptions, data subjects may have rights including:</P><UL><li>to be informed about processing;</li><li>to request access to personal data;</li><li>to request correction of inaccurate data;</li><li>to request deletion/erasure where applicable;</li><li>to object to certain processing;</li><li>to restrict processing in applicable circumstances;</li><li>to receive portable data where applicable;</li><li>to withdraw consent where consent is the lawful basis;</li><li>to object to certain automated decision-making and seek human intervention where applicable; and</li><li>to lodge a complaint with the Nigeria Data Protection Commission.</li></UL><P>Requests should be sent to <strong className="text-foreground">[PRIVACY EMAIL / DPO EMAIL]</strong>. We may need reasonable information to verify the requester's identity and protect another person's privacy. Where a request concerns customer data held on behalf of a merchant, we may refer the request to the relevant merchant or assist the merchant as required by our contractual and legal obligations.</P></Section>
      <Section title="15. Children's data"><P>Strap is a business software platform and is not directed at children. Merchants must not knowingly use Strap to collect children's personal data unlawfully. Where child data is necessary for a legitimate business purpose, the responsible merchant must comply with applicable child-protection and data-protection requirements.</P></Section>
      <Section title="16. Merchant responsibilities"><UL><li>Collect personal data fairly and lawfully.</li><li>Provide customers and staff with appropriate notices.</li><li>Only collect information reasonably needed for the stated purpose.</li><li>Keep records accurate and secure.</li><li>Use appropriate permissions and remove staff access when it is no longer needed.</li><li>Honor applicable consumer, tax, advertising and product-safety requirements.</li><li>Do not upload or publish private information without authorization.</li><li>Maintain their own retention, refund, warranty and customer-service policies where required.</li></UL></Section>
      <Section title="17. Third-party links and integrations"><P>Strap may link to or integrate with services operated by third parties. Those services may have separate terms and privacy notices. A third-party provider's processing is not automatically covered by this policy, and Strap is not responsible for a third party's independent privacy practices.</P></Section>
      <Section title="18. Changes to this policy"><P>We may update this policy when Strap changes, laws or regulatory guidance changes, or our processing practices change. Material changes will be highlighted where appropriate. The current version will remain available on this page with its effective date.</P></Section>
      <Section title="19. Complaints and regulatory contact"><P>First contact Strap at <strong className="text-foreground">[PRIVACY EMAIL / DPO EMAIL]</strong> so we can investigate and respond. You may also have the right to complain to the Nigeria Data Protection Commission. The NDPC identifies data-subject rights under sections 34–38 of the Nigeria Data Protection Act and provides regulatory complaint and data-subject request channels. urlNigeria Data Protection Commissionhttps://ndpc.gov.ng/</P></Section>
      <Section title="20. Contact"><P>Privacy enquiries: <strong className="text-foreground">[PRIVACY EMAIL]</strong><br />Security enquiries: <strong className="text-foreground">[SECURITY EMAIL]</strong><br />Postal address: <strong className="text-foreground">[REGISTERED BUSINESS ADDRESS]</strong></P></Section>
    </div>
  </main><SiteFooter /></div>;
}
