import { createFileRoute, Link } from "@tanstack/react-router";
import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { ArrowLeft, Bell, BookOpen, Check, ChevronRight, CircleHelp, CreditCard, ExternalLink, KeyRound, Laptop, Lock, LogOut, Package, Palette, Receipt, ShieldCheck, Store, Users, Globe2, SlidersHorizontal } from "lucide-react";
import { AppShell } from "@/components/shell/AppShell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { supabase } from "@/integrations/supabase/client";
import { useStoreContext } from "@/components/shell/StoreProvider";

export const Route = createFileRoute("/settings")({ component: SettingsPage });

type Item = { id:string; title:string; description:string; icon:typeof Store };
const items: Item[] = [
  { id:"profile", title:"Store profile", description:"Business identity, contact details and location", icon:Store },
  { id:"appearance", title:"Store appearance", description:"Brand, colors, typography and storefront presentation", icon:Palette },
  { id:"staff", title:"Staff & permissions", description:"Team members, roles and access", icon:Users },
  { id:"notifications", title:"Notifications", description:"Orders, stock and customer alerts", icon:Bell },
  { id:"receipts", title:"Receipts", description:"Receipt identity, printing and footer details", icon:Receipt },
  { id:"online", title:"Online store", description:"Storefront, SEO, navigation and publishing", icon:Globe2 },
  { id:"checkout", title:"Checkout & sales", description:"Checkout behaviour, discounts and sales preferences", icon:CreditCard },
  { id:"inventory", title:"Inventory", description:"Stock rules, alerts, valuation and branches", icon:Package },
  { id:"security", title:"Security", description:"Account protection and session controls", icon:ShieldCheck },
  { id:"payments", title:"Payments", description:"Payment providers and subscription billing", icon:CreditCard },
  { id:"password", title:"Change password", description:"Securely change your account password", icon:KeyRound },
  { id:"sessions", title:"Active computers / sessions", description:"Review and revoke signed-in sessions", icon:Laptop },
  { id:"signout", title:"Sign out other devices", description:"Keep this device signed in and revoke others", icon:LogOut },
  { id:"advanced", title:"Advanced settings", description:"30+ operational controls for your store", icon:SlidersHorizontal },
];

function SettingsPage(){
  const { store, role } = useStoreContext();
  const [active,setActive]=useState("profile");
  const [otpSent,setOtpSent]=useState(false);
  const [otp,setOtp]=useState("");
  const [newPassword,setNewPassword]=useState("");
  const [message,setMessage]=useState("");
  const [busy,setBusy]=useState(false);
  const email=useQuery({queryKey:["settings-user-email"],queryFn:async()=>{const{data}=await supabase.auth.getUser();return data.user?.email??""}}).data??"";
  const selected=items.find(x=>x.id===active)!;
  async function sendOtp(){if(!email)return;setBusy(true);setMessage("");const{error}=await supabase.auth.signInWithOtp({email,options:{shouldCreateUser:false}});setBusy(false);if(error){setMessage(error.message);return}setOtpSent(true);setMessage("Verification code sent to your email.");}
  async function verifyAndChange(){if(!otp||newPassword.length<8){setMessage("Enter the code and a password of at least 8 characters.");return}setBusy(true);const{error:verifyError}=await supabase.auth.verifyOtp({email,token:otp,type:"email"});if(verifyError){setBusy(false);setMessage(verifyError.message);return}const{error}=await supabase.auth.updateUser({password:newPassword});setBusy(false);setMessage(error?error.message:"Password changed successfully.");if(!error){setOtp("");setNewPassword("");setOtpSent(false)}}
  async function signOutOthers(){setBusy(true);const{error}=await supabase.auth.signOut({scope:"others"});setBusy(false);setMessage(error?error.message:"Other active sessions have been signed out.")}
  return <AppShell title="Settings"><div className="grid gap-6 lg:grid-cols-[280px_minmax(0,1fr)]">
    <aside className="h-fit rounded-2xl border border-border bg-surface p-2 lg:sticky lg:top-28"><div className="px-3 py-3"><p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Store & account</p><p className="mt-1 text-sm font-medium truncate">{store?.name??"Your store"}</p></div>{items.map(item=>{const Icon=item.icon;return <button key={item.id} onClick={()=>setActive(item.id)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left transition ${active===item.id?"bg-accent-soft text-accent-ink":"hover:bg-secondary"}`}><Icon className="size-4 shrink-0"/><span className="min-w-0 flex-1"><span className="block text-sm font-semibold">{item.title}</span><span className="hidden truncate text-xs text-muted-foreground sm:block">{item.description}</span></span><ChevronRight className="size-4 opacity-50"/></button>})}</aside>
    <section className="min-w-0 rounded-2xl border border-border bg-surface p-5 sm:p-7"><div className="flex items-start justify-between gap-4 border-b border-border pb-6"><div><p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Settings</p><h2 className="mt-1 text-2xl font-bold tracking-tight">{selected.title}</h2><p className="mt-2 text-sm text-muted-foreground">{selected.description}</p></div>{active==="payments"&&<span className="rounded-full bg-secondary px-3 py-1 text-xs font-semibold">Coming Soon</span>}</div>
      {active==="profile"&&<ProfileSection store={store}/>} {active==="appearance"&&<AppearanceSection/>} {active==="staff"&&<LinkSection title="Staff & permissions" body="Manage staff accounts, roles, PIN access and permissions from the staff workspace." to="/staff"/>} {active==="notifications"&&<ToggleSection title="Notifications" rows={["New online orders","Low-stock alerts","Out-of-stock alerts","Customer notifications","Staff activity alerts"]}/>} {active==="receipts"&&<LinkSection title="Receipts" body="Design your receipts, configure business details and printing behaviour." to="/receipt-designer"/>} {active==="online"&&<LinkSection title="Online store" body="Manage your storefront, catalog, orders and publishing tools." to="/online-store"/>} {active==="checkout"&&<ToggleSection title="Checkout & sales" rows={["Require customer details","Confirm destructive sales actions","Allow discounts","Play POS sounds","Auto-print receipts"]}/>} {active==="inventory"&&<LinkSection title="Inventory" body="Configure stock behaviour, alerts, valuation and branch-aware inventory." to="/products"/>} {active==="security"&&<SecuritySection onSignOutOthers={signOutOthers} busy={busy}/>} {active==="payments"&&<ComingSoon/>} {active==="password"&&<PasswordSection email={email} otpSent={otpSent} otp={otp} setOtp={setOtp} newPassword={newPassword} setNewPassword={setNewPassword} sendOtp={sendOtp} verifyAndChange={verifyAndChange} busy={busy} message={message}/>} {active==="sessions"&&<SecuritySection onSignOutOthers={signOutOthers} busy={busy}/>} {active==="signout"&&<div className="py-8"><Lock className="size-8 text-accent-ink"/><h3 className="mt-4 text-xl font-bold">Sign out other devices</h3><p className="mt-2 max-w-xl text-sm leading-6 text-muted-foreground">This keeps your current session active while invalidating other sessions associated with your account.</p><Button className="mt-6" onClick={signOutOthers} disabled={busy}>{busy?"Signing out…":"Sign out other devices"}</Button>{message&&<p className="mt-4 text-sm">{message}</p>}</div>} {active==="advanced"&&<LinkSection title="Advanced settings" body="Open the advanced operational controls for your store. This area is intentionally separate from everyday settings." to="/advanced-settings"/>}
    </section></div></AppShell>
}

function ProfileSection({store}:{store:any}){return <div className="grid gap-6 py-7 sm:grid-cols-2"><Field label="Store name" value={store?.name??""}/><Field label="Phone" value={store?.phone??""}/><Field label="Address" value={store?.address??""}/><Field label="Currency" value={store?.currency??"NGN"}/><div className="sm:col-span-2 rounded-xl border border-border bg-secondary/40 p-4"><p className="font-semibold">Store ownership</p><p className="mt-1 text-sm text-muted-foreground">Role: {store?.owner_id?"Owner / authorised member":"Store member"}</p></div></div>}
function Field({label,value}:{label:string,value:string}){return <div><Label>{label}</Label><Input className="mt-2" defaultValue={value} /></div>}
function AppearanceSection(){return <div className="space-y-4 py-7"><p className="text-sm text-muted-foreground">Control the visual identity used by your business and online storefront.</p><ToggleSection title="Brand controls" rows={["Use store logo","Use brand colors","Show store name in storefront","Show social sharing metadata"]}/><Link to="/online-store/customize" className="inline-flex items-center gap-2 font-semibold text-accent-ink">Open storefront customization <ExternalLink className="size-4"/></Link></div>}
function ToggleSection({title,rows}:{title:string,rows:string[]}){return <div className="space-y-2 py-7"><h3 className="font-semibold">{title}</h3>{rows.map(row=><div key={row} className="flex items-center justify-between gap-4 rounded-xl border border-border p-4"><div><p className="text-sm font-semibold">{row}</p><p className="text-xs text-muted-foreground">Store preference</p></div><Switch defaultChecked/></div>)}</div>}
function LinkSection({title,body,to}:{title:string,body:string,to:string}){return <div className="py-10"><div className="rounded-2xl border border-border bg-secondary/40 p-6"><h3 className="text-xl font-bold">{title}</h3><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">{body}</p><Link to={to as any} className="mt-6 inline-flex items-center gap-2 rounded-xl bg-accent px-4 py-2.5 text-sm font-semibold">Open {title} <ExternalLink className="size-4"/></Link></div></div>}
function SecuritySection({onSignOutOthers,busy}:{onSignOutOthers:()=>void,busy:boolean}){return <div className="space-y-4 py-7"><div className="rounded-xl border border-border p-5"><div className="flex items-center gap-3"><ShieldCheck className="size-5 text-accent-ink"/><div><p className="font-semibold">Account protection</p><p className="text-sm text-muted-foreground">Email verification and session controls are handled by Supabase Auth.</p></div></div></div><div className="rounded-xl border border-border p-5"><p className="font-semibold">Other sessions</p><p className="mt-1 text-sm text-muted-foreground">Revoke every other active login while keeping this device signed in.</p><Button className="mt-4" variant="outline" onClick={onSignOutOthers} disabled={busy}>{busy?"Working…":"Sign out other devices"}</Button></div></div>}
function PasswordSection({email,otpSent,otp,setOtp,newPassword,setNewPassword,sendOtp,verifyAndChange,busy,message}:{email:string;otpSent:boolean;otp:string;setOtp:(v:string)=>void;newPassword:string;setNewPassword:(v:string)=>void;sendOtp:()=>void;verifyAndChange:()=>void;busy:boolean;message:string}){return <div className="max-w-lg space-y-5 py-7"><div className="rounded-xl border border-border bg-secondary/40 p-4"><p className="text-sm font-semibold">Verify with email OTP</p><p className="mt-1 text-xs leading-5 text-muted-foreground">A verification code will be sent to {email||"your verified email"} before the password is changed.</p></div><div><Label>New password</Label><Input type="password" value={newPassword} onChange={e=>setNewPassword(e.target.value)} className="mt-2" minLength={8}/></div>{otpSent&&<div><Label>Verification code</Label><Input inputMode="numeric" value={otp} onChange={e=>setOtp(e.target.value)} className="mt-2" placeholder="Enter the code"/></div>} {!otpSent?<Button onClick={sendOtp} disabled={busy||!email}>{busy?"Sending…":"Send verification code"}</Button>:<Button onClick={verifyAndChange} disabled={busy||!otp||!newPassword}>{busy?"Changing…":"Verify & change password"}</Button>}{message&&<p className="text-sm text-muted-foreground">{message}</p>}</div>}
function ComingSoon(){return <div className="py-12 text-center"><CreditCard className="mx-auto size-9 text-muted-foreground"/><h3 className="mt-4 text-xl font-bold">Payments are coming soon</h3><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-muted-foreground">Payment providers, premium plans and subscription billing are intentionally disabled until launch.</p></div>}
