import { createFileRoute } from "@tanstack/react-router";
import { SiteFooter, SiteHeader } from "@/components/site/SiteChrome";

export const Route = createFileRoute("/terms")({
  head: () => ({ meta: [{ title: "Terms of Service — Strap" }, { name: "description", content: "Detailed terms governing Strap accounts, merchant workspaces, online stores and platform use." }] }),
  component: Terms,
});

const Section = ({ title, children }: { title: string; children: React.ReactNode }) => <section className="space-y-3"><h2 className="font-display text-xl font-bold text-foreground">{title}</h2>{children}</section>;
const P = ({ children }: { children: React.ReactNode }) => <p>{children}</p>;
const UL = ({ children }: { children: React.ReactNode }) => <ul className="list-disc space-y-2 pl-5">{children}</ul>;

function Terms() {
  return <div className="min-h-screen bg-surface"><SiteHeader /><main className="mx-auto max-w-4xl px-4 py-14 sm:px-6">
    <div className="border-b border-border pb-8"><p className="text-label-caps text-muted-foreground">Legal</p><h1 className="mt-2 text-display-md">Terms of Service</h1><p className="mt-4 max-w-3xl text-muted-foreground">These Terms govern access to and use of Strap, including its point-of-sale tools, inventory features, customer records, online storefronts, catalogue imports, reports and connected hardware.</p><p className="mt-3 text-sm text-muted-foreground"><strong>Effective date:</strong> 19 August 2026 · <strong>Last updated:</strong> 19 August 2026</p></div>
    <div className="mt-10 space-y-8 text-[15px] leading-7 text-muted-foreground">
      <div className="rounded-2xl border border-warning/30 bg-warning-soft p-5"><strong className="text-foreground">Publication checklist:</strong> Before relying on these Terms for public commercial use, replace <strong className="text-foreground">[LEGAL ENTITY]</strong>, <strong className="text-foreground">[ADDRESS]</strong> and contact placeholders with the actual contracting entity and have Nigerian counsel review the document against Strap's final pricing, payment, refund, data-processing, consumer-protection and regulatory arrangements.</div>
      <Section title="1. Contracting entity"><P>These Terms are between you and <strong className="text-foreground">[LEGAL ENTITY / BUSINESS NAME]</strong> (“Strap”, “we”, “us” or “our”), located at <strong className="text-foreground">[REGISTERED ADDRESS]</strong>. If you use Strap for a business, you confirm that you have authority to bind that business.</P></Section>
      <Section title="2. What Strap provides"><P>Strap provides business software for recording sales, managing stock, managing customers, tracking expenses, generating reports, operating online catalogues and orders, designing receipts, and connecting supported scanners or printers. Features may change as Strap develops.</P><P>Strap is software infrastructure. Unless a separate written agreement says otherwise, Strap is not the seller of products listed by merchants, the merchant of record for a merchant's sales, a bank, payment institution, lender, tax adviser, accountant, legal adviser, logistics company or insurer.</P></Section>
      <Section title="3. Eligibility and authority"><P>You must be legally capable of entering a contract and must provide accurate account information. If you create an account for an organization, you represent that you are authorized to do so. You must not create an account using another person's identity or credentials without authorization.</P></Section>
      <Section title="4. Account security"><UL><li>Keep passwords, PINs, recovery methods and device access confidential.</li><li>Use separate staff accounts where Strap provides them instead of sharing credentials.</li><li>Give each employee only the permissions they need.</li><li>Remove or disable access promptly when staff leave or no longer require access.</li><li>Tell Strap promptly if you suspect unauthorized access.</li></UL><P>You are responsible for activity performed through credentials you fail to protect, except to the extent applicable law provides otherwise.</P></Section>
      <Section title="5. Merchant content and responsibilities"><P>You retain your rights in product data, images, descriptions, business information and other content you submit, subject to the license Strap needs to operate the service. You are responsible for ensuring that your content is accurate, lawful, non-infringing and suitable for publication.</P><UL><li>Do not list counterfeit, stolen, prohibited or unlawfully restricted goods.</li><li>Do not publish misleading product descriptions, prices or promotions.</li><li>Do not upload another person's private information without a lawful reason and authorization.</li><li>Comply with applicable product safety, labeling, tax, advertising, consumer-protection and industry rules.</li><li>Maintain accurate stock and pricing information.</li><li>Honor your own legally required refund, return, warranty and cancellation obligations.</li></UL></Section>
      <Section title="6. Online stores and merchant-customer contracts"><P>A merchant operating a Strap storefront is responsible for the transaction between the merchant and the shopper. The merchant must display material product information, price, availability, delivery information, return/refund terms and other disclosures required by applicable law before payment or order confirmation.</P><P>Strap may provide tools for customers to report or rate a store. A report or rating does not itself establish that a merchant has violated a law. Strap may investigate, request information, limit visibility or take other platform-safety action where reasonably necessary.</P></Section>
      <Section title="7. Consumer protection"><P>Merchants must comply with applicable Nigerian consumer-protection rules, including requirements concerning clear information, price disclosure, accurate representations, fair dealing, product safety, returns and complaint handling. Strap does not authorize a merchant to contract out of mandatory consumer rights.</P><P>Where a Strap feature is used to facilitate an online transaction, the merchant remains responsible for providing legally required disclosures and a practical complaint/redress channel.</P></Section>
      <Section title="8. Product imports and smart extraction"><P>Strap may allow CSV/XLSX uploads, copied text and image-assisted catalogue workflows. Imported data may contain errors. You must review extracted names, prices, quantities, categories, SKUs, barcodes and images before publishing or selling.</P><P>You must only upload files and images that you are authorized to process. Automated extraction is an assistance tool and does not guarantee accuracy, authenticity, tax classification, product compliance or market legality.</P></Section>
      <Section title="9. Hardware and browser features"><P>Scanner, Bluetooth, USB, Web Serial, printing and camera capabilities depend on your browser, operating system, hardware and device permissions. Strap cannot guarantee compatibility with every third-party device. You are responsible for maintaining supported hardware and following the hardware setup guides.</P><P>A receipt generated by Strap is a software output. The merchant remains responsible for ensuring that receipts, invoices, tax information and records meet applicable requirements for its business.</P></Section>
      <Section title="10. Offline mode and synchronization"><P>Strap may support temporary offline sales or locally queued information. Offline records can be affected by device loss, browser storage limits, corruption, user actions or conflicting changes. When connectivity returns, Strap may synchronize queued records. Merchants should regularly reconnect and verify that important transactions have synchronized.</P><P>Strap does not guarantee that offline mode can resolve every multi-device inventory conflict. The merchant remains responsible for reconciliation where concurrent offline devices are used.</P></Section>
      <Section title="11. Payments and financial information"><P>Where payment processing is provided by a third party, that provider's terms and privacy notice apply to its processing. Strap may record a payment method and transaction status without receiving full payment credentials. You must not use Strap to store prohibited authentication data such as full card security codes.</P><P>Strap does not guarantee payment authorization, settlement or availability of any bank, card, transfer or payment-provider network.</P></Section>
      <Section title="12. Fees and taxes"><P>If Strap introduces paid plans, fees, taxes, usage limits or transaction charges, the applicable commercial terms shown at checkout or in your order form will govern. Unless expressly stated, merchant taxes, duties, levies and regulatory obligations relating to the merchant's business remain the merchant's responsibility.</P></Section>
      <Section title="13. Acceptable use"><P>You must not:</P><UL><li>reverse engineer, exploit, disrupt or attempt to bypass Strap security controls;</li><li>access another merchant's data without authorization;</li><li>use Strap for fraud, money laundering, scams, phishing or unlawful transactions;</li><li>upload malware or content intended to damage the service;</li><li>scrape or systematically copy private platform data;</li><li>impersonate Strap, another merchant or another person;</li><li>use Strap to violate privacy, intellectual-property or consumer-protection rights;</li><li>interfere with service availability or attempt to overwhelm Strap infrastructure.</li></UL></Section>
      <Section title="14. Intellectual property"><P>Strap and its software, branding, interfaces, documentation, designs and original platform content are owned by Strap or its licensors and are protected by applicable intellectual-property law. These Terms give you a limited, revocable, non-exclusive right to use the service for your internal business purposes while your account is permitted to use Strap.</P><P>You may not copy Strap's interface, branding or proprietary materials for a competing service except as permitted by law or written permission.</P></Section>
      <Section title="15. Feedback and ratings"><P>If you submit suggestions, feedback or feature requests, you grant Strap a non-exclusive right to use that feedback to improve the service without owing you a separate fee, provided Strap does not publicly disclose confidential personal information through that use. Public store ratings and reports may be moderated or removed where they violate platform rules or applicable law.</P></Section>
      <Section title="16. Privacy and data processing"><P>Our Privacy Policy explains Strap's processing of personal data. Where Strap processes merchant-controlled customer or staff data on the merchant's instructions, the parties may need a separate data-processing agreement or other contractual terms depending on the nature and scale of the processing. The merchant remains responsible for lawful collection and appropriate notices for data it controls.</P></Section>
      <Section title="17. Third-party services"><P>Strap may depend on hosting, authentication, storage, email, analytics, payment, AI/OCR, browser and hardware services operated by third parties. Those services may have their own terms and may be unavailable from time to time. Strap is not responsible for independent third-party products except to the extent required by law or a separate agreement.</P></Section>
      <Section title="18. Availability, maintenance and changes"><P>We aim to keep Strap reliable but do not promise uninterrupted availability. Maintenance, security events, provider outages, network failures, device problems or events beyond our reasonable control can interrupt service. We may change, suspend or retire features when reasonably necessary for security, legal compliance, technical improvements or product development.</P></Section>
      <Section title="19. Suspension and termination"><P>We may suspend or terminate access where reasonably necessary to protect Strap, users or third parties, respond to unlawful or abusive activity, comply with law, address security risks, or where an applicable paid subscription ends. Where practical, we will provide notice and an opportunity to resolve the issue unless immediate action is required.</P><P>After termination, data may remain available for a limited period for export, legal retention, backup or security purposes. Deletion is subject to the Privacy Policy and applicable legal obligations.</P></Section>
      <Section title="20. Disclaimers"><P>To the maximum extent permitted by applicable law, Strap is provided on an “as available” basis. We do not guarantee that automated imports, reports, inventory values, forecasts, receipt designs, hardware connections or other generated outputs are error-free or suitable for every legal, accounting, tax or operational purpose.</P><P>You are responsible for verifying important information before relying on it, particularly prices, stock, taxes, customer information, financial reports and automated product extraction.</P></Section>
      <Section title="21. Liability"><P>Nothing in these Terms excludes or limits liability that cannot lawfully be excluded or limited under applicable law, including liability for fraud or other mandatory statutory protections. Subject to that limitation, Strap is not responsible for indirect or consequential loss, loss caused by unauthorized access resulting from your failure to secure credentials/devices, or loss caused by merchant content or third-party services.</P><P>Any contractual liability cap applicable to Strap should be confirmed by counsel and aligned with the pricing and commercial model before this document is relied upon.</P></Section>
      <Section title="22. Indemnity"><P>To the extent permitted by law, a merchant is responsible for claims arising from its unlawful products, misleading listings, infringement of third-party rights, violation of consumer law, unauthorized personal-data processing, or misuse of Strap. This clause does not require a consumer to waive mandatory rights.</P></Section>
      <Section title="23. Disputes and governing law"><P>These Terms are intended to be governed by the laws of the Federal Republic of Nigeria, subject to any mandatory rights or protections that cannot lawfully be excluded. Before publication, Strap should insert the agreed Nigerian dispute-resolution forum, court jurisdiction or arbitration mechanism after obtaining legal advice.</P></Section>
      <Section title="24. Changes to these Terms"><P>We may update these Terms when the service changes, law changes or for security and operational reasons. Material changes will be communicated where appropriate. Continued use after the effective date of an updated version may constitute acceptance to the extent permitted by law.</P></Section>
      <Section title="25. Severability and waiver"><P>If a court or competent authority finds a provision unenforceable, the remaining provisions will continue to the extent permitted by law. A failure to enforce a provision immediately does not waive the right to enforce it later.</P></Section>
      <Section title="26. Contact and complaints"><P>General support: <strong className="text-foreground">[SUPPORT EMAIL]</strong><br />Legal notices: <strong className="text-foreground">[LEGAL EMAIL]</strong><br />Privacy: <strong className="text-foreground">[PRIVACY/DPO EMAIL]</strong><br />Address: <strong className="text-foreground">[REGISTERED BUSINESS ADDRESS]</strong></P><P>Consumers using a merchant's storefront should normally first contact that merchant using the contact details displayed on the storefront. Nothing in these Terms removes any mandatory right to complain to a competent regulator or seek a remedy available under Nigerian law.</P></Section>
    </div>
  </main><SiteFooter /></div>;
}
