import { useState } from "react";
import { CalendarDays, ReceiptText } from "lucide-react";
import { BottomSheet, BottomSheetContent, BottomSheetDescription, BottomSheetFooter, BottomSheetHeader, BottomSheetTitle } from "@/components/ui/bottom-sheet";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

export const EXPENSE_CATEGORIES=["Rent & Utilities","Salaries & Wages","Transport & Logistics","Supplies & Packaging","Equipment & Repairs","Marketing & Ads","Licensing & Taxes","General & Other"] as const;
export function AddExpenseSheet({open,onOpenChange,currency,onSave,saving=false}:{open:boolean;onOpenChange:(open:boolean)=>void;currency:string;onSave:(value:{amount:number;category:string;date:string;description:string})=>Promise<void>|void;saving?:boolean}){const [amount,setAmount]=useState("");const [category,setCategory]=useState(EXPENSE_CATEGORIES[0]);const [date,setDate]=useState(()=>new Date().toISOString().slice(0,10));const [description,setDescription]=useState("");const submit=async(e:React.FormEvent)=>{e.preventDefault();const value=Number(amount);if(!Number.isFinite(value)||value<=0)return;await onSave({amount:value,category,date,description});setAmount("");setDescription("")};return <BottomSheet open={open} onOpenChange={onOpenChange}><BottomSheetContent className="max-h-[92dvh] overflow-y-auto"><BottomSheetHeader><div className="flex size-10 items-center justify-center rounded-xl bg-secondary"><ReceiptText className="size-5"/></div><BottomSheetTitle className="mt-3">Add expense</BottomSheetTitle><BottomSheetDescription>Record a business cost without leaving your current work.</BottomSheetDescription></BottomSheetHeader><form onSubmit={submit} className="space-y-4 px-4 pb-2"><div><Label htmlFor="quick-expense-amount">Amount ({currency})</Label><Input id="quick-expense-amount" inputMode="decimal" type="number" min="0.01" step="0.01" required value={amount} onChange={e=>setAmount(e.target.value)} placeholder="0.00" className="mt-1 h-12 text-lg"/></div><div><Label>Category</Label><Select value={category} onValueChange={setCategory}><SelectTrigger className="mt-1 h-12 w-full"><SelectValue/></SelectTrigger><SelectContent>{EXPENSE_CATEGORIES.map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></div><div><Label htmlFor="quick-expense-date">Date</Label><div className="relative mt-1"><CalendarDays className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input id="quick-expense-date" type="date" required value={date} onChange={e=>setDate(e.target.value)} className="h-12 pl-10"/></div></div><div><Label htmlFor="quick-expense-description">Note <span className="font-normal text-muted-foreground">(optional)</span></Label><Textarea id="quick-expense-description" value={description} onChange={e=>setDescription(e.target.value)} placeholder="What was this expense for?" className="mt-1"/></div><BottomSheetFooter className="px-0 pb-2"><Button type="button" variant="outline" onClick={()=>onOpenChange(false)} className="h-11 flex-1">Cancel</Button><Button type="submit" disabled={saving||!amount} className="h-11 flex-1">{saving?"Saving…":"Add expense"}</Button></BottomSheetFooter></form></BottomSheetContent></BottomSheet>}
