import { Link } from "@tanstack/react-router";
import { ArrowRight, BarChart3, Check, CreditCard, Globe2, PackageSearch, ScanLine, ShieldCheck, Users, Wallet, Zap } from "lucide-react";

const plans = [
  { name: "Free", price: "₦0", description: "Run your counter and manage the essentials.", features: ["POS & offline sales", "Products & inventory", "Customers & expenses", "Basic orders & reports"] },
  { name: "Business", price: "₦3,000", description: "Open your shop online and unlock storefront tools.", featured: true, features: ["Everything in Free", "Online Store", "Storefront categories", "List, compact & large layouts", "Featured products", "Store data export"] },
  { name: "Pro", price: "₦5,000", description: "Advanced control for growing retail operations.", features: ["Everything in Business", "Advanced inventory tools", "Stock calculation tools", "Advanced reports", "Priority Pro features"] },
];

const cards = [
  [PackageSearch, "Find stock before it becomes a problem", "See low-stock products, stock value and product activity in one place."],
  [BarChart3, "Turn activity into useful signals", "Sales, expenses and inventory work together so you can understand performance."],
  [Users, "Give every teammate the right workspace", "Owners, managers and cashiers get the access they need."],
] as const;

export function LandingUpgrades() {
  return (
    <>
      <section id="about" className="border-y border-border bg-secondary/35 px-4 py-20 sm:px-6 sm:py-28">
        <div className="mx-auto max-w-7xl">
          <p className="text-label-caps text-accent-ink">Why Strap</p>
          <h2 className="text-display-md mt-4">Built around the way a real shop actually moves.</h2>
          <p className="mt-5 max-w-3xl text-lg leading-8 text-muted-foreground">Strap connects sales, stock, expenses, customers and online orders into one operating flow instead of making you copy information between tools.</p>
          <div className="mt-10 grid gap-4 md:grid-cols-3">{cards.map(([Icon, title, body]) => <article key={title} className="rounded-3xl border border-border bg-background p-6"><span className="flex size-11 items-center justify-center rounded-xl bg-accent-soft text-accent-ink"><Icon className="size-5" /></span><h3 className="mt-5 font-display text-xl font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{body}</p></article>)}</div>
        </div>
      </section>

      <section id="pricing" className="border-y border-border bg-background px-4 py-20 sm:px-6 sm:py-28">
        <div className="mx-auto max-w-7xl">
          <div className="mx-auto max-w-3xl text-center"><p className="text-label-caps text-accent-ink">Simple pricing</p><h2 className="text-display-md mt-4">Start free. Pay when your shop is ready to sell online.</h2><p className="mt-5 text-lg leading-8 text-muted-foreground">The counter stays useful on Free. The Online Store starts at ₦3,000/month.</p></div>
          <div className="mt-12 grid gap-5 lg:grid-cols-3">{plans.map((plan) => <article key={plan.name} className={`relative rounded-[1.75rem] border p-6 sm:p-7 ${plan.featured ? "border-accent bg-accent-soft/35 shadow-lg" : "border-border bg-background"}`}>{plan.featured && <span className="absolute right-5 top-5 rounded-full bg-accent px-3 py-1 text-[11px] font-bold text-accent-foreground">Most popular</span>}<h3 className="font-display text-2xl font-bold">{plan.name}</h3><p className="mt-3 min-h-12 text-sm leading-6 text-muted-foreground">{plan.description}</p><div className="mt-6 flex items-end gap-1"><span className="font-display text-4xl font-bold tracking-tight">{plan.price}</span>{plan.name !== "Free" && <span className="pb-1 text-sm text-muted-foreground">/ month</span>}</div><Link to="/auth" className={`mt-6 inline-flex w-full items-center justify-center gap-2 rounded-xl px-5 py-3 font-semibold ${plan.featured ? "bg-accent text-accent-foreground" : "border border-border bg-background hover:bg-secondary"}`}>Choose {plan.name}<ArrowRight className="size-4" /></Link><ul className="mt-7 space-y-3">{plan.features.map((feature) => <li key={feature} className="flex items-start gap-3 text-sm"><Check className="mt-0.5 size-4 shrink-0 text-accent-ink" />{feature}</li>)}</ul>{plan.name === "Free" && <p className="mt-6 border-t border-border pt-4 text-xs text-muted-foreground">Online Store is not included in Free.</p>}</article>)}</div>
        </div>
      </section>

      <section id="inventory" className="px-4 py-20 sm:px-6 sm:py-28"><div className="mx-auto max-w-7xl grid gap-10 lg:grid-cols-2 lg:items-center"><div><p className="text-label-caps text-accent-ink">Inventory intelligence</p><h2 className="text-display-md mt-4">Know what you have before customers ask.</h2><p className="mt-5 text-lg leading-8 text-muted-foreground">Search by name, SKU or barcode, filter products and spot stock that needs attention.</p><div className="mt-7 grid gap-3 sm:grid-cols-2">{["Low-stock alerts", "Out-of-stock filters", "Stock-value tracking", "Bulk quantity updates"].map((item) => <div key={item} className="flex items-center gap-3 rounded-xl border border-border bg-background p-4 text-sm font-semibold"><Check className="size-4 text-accent-ink" />{item}</div>)}</div></div><div className="rounded-[2rem] bg-neutral-950 p-7 text-white"><div className="flex items-center gap-3"><PackageSearch className="size-5 text-accent" /><p className="font-semibold">Stock control</p></div><div className="mt-6 space-y-3">{[["Available", "124 products"], ["Low stock", "12 products"], ["Out of stock", "3 products"], ["Inventory value", "₦1,842,500"]].map(([label, value]) => <div key={label} className="flex justify-between rounded-xl border border-white/10 bg-white/[.06] p-4"><span className="text-sm text-white/70">{label}</span><span className="font-semibold">{value}</span></div>)}</div></div></div></section>

      <section id="checkout" className="border-y border-white/10 bg-neutral-950 px-4 py-20 text-white sm:px-6 sm:py-28"><div className="mx-auto max-w-7xl grid gap-12 lg:grid-cols-[1fr_.9fr] lg:items-center"><div><p className="text-label-caps text-accent">Fast checkout</p><h2 className="text-display-md mt-4">From product search to completed sale without the clutter.</h2><p className="mt-5 text-lg leading-8 text-white/75">Build a cart, scan products, choose payment and finish the transaction while Strap keeps stock and sales connected.</p><Link to="/auth" className="mt-7 inline-flex items-center gap-2 font-semibold text-accent">Open the register <ArrowRight className="size-4" /></Link></div><div className="rounded-[2rem] border border-white/10 bg-white/[.07] p-7"><div className="flex items-center gap-3"><CreditCard className="size-5 text-accent" /><p className="font-semibold">A clean counter flow</p></div><div className="mt-6 space-y-2">{["Search or scan a product", "Build the current cart", "Choose cash, card, transfer or credit", "Confirm payment", "Preview or print the receipt"].map((item, i) => <div key={item} className="flex items-center gap-3 rounded-xl bg-white/[.06] p-3"><span className="flex size-7 items-center justify-center rounded-full bg-accent text-xs font-bold text-accent-foreground">{i + 1}</span><span className="text-sm text-white/80">{item}</span></div>)}</div></div></div></section>

      <section id="online-store" className="px-4 py-20 sm:px-6 sm:py-28"><div className="mx-auto max-w-7xl grid gap-10 lg:grid-cols-2 lg:items-center"><div><p className="text-label-caps text-accent-ink">Online storefront</p><h2 className="text-display-md mt-4">Give your shop a front door on the internet.</h2><p className="mt-5 text-lg leading-8 text-muted-foreground">Publish products, organise them into categories, feature the products you want customers to notice and manage online orders from the same workspace.</p><div className="mt-7 flex flex-wrap gap-2">{["Shareable catalog", "Categories", "Featured products", "Product layouts", "Online orders"].map((item) => <span key={item} className="rounded-full border border-border bg-background px-4 py-2 text-xs font-semibold">{item}</span>)}</div></div><div className="rounded-[2rem] border border-border bg-secondary p-7"><div className="flex items-center justify-between"><div><p className="text-xs uppercase tracking-[.16em] text-muted-foreground">Your online store</p><h3 className="mt-2 font-display text-2xl font-bold">Open 24/7</h3></div><Globe2 className="size-7 text-accent-ink" /></div></div></div></section>

      <section id="insights" className="border-y border-border bg-secondary/35 px-4 py-20 sm:px-6 sm:py-28"><div className="mx-auto max-w-7xl"><p className="text-label-caps text-accent-ink">Insights</p><h2 className="text-display-md mt-4">Stop guessing where the money went.</h2><p className="mt-5 max-w-2xl text-lg leading-8 text-muted-foreground">Use sales, expenses, payment records and stock information together to understand the health of the shop.</p><div className="mt-10 grid gap-4 md:grid-cols-3">{[[Wallet, "Money movement", "Keep sales, expenses and payment methods together."], [BarChart3, "Performance", "See useful totals and trends without rebuilding reports manually."], [Zap, "Better decisions", "Use today's activity to make tomorrow's decisions clearer."]].map(([Icon, title, body]) => <article key={title as string} className="rounded-2xl border border-border bg-background p-6"><Icon className="size-5 text-accent-ink" /><h3 className="mt-4 font-display text-lg font-bold">{title as string}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{body as string}</p></article>)}</div></div></section>

      <section id="teams" className="px-4 py-20 sm:px-6 sm:py-28"><div className="mx-auto max-w-7xl grid gap-12 lg:grid-cols-2 lg:items-center"><div><p className="text-label-caps text-accent-ink">Team access</p><h2 className="text-display-md mt-4">Let people work without giving everyone the keys.</h2><p className="mt-5 max-w-xl text-lg leading-8 text-muted-foreground">Strap supports owner, manager and cashier roles so day-to-day selling stays fast while management controls remain protected.</p></div><div className="space-y-3">{[[ShieldCheck, "Owner", "Full store management"], [Users, "Manager", "Operational management"], [Zap, "Cashier", "Fast selling workflows"]].map(([Icon, title, body]) => <div key={title as string} className="flex items-center gap-4 rounded-2xl border border-border bg-background p-5"><Icon className="size-5 text-accent-ink" /><div><p className="font-display font-bold">{title as string}</p><p className="mt-1 text-sm text-muted-foreground">{body as string}</p></div></div>)}</div></div></section>

      <section id="security" className="border-y border-border bg-background px-4 py-20 sm:px-6 sm:py-28"><div className="mx-auto max-w-5xl text-center"><ShieldCheck className="mx-auto size-7 text-accent-ink" /><h2 className="text-display-sm mt-6">Your business deserves a system you can trust.</h2><p className="mx-auto mt-4 max-w-2xl leading-7 text-muted-foreground">Authentication and controlled access keep business activity inside the right workspace.</p></div></section>
    </>
  );
}
