import { Link } from "@tanstack/react-router";
import { ArrowRight, BarChart3, BookOpen, Boxes, CircleHelp, CreditCard, Globe2, Mail, Printer, Receipt, ScanLine, Settings2, ShieldCheck, ShoppingCart, Smartphone, Store, Users, Wallet, Zap } from "lucide-react";

const COLUMNS = [
  { title: "Product", links: [["Point of sale", "#how-it-works"], ["Inventory & stock", "#features"], ["Online store", "#features"], ["Reports & insights", "#features"], ["Expenses", "#features"], ["Shop teams", "#features"]] },
  { title: "Selling", links: [["Fast checkout", "#features"], ["Barcode & QR scanning", "#features"], ["Cash & payments", "#features"], ["Receipts", "#features"], ["Receipt designer", "#features"], ["Printer workflows", "#features"]] },
  { title: "Operations", links: [["Stock management", "#features"], ["Low-stock tracking", "#features"], ["Online catalog", "#features"], ["Online orders", "#features"], ["Store settings", "#features"], ["Business insights", "#features"]] },
] as const;

const RESOURCES = [["Help Centre", "/support", CircleHelp], ["Guides & documentation", "/support", BookOpen], ["Getting started", "/support", Zap], ["Scanner setup", "/support", ScanLine], ["Receipt printing help", "/support", Printer], ["Contact support", "/support", Mail]] as const;

export function SiteHeader() {
  return <header className="sticky top-0 z-50 border-b border-border bg-surface/90 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4 px-4 py-4 sm:px-6"><Link to="/" className="flex shrink-0 items-center gap-2"><span className="flex size-8 items-center justify-center rounded-full bg-accent"><span className="size-3 rotate-45 rounded-[3px] bg-foreground" /></span><span className="font-display text-xl font-bold tracking-tight">KUDI.</span></Link><nav className="hidden items-center gap-6 text-sm font-medium md:flex"><a href="#features" className="hover:text-accent-ink">Features</a><a href="#how-it-works" className="hover:text-accent-ink">How it works</a><a href="#features" className="hover:text-accent-ink">Online store</a><a href="#features" className="hover:text-accent-ink">Insights</a><Link to="/support" className="hover:text-accent-ink">Help</Link></nav><div className="flex items-center gap-2"><Link to="/support" className="hidden rounded-full px-4 py-2.5 text-sm font-semibold hover:bg-secondary sm:inline-flex">Help</Link><Link to="/auth" className="inline-flex items-center rounded-full bg-foreground px-5 py-2.5 text-sm font-semibold text-background hover:bg-accent hover:text-accent-foreground">Open register</Link></div></div></header>;
}

export function SiteFooter() {
  const year = new Date().getFullYear();
  return <footer className="border-t border-background/10 bg-foreground text-background">
    <div className="mx-auto max-w-7xl px-4 pb-8 pt-16 sm:px-6 sm:pt-20">
      <section className="grid gap-10 overflow-hidden rounded-[2rem] border border-background/10 bg-background/[.04] p-6 sm:p-8 lg:grid-cols-[1fr_auto] lg:items-center lg:p-10"><div><p className="text-label-caps text-accent">Kudi for everyday retail</p><h2 className="mt-3 max-w-2xl font-display text-3xl font-bold tracking-tight sm:text-4xl">One place to sell, stock, understand and grow.</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-background/55 sm:text-base">From the first scan of the morning to the final report at night, Kudi keeps the important parts of your shop connected.</p></div><Link to="/auth" className="inline-flex items-center justify-center gap-2 rounded-xl bg-accent px-6 py-3.5 font-semibold text-accent-foreground hover:-translate-y-0.5">Start selling free <ArrowRight className="size-4" /></Link></section>

      <section className="grid gap-12 border-b border-background/10 py-14 lg:grid-cols-[1fr_2.1fr]"><div className="max-w-md"><Link to="/" className="inline-flex items-center gap-2"><span className="flex size-9 items-center justify-center rounded-full bg-accent"><span className="size-3.5 rotate-45 rounded-[3px] bg-foreground" /></span><span className="font-display text-2xl font-bold tracking-tight">KUDI.</span></Link><p className="mt-5 text-base leading-7 text-background/60">Kudi is a practical retail operating system for shops that want one clear place to sell, manage stock, track money, understand performance and build an online storefront.</p><div className="mt-6 grid gap-2 text-xs text-background/50 sm:grid-cols-2"><span className="inline-flex items-center gap-2"><Store className="size-3.5 text-accent" />Everyday retail</span><span className="inline-flex items-center gap-2"><Smartphone className="size-3.5 text-accent" />Desktop & mobile</span><span className="inline-flex items-center gap-2"><ShieldCheck className="size-3.5 text-accent" />Protected workspace</span><span className="inline-flex items-center gap-2"><Users className="size-3.5 text-accent" />Shop teams</span></div></div><div className="grid grid-cols-2 gap-x-6 gap-y-10 sm:grid-cols-3">{COLUMNS.map((column) => <div key={column.title}><p className="text-label-caps text-background/40">{column.title}</p><div className="mt-4 space-y-3">{column.links.map(([label, href]) => <a key={label} href={href} className="block text-sm text-background/60 hover:text-accent">{label}</a>)}</div></div>)}</div></section>

      <section className="grid gap-10 border-b border-background/10 py-14 sm:grid-cols-2 lg:grid-cols-4"><div><p className="text-label-caps text-background/40">Resources</p><div className="mt-4 space-y-3">{RESOURCES.map(([label, href, Icon]) => <Link key={label} to={href as "/support"} className="flex items-center gap-2 text-sm text-background/60 hover:text-accent"><Icon className="size-3.5 shrink-0" />{label}</Link>)}</div></div><div><p className="text-label-caps text-background/40">Account</p><div className="mt-4 space-y-3"><Link to="/auth" className="block text-sm text-background/60 hover:text-accent">Sign in</Link><Link to="/auth" className="block text-sm text-background/60 hover:text-accent">Create account</Link><Link to="/support" className="block text-sm text-background/60 hover:text-accent">Account help</Link></div></div><div><p className="text-label-caps text-background/40">Legal & trust</p><div className="mt-4 space-y-3"><Link to="/privacy" className="block text-sm text-background/60 hover:text-accent">Privacy policy</Link><Link to="/terms" className="block text-sm text-background/60 hover:text-accent">Terms of service</Link><Link to="/support" className="block text-sm text-background/60 hover:text-accent">Safety & store reporting</Link></div></div><div><p className="text-label-caps text-background/40">Need a hand?</p><p className="mt-4 text-sm leading-6 text-background/50">Find step-by-step help for setup, scanners, receipts, online selling and everyday Kudi workflows.</p><Link to="/support" className="mt-3 inline-flex items-center gap-2 text-sm font-semibold text-accent">Visit Help Centre <ArrowRight className="size-4" /></Link></div></section>

      <section className="grid gap-4 border-b border-background/10 py-10 sm:grid-cols-2 lg:grid-cols-4"><div className="flex gap-3 rounded-2xl border border-background/10 bg-background/[.03] p-4"><ShoppingCart className="size-5 shrink-0 text-accent" /><div><p className="text-sm font-semibold">Fast checkout</p><p className="mt-1 text-xs leading-5 text-background/45">Search, scan, pay and finish the sale.</p></div></div><div className="flex gap-3 rounded-2xl border border-background/10 bg-background/[.03] p-4"><Boxes className="size-5 shrink-0 text-accent" /><div><p className="text-sm font-semibold">Stock control</p><p className="mt-1 text-xs leading-5 text-background/45">Know what is available and what needs attention.</p></div></div><div className="flex gap-3 rounded-2xl border border-background/10 bg-background/[.03] p-4"><BarChart3 className="size-5 shrink-0 text-accent" /><div><p className="text-sm font-semibold">Clear insights</p><p className="mt-1 text-xs leading-5 text-background/45">Turn daily activity into useful business information.</p></div></div><div className="flex gap-3 rounded-2xl border border-background/10 bg-background/[.03] p-4"><Globe2 className="size-5 shrink-0 text-accent" /><div><p className="text-sm font-semibold">Sell online</p><p className="mt-1 text-xs leading-5 text-background/45">Give customers a simple way to find your products.</p></div></div></section>

      <div className="mt-8 flex flex-col gap-5 text-xs text-background/40 md:flex-row md:items-center md:justify-between"><p>© {year} Kudi. Built for modern shops and everyday retail.</p><div className="flex flex-wrap gap-x-5 gap-y-2"><Link to="/privacy" className="hover:text-background">Privacy</Link><Link to="/terms" className="hover:text-background">Terms</Link><Link to="/support" className="hover:text-background">Help</Link><Link to="/auth" className="hover:text-background">Open register</Link><span className="inline-flex items-center gap-1.5"><CreditCard className="size-3.5" />Payments</span><span className="inline-flex items-center gap-1.5"><Receipt className="size-3.5" />Receipts</span><span className="inline-flex items-center gap-1.5"><Settings2 className="size-3.5" />Shop tools</span></div></div>
    </div>
  </footer>;
}
