import { createFileRoute } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { CheckSquare, Eye, EyeOff, Filter, Globe2, RefreshCw, Search, Star, Tag, X } from "lucide-react";
import { toast } from "sonner";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { AppShell } from "@/components/shell/AppShell";
import { useStoreContext } from "@/components/shell/StoreProvider";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { formatMoney } from "@/lib/currency";
import type { OnlineProductRow } from "@/integrations/supabase/online-types";

export const Route = createFileRoute("/_authenticated/online-store/catalog")({ ssr: false, component: OnlineCatalogPage });
type Product = { id: string; name: string; category: string; price: number; image_url: string; is_active: boolean };
type FilterMode = "all" | "published" | "hidden" | "featured";

function OnlineCatalogPage() {
  const { store, role } = useStoreContext(); const storeId = store?.id; const canManage = role === "owner" || role === "manager";
  const queryClient = useQueryClient(); const [query, setQuery] = useState(""); const [category, setCategory] = useState("all"); const [status, setStatus] = useState<FilterMode>("all"); const [selected, setSelected] = useState<Set<string>>(new Set()); const [sort, setSort] = useState<"name" | "price">("name");
  const productsQuery = useQuery({ queryKey: ["online-catalog-products", storeId], enabled: Boolean(storeId), queryFn: async () => { const [{ data: products, error: pe }, { data: online, error: oe }] = await Promise.all([supabase.from("products").select("id,name,category,price,image_url,is_active").eq("store_id", storeId!).eq("is_active", true), supabase.from("online_products").select("*").eq("store_id", storeId!)]); if (pe) throw new Error(pe.message); if (oe) throw new Error(oe.message); const map = new Map((online ?? []).map((item) => [item.product_id, item])); return (products ?? []).map((product) => ({ product, online: map.get(product.id) ?? null })); } });
  const rows = productsQuery.data ?? [];
  const categories = useMemo(() => Array.from(new Set(rows.map((r) => r.product.category).filter(Boolean))).sort(), [rows]);
  const filtered = useMemo(() => rows.filter(({ product, online }) => { const text = `${product.name} ${product.category}`.toLowerCase(); const matchesText = text.includes(query.toLowerCase()); const matchesCategory = category === "all" || product.category === category; const published = Boolean(online?.enabled); const matchesStatus = status === "all" || (status === "published" && published) || (status === "hidden" && !published) || (status === "featured" && Boolean(online?.featured)); return matchesText && matchesCategory && matchesStatus; }).sort((a, b) => sort === "name" ? a.product.name.localeCompare(b.product.name) : Number(b.product.price) - Number(a.product.price)), [rows, query, category, status, sort]);
  const selectedVisible = filtered.filter((r) => selected.has(r.product.id)).length;
  const allVisibleSelected = filtered.length > 0 && selectedVisible === filtered.length;
  function toggleSelect(id: string) { setSelected((prev) => { const next = new Set(prev); next.has(id) ? next.delete(id) : next.add(id); return next; }); }
  function selectVisible() { setSelected((prev) => { const next = new Set(prev); if (allVisibleSelected) filtered.forEach((r) => next.delete(r.product.id)); else filtered.forEach((r) => next.add(r.product.id)); return next; }); }
  async function bulkPublish(enabled: boolean) { if (!storeId || !canManage || selected.size === 0) return; const ids = Array.from(selected); for (const productId of ids) { const current = rows.find((r) => r.product.id === productId)?.online; const result = current ? await supabase.from("online_products").update({ enabled }).eq("product_id", productId) : await supabase.from("online_products").insert({ store_id: storeId, product_id: productId, enabled, featured: false, description: "" }); if (result.error) { toast.error(result.error.message); return; } } setSelected(new Set()); await queryClient.invalidateQueries({ queryKey: ["online-catalog-products", storeId] }); toast.success(`${ids.length} product${ids.length === 1 ? "" : "s"} ${enabled ? "published" : "hidden"}`); }
  async function bulkFeature(featured: boolean) { if (!storeId || !canManage || selected.size === 0) return; const publishable = rows.filter((r) => selected.has(r.product.id) && r.online?.enabled); if (!publishable.length) { toast.error("Select published products to feature them."); return; } const results = await Promise.all(publishable.map(({ product }) => supabase.from("online_products").update({ featured }).eq("product_id", product.id))); const failed = results.find((r) => r.error); if (failed?.error) { toast.error(failed.error.message); return; } await queryClient.invalidateQueries({ queryKey: ["online-catalog-products", storeId] }); toast.success(`${publishable.length} product${publishable.length === 1 ? "" : "s"} ${featured ? "featured" : "unfeatured"}`); }
  async function toggle(product: Product, current: OnlineProductRow | null) { if (!storeId || !canManage) return; const next = !(current?.enabled ?? false); const result = current ? await supabase.from("online_products").update({ enabled: next }).eq("product_id", product.id) : await supabase.from("online_products").insert({ store_id: storeId, product_id: product.id, enabled: true, featured: false, description: "" }); if (result.error) { toast.error(result.error.message); return; } await queryClient.invalidateQueries({ queryKey: ["online-catalog-products", storeId] }); toast.success(next ? `${product.name} published` : `${product.name} hidden`); }
  async function toggleFeatured(product: Product, current: OnlineProductRow | null) { if (!current?.enabled) { toast.error("Publish the product before featuring it."); return; } const result = await supabase.from("online_products").update({ featured: !current.featured }).eq("product_id", product.id); if (result.error) { toast.error(result.error.message); return; } await queryClient.invalidateQueries({ queryKey: ["online-catalog-products", storeId] }); }
  return <AppShell title="Online catalog">
    <div className="border border-border bg-accent-soft p-5"><div className="flex items-start gap-3"><span className="flex size-10 items-center justify-center bg-accent"><Globe2 className="size-5" /></span><div><h2 className="font-display font-semibold">Publish your catalog faster</h2><p className="mt-1 text-sm text-muted-foreground">Search, filter, select multiple products and publish or hide them together.</p></div></div></div>
    <div className="mt-5 space-y-3 rounded-2xl border border-border bg-surface p-4 shadow-sm"><div className="flex flex-col gap-3 lg:flex-row"><label className="relative flex-1"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><input className="field pl-10" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search products or categories…" /></label><select className="field lg:w-48" value={category} onChange={(e) => setCategory(e.target.value)}><option value="all">All categories</option>{categories.map((c) => <option key={c} value={c}>{c}</option>)}</select><select className="field lg:w-36" value={status} onChange={(e) => setStatus(e.target.value as FilterMode)}><option value="all">All status</option><option value="published">Published</option><option value="hidden">Hidden</option><option value="featured">Featured</option></select><select className="field lg:w-36" value={sort} onChange={(e) => setSort(e.target.value as "name" | "price")}><option value="name">Name</option><option value="price">Price</option></select><Button variant="outline" onClick={() => void productsQuery.refetch()}><RefreshCw className="mr-2 size-4" />Refresh</Button></div><div className="flex flex-wrap items-center gap-2 text-xs text-muted-foreground"><Filter className="size-3.5" /> Showing {filtered.length} of {rows.length} products</div></div>
    {selected.size > 0 && <div className="sticky top-[70px] z-30 mt-3 flex flex-wrap items-center gap-2 rounded-2xl border border-border bg-surface/95 p-3 shadow-lg backdrop-blur"><span className="mr-2 text-sm font-semibold">{selected.size} selected</span><Button size="sm" disabled={!canManage} onClick={() => void bulkPublish(true)}><Eye className="mr-1.5 size-4" />Publish</Button><Button size="sm" variant="outline" disabled={!canManage} onClick={() => void bulkPublish(false)}><EyeOff className="mr-1.5 size-4" />Hide</Button><Button size="sm" variant="outline" disabled={!canManage} onClick={() => void bulkFeature(true)}><Star className="mr-1.5 size-4" />Feature</Button><Button size="sm" variant="outline" disabled={!canManage} onClick={() => void bulkFeature(false)}><Star className="mr-1.5 size-4" />Unfeature</Button><button className="ml-auto rounded-lg p-2 hover:bg-secondary" onClick={() => setSelected(new Set())}><X className="size-4" /></button></div>}
    <div className="mt-4 overflow-hidden rounded-2xl border border-border bg-surface shadow-sm"><div className="flex items-center gap-3 border-b border-border px-4 py-3"><button type="button" onClick={selectVisible} disabled={!canManage || filtered.length === 0} className="flex items-center gap-2 text-sm font-semibold"><CheckSquare className="size-4" />{allVisibleSelected ? "Clear visible" : "Select visible"}</button><span className="text-xs text-muted-foreground">{selectedVisible} visible selected</span></div>{productsQuery.isLoading ? <div className="space-y-3 p-5"><Skeleton className="h-16 w-full" /><Skeleton className="h-16 w-full" /></div> : productsQuery.error ? <p className="p-5 text-sm text-destructive">Could not load products.</p> : filtered.length === 0 ? <p className="p-10 text-center text-sm text-muted-foreground">No products match these filters.</p> : <ul className="divide-y divide-border">{filtered.map(({ product, online }) => { const published = Boolean(online?.enabled); const checked = selected.has(product.id); return <li key={product.id} className={`flex items-center gap-3 px-4 py-4 transition-colors sm:gap-4 ${checked ? "bg-accent-soft/60" : ""}`}><button type="button" disabled={!canManage} onClick={() => toggleSelect(product.id)} className={`flex size-5 shrink-0 items-center justify-center rounded border ${checked ? "border-foreground bg-foreground text-background" : "border-border"}`}>{checked && <CheckSquare className="size-3.5" />}</button><div className="flex size-12 shrink-0 items-center justify-center overflow-hidden rounded-xl bg-secondary">{product.image_url ? <img src={product.image_url} alt="" className="h-full w-full object-cover" /> : <Globe2 className="size-5 text-muted-foreground" />}</div><div className="min-w-0 flex-1"><p className="truncate font-semibold">{product.name}</p><p className="truncate text-xs text-muted-foreground"><Tag className="mr-1 inline size-3" />{product.category || "Uncategorised"} · {formatMoney(Number(product.price), store?.currency ?? "NGN")}</p></div>{published && <button type="button" title="Feature product" onClick={() => void toggleFeatured(product, online)} className={`flex size-9 items-center justify-center rounded-full ${online?.featured ? "bg-accent text-foreground" : "bg-secondary text-muted-foreground"}`}><Star className="size-4" /></button>}<span className={`hidden text-xs font-semibold sm:inline ${published ? "text-success" : "text-muted-foreground"}`}>{published ? "Published" : "Hidden"}</span><Button size="sm" disabled={!canManage} variant={published ? "outline" : "default"} onClick={() => void toggle(product, online)}>{published ? <><EyeOff className="mr-2 size-4" />Hide</> : <><Eye className="mr-2 size-4" />Publish</>}</Button></li>; })}</ul>}</div>
    <div className="mt-4 flex flex-wrap gap-4 text-xs text-muted-foreground"><span>• Search</span><span>• Category filter</span><span>• Status filter</span><span>• Price/name sorting</span><span>• Multi-select</span><span>• Bulk publish/hide</span><span>• Bulk feature</span><span>• Live refresh</span></div>
  </AppShell>;
}
