import { useMemo, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Link } from "@tanstack/react-router";
import { AlertTriangle, ArrowRightLeft, Boxes, CheckCircle2, ChevronRight, CircleDollarSign, Globe2, PackageCheck, Plus, RefreshCw, Truck, Users, Warehouse } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { onlineSupabase as supabase } from "@/integrations/supabase/online-client";
import { useStoreContext } from "@/components/shell/StoreProvider";

const tabs = ["Overview", "Products", "Purchasing", "Transfers", "Discounts", "Loyalty", "Fulfillment", "Shipping", "Domains", "Segments"] as const;
type Tab = typeof tabs[number];
const db = supabase as any;

function Card({ title, hint, children, action }: { title: string; hint?: string; children: React.ReactNode; action?: React.ReactNode }) {
  return <section className="rounded-2xl border border-border bg-surface p-5 shadow-sm"><div className="mb-4 flex items-start justify-between gap-4"><div><h2 className="font-display text-base font-bold tracking-tight">{title}</h2>{hint && <p className="mt-1 text-xs text-muted-foreground">{hint}</p>}</div>{action}</div>{children}</section>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="space-y-1.5"><span className="text-xs font-semibold text-muted-foreground">{label}</span>{children}</label>; }
function Empty({ text }: { text: string }) { return <div className="rounded-xl border border-dashed border-border p-6 text-center text-sm text-muted-foreground">{text}</div>; }
function fmt(value: unknown) { return Number(value ?? 0).toLocaleString("en-NG", { maximumFractionDigits: 2 }); }

export default function CommerceOperations() {
  const { store, branch, branches, role, isLoading } = useStoreContext();
  const [tab, setTab] = useState<Tab>("Overview");
  const canManage = role === "owner" || role === "manager";
  const qc = useQueryClient();
  if (isLoading) return <div className="p-6 text-sm text-muted-foreground">Loading commerce workspace…</div>;
  if (!store) return <div className="p-6"><Empty text="Create or select a store before opening Commerce operations." /></div>;
  if (!canManage) return <div className="mx-auto max-w-2xl p-6"><Card title="Manager access required" hint="Commerce operations can change stock, pricing and fulfilment."><p className="text-sm text-muted-foreground">Ask the store owner or manager to give you the required permission.</p><Link to="/dashboard" className="mt-4 inline-flex text-sm font-semibold text-accent-ink">Back to dashboard <ChevronRight className="ml-1 size-4" /></Link></Card></div>;
  return <div className="mx-auto w-full max-w-[1500px] space-y-5 p-4 pb-10 md:p-6"><header><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-label-caps text-muted-foreground">Commerce operations</p><h1 className="mt-1 font-display text-2xl font-bold tracking-tight md:text-3xl">Run the store behind the storefront.</h1><p className="mt-2 max-w-2xl text-sm text-muted-foreground">Purchasing, inventory intelligence, customer growth and fulfilment in one workspace.</p></div><div className="rounded-2xl border border-border bg-surface px-4 py-3 text-right shadow-sm"><p className="text-xs text-muted-foreground">{store.name}</p><p className="font-semibold">{branch?.name ?? "All branches"}</p></div></div></header><div className="flex gap-2 overflow-x-auto border-b border-border pb-2">{tabs.map((item) => <button key={item} type="button" onClick={() => setTab(item)} className={`whitespace-nowrap rounded-full px-3 py-2 text-xs font-semibold transition ${tab === item ? "bg-accent text-accent-foreground" : "bg-secondary text-muted-foreground hover:text-foreground"}`}>{item}</button>)}</div>{tab === "Overview" && <Overview storeId={store.id} branchId={branch?.id} />} {tab === "Products" && <Products storeId={store.id} />} {tab === "Purchasing" && <Purchasing storeId={store.id} branchId={branch?.id ?? branches[0]?.id} />} {tab === "Transfers" && <Transfers storeId={store.id} branches={branches} />} {tab === "Discounts" && <Discounts storeId={store.id} />} {tab === "Loyalty" && <Loyalty storeId={store.id} />} {tab === "Fulfillment" && <Fulfillment storeId={store.id} />} {tab === "Shipping" && <Shipping storeId={store.id} />} {tab === "Domains" && <Domains storeId={store.id} />} {tab === "Segments" && <Segments storeId={store.id} />}<p className="text-center text-xs text-muted-foreground">Online payments are <span className="font-semibold">Coming Soon</span>. Nothing here activates payment collection.</p><Button variant="ghost" size="sm" className="mx-auto flex" onClick={() => qc.invalidateQueries()}><RefreshCw className="mr-2 size-3.5" />Refresh workspace</Button></div>;
}

function Overview({ storeId, branchId }: { storeId: string; branchId?: string }) {
  const inv = useQuery({ queryKey: ["inventory-intelligence", storeId, branchId], queryFn: async () => { const q = db.from("inventory_intelligence").select("*").eq("store_id", storeId); const { data, error } = await (branchId ? q.eq("branch_id", branchId) : q); if (error) throw error; return data ?? []; } });
  const alerts = useQuery({ queryKey: ["inventory-alerts", storeId], queryFn: async () => { const { data, error } = await db.from("inventory_alerts").select("*").eq("store_id", storeId).eq("status", "open").order("created_at", { ascending: false }).limit(12); if (error) throw error; return data ?? []; } });
  const stats = useMemo(() => { const rows = inv.data ?? []; return { value: rows.reduce((s: number, r: any) => s + Number(r.inventory_cost_value ?? 0), 0), retail: rows.reduce((s: number, r: any) => s + Number(r.retail_value ?? 0), 0), low: rows.filter((r: any) => r.stock_status === "low_stock").length, out: rows.filter((r: any) => r.stock_status === "out_of_stock").length }; }, [inv.data]);
  return <div className="space-y-5"><div className="grid gap-3 md:grid-cols-4">{[["Inventory cost",`₦${fmt(stats.value)}`,Warehouse],["Retail value",`₦${fmt(stats.retail)}`,CircleDollarSign],["Low stock",String(stats.low),AlertTriangle],["Out of stock",String(stats.out),PackageCheck]].map(([label,value,Icon]) => <div key={String(label)} className="rounded-2xl border border-border bg-surface p-4 shadow-sm"><Icon className="size-4 text-muted-foreground" /><p className="mt-4 text-xs text-muted-foreground">{String(label)}</p><p className="mt-1 font-display text-xl font-bold">{String(value)}</p></div>)}</div><div className="grid gap-5 lg:grid-cols-2"><Card title="Inventory intelligence" hint="Live stock health from your branch inventory.">{inv.isLoading ? <p className="text-sm text-muted-foreground">Loading…</p> : <div className="space-y-2">{(inv.data ?? []).slice(0, 10).map((r: any) => <div key={r.product_id + r.branch_id} className="flex items-center justify-between rounded-xl bg-secondary/60 p-3"><div><p className="text-sm font-semibold">{r.product_name ?? r.product_id}</p><p className="text-xs text-muted-foreground">{r.stock_status?.replaceAll("_", " ")}</p></div><p className="font-semibold">{r.quantity ?? 0}</p></div>)}{!inv.data?.length && <Empty text="No inventory intelligence records yet." />}</div>}</Card><Card title="Open inventory alerts" hint="Prioritize stock issues before they become lost sales.">{alerts.isLoading ? <p className="text-sm text-muted-foreground">Loading…</p> : <div className="space-y-2">{(alerts.data ?? []).map((a: any) => <div key={a.id} className="flex items-center justify-between rounded-xl border border-border p-3"><div><p className="text-sm font-semibold">{a.alert_type?.replaceAll("_", " ")}</p><p className="text-xs text-muted-foreground">Current {a.current_quantity} · threshold {a.threshold}</p></div><span className="rounded-full bg-accent-soft px-2 py-1 text-[10px] font-bold uppercase">{a.status}</span></div>)}{!alerts.data?.length && <Empty text="No open inventory alerts." />}</div>}</Card></div></div>;
}

function Products({ storeId }: { storeId: string }) {
  const products = useQuery({ queryKey: ["commerce-products", storeId], queryFn: async () => { const { data, error } = await db.from("products").select("id,name,sku,price").eq("store_id", storeId).order("name").limit(100); if (error) throw error; return data ?? []; } });
  const [variant, setVariant] = useState({ product_id: "", name: "", sku: "", barcode: "", price: "", cost: "", attributes: "" });
  const [bundle, setBundle] = useState({ product_id: "", component_product_id: "", quantity: "1" });
  async function addVariant() { if (!variant.product_id || !variant.name || !variant.price) return; const { error } = await db.from("product_variants").insert({ store_id: storeId, product_id: variant.product_id, name: variant.name, sku: variant.sku || null, barcode: variant.barcode || null, price: Number(variant.price), cost: Number(variant.cost || 0), attributes: variant.attributes ? JSON.parse(variant.attributes) : {}, is_active: true }); if (error) return alert(error.message); setVariant({ product_id:"",name:"",sku:"",barcode:"",price:"",cost:"",attributes:"" }); }
  async function addBundle() { if (!bundle.product_id || !bundle.component_product_id) return; const { error } = await db.from("product_bundles").insert({ store_id: storeId, product_id: bundle.product_id, component_product_id: bundle.component_product_id, quantity: Number(bundle.quantity) }); if (error) return alert(error.message); setBundle({ product_id:"",component_product_id:"",quantity:"1" }); }
  return <div className="grid gap-5 lg:grid-cols-2"><Card title="Product variants" hint="Add SKU/barcode-level options without duplicating your base product."><div className="grid gap-3 md:grid-cols-2"><Field label="Product"><select className="h-10 rounded-md border border-input bg-background px-3 text-sm" value={variant.product_id} onChange={e=>setVariant({...variant,product_id:e.target.value})}><option value="">Choose product</option>{(products.data??[]).map((p:any)=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Field label="Variant name"><Input value={variant.name} onChange={e=>setVariant({...variant,name:e.target.value})} placeholder="Large / Black" /></Field><Field label="SKU"><Input value={variant.sku} onChange={e=>setVariant({...variant,sku:e.target.value})} /></Field><Field label="Barcode"><Input value={variant.barcode} onChange={e=>setVariant({...variant,barcode:e.target.value})} /></Field><Field label="Price"><Input type="number" value={variant.price} onChange={e=>setVariant({...variant,price:e.target.value})} /></Field><Field label="Cost"><Input type="number" value={variant.cost} onChange={e=>setVariant({...variant,cost:e.target.value})} /></Field></div><Button className="mt-4" onClick={addVariant}><Plus className="mr-2 size-4" />Add variant</Button></Card><Card title="Product bundles" hint="Define the components consumed by a sellable bundle."><div className="grid gap-3"><Field label="Bundle product"><select className="h-10 rounded-md border border-input bg-background px-3 text-sm" value={bundle.product_id} onChange={e=>setBundle({...bundle,product_id:e.target.value})}><option value="">Choose bundle</option>{(products.data??[]).map((p:any)=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Field label="Component product"><select className="h-10 rounded-md border border-input bg-background px-3 text-sm" value={bundle.component_product_id} onChange={e=>setBundle({...bundle,component_product_id:e.target.value})}><option value="">Choose component</option>{(products.data??[]).map((p:any)=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Field label="Quantity"><Input type="number" min="1" value={bundle.quantity} onChange={e=>setBundle({...bundle,quantity:e.target.value})} /></Field></div><Button className="mt-4" onClick={addBundle}><Boxes className="mr-2 size-4" />Add component</Button></Card></div>;
}

function Purchasing({ storeId, branchId }: { storeId: string; branchId?: string }) {
  const q = useQuery({ queryKey:["suppliers",storeId], queryFn:async()=>{const {data,error}=await db.from("suppliers").select("*").eq("store_id",storeId).order("name");if(error)throw error;return data??[]} });
  const orders = useQuery({ queryKey:["purchase-orders",storeId], queryFn:async()=>{const {data,error}=await db.from("purchase_orders").select("*").eq("store_id",storeId).order("created_at",{ascending:false}).limit(20);if(error)throw error;return data??[]} });
  const [supplier,setSupplier]=useState({name:"",phone:"",email:"",address:""}); const [po,setPo]=useState({reference:"",supplier_id:"",notes:""});
  async function addSupplier(){if(!supplier.name)return;const {error}=await db.from("suppliers").insert({...supplier,store_id:storeId,is_active:true});if(error)return alert(error.message);setSupplier({name:"",phone:"",email:"",address:""});void q.refetch();}
  async function addPO(){if(!po.reference||!branchId)return;const {error}=await db.from("purchase_orders").insert({store_id:storeId,branch_id:branchId,supplier_id:po.supplier_id||null,reference:po.reference,status:"draft",notes:po.notes||null});if(error)return alert(error.message);setPo({reference:"",supplier_id:"",notes:""});void orders.refetch();}
  async function setStatus(id:string,status:string){const {error}=await db.from("purchase_orders").update({status,...(status==="ordered"?{ordered_at:new Date().toISOString()}:{}),...(status==="received"?{received_at:new Date().toISOString()}:{})}).eq("id",id).eq("store_id",storeId);if(error)return alert(error.message);void orders.refetch();}
  return <div className="space-y-5"><Card title="Suppliers" hint="Keep vendor contact information close to purchasing."><div className="grid gap-3 md:grid-cols-4"><Input placeholder="Supplier name" value={supplier.name} onChange={e=>setSupplier({...supplier,name:e.target.value})}/><Input placeholder="Phone" value={supplier.phone} onChange={e=>setSupplier({...supplier,phone:e.target.value})}/><Input placeholder="Email" value={supplier.email} onChange={e=>setSupplier({...supplier,email:e.target.value})}/><Button onClick={addSupplier}><Plus className="mr-2 size-4"/>Add supplier</Button></div><div className="mt-4 grid gap-2 md:grid-cols-3">{(q.data??[]).map((s:any)=><div key={s.id} className="rounded-xl bg-secondary/60 p-3"><p className="font-semibold">{s.name}</p><p className="text-xs text-muted-foreground">{s.phone || s.email || "No contact saved"}</p></div>)}</div></Card><Card title="Purchase orders" hint="Draft, order and receive stock against a branch."><div className="grid gap-3 md:grid-cols-3"><Input placeholder="PO reference" value={po.reference} onChange={e=>setPo({...po,reference:e.target.value})}/><select className="h-10 rounded-md border border-input bg-background px-3 text-sm" value={po.supplier_id} onChange={e=>setPo({...po,supplier_id:e.target.value})}><option value="">No supplier</option>{(q.data??[]).map((s:any)=><option key={s.id} value={s.id}>{s.name}</option>)}</select><Button onClick={addPO}><Plus className="mr-2 size-4"/>Create PO</Button></div><div className="mt-4 space-y-2">{(orders.data??[]).map((o:any)=><div key={o.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-border p-3"><div><p className="font-semibold">{o.reference}</p><p className="text-xs text-muted-foreground">{o.status} · ₦{fmt(o.subtotal)}</p></div><div className="flex gap-2">{o.status==="draft"&&<Button size="sm" variant="outline" onClick={()=>setStatus(o.id,"ordered")}>Mark ordered</Button>}{o.status==="ordered"&&<Button size="sm" onClick={()=>setStatus(o.id,"received")}>Mark received</Button>}</div></div>)}{!orders.data?.length&&<Empty text="No purchase orders yet."/>}</div></Card></div>;
}

function Transfers({ storeId, branches }: { storeId: string; branches: any[] }) {
  const q=useQuery({queryKey:["stock-transfers",storeId],queryFn:async()=>{const {data,error}=await db.from("stock_transfers").select("*").eq("store_id",storeId).order("created_at",{ascending:false}).limit(20);if(error)throw error;return data??[]}}); const [form,setForm]=useState({from:"",to:"",reference:"",notes:""});
  async function create(){if(!form.from||!form.to||!form.reference||form.from===form.to)return;const {error}=await db.from("stock_transfers").insert({store_id:storeId,from_branch_id:form.from,to_branch_id:form.to,reference:form.reference,status:"requested",notes:form.notes||null});if(error)return alert(error.message);setForm({from:"",to:"",reference:"",notes:""});void q.refetch();}
  async function update(id:string,status:string){const patch:any={status};if(status==="approved")patch.approved_at=new Date().toISOString();if(status==="dispatched")patch.dispatched_at=new Date().toISOString();if(status==="received")patch.received_at=new Date().toISOString();const {error}=await db.from("stock_transfers").update(patch).eq("id",id).eq("store_id",storeId);if(error)return alert(error.message);void q.refetch();}
  return <Card title="Stock transfers" hint="Move inventory between branches with an auditable lifecycle."><div className="grid gap-3 md:grid-cols-4"><select className="h-10 rounded-md border border-input bg-background px-3 text-sm" value={form.from} onChange={e=>setForm({...form,from:e.target.value})}><option value="">From branch</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><select className="h-10 rounded-md border border-input bg-background px-3 text-sm" value={form.to} onChange={e=>setForm({...form,to:e.target.value})}><option value="">To branch</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><Input placeholder="Transfer reference" value={form.reference} onChange={e=>setForm({...form,reference:e.target.value})}/><Button onClick={create}><ArrowRightLeft className="mr-2 size-4"/>Request transfer</Button></div><div className="mt-5 space-y-2">{(q.data??[]).map((t:any)=><div key={t.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-border p-3"><div><p className="font-semibold">{t.reference}</p><p className="text-xs text-muted-foreground">{t.status}</p></div><div className="flex gap-2">{t.status==="requested"&&<Button size="sm" variant="outline" onClick={()=>update(t.id,"approved")}>Approve</Button>}{t.status==="approved"&&<Button size="sm" variant="outline" onClick={()=>update(t.id,"dispatched")}>Dispatch</Button>}{t.status==="dispatched"&&<Button size="sm" onClick={()=>update(t.id,"received")}>Receive</Button>}</div></div>)}{!q.data?.length&&<Empty text="No stock transfers yet."/>}</div></Card>;
}

function Discounts({ storeId }: { storeId: string }) { const q=useQuery({queryKey:["discounts",storeId],queryFn:async()=>{const {data,error}=await db.from("discount_codes").select("*").eq("store_id",storeId).order("created_at",{ascending:false});if(error)throw error;return data??[]}});const [f,setF]=useState({code:"",type:"percentage",value:"",minimum_order:"",usage_limit:"",expires_at:""});async function add(){if(!f.code||!f.value)return;const {error}=await db.from("discount_codes").insert({store_id:storeId,code:f.code.toUpperCase(),type:f.type,value:Number(f.value),minimum_order:Number(f.minimum_order||0),usage_limit:f.usage_limit?Number(f.usage_limit):null,expires_at:f.expires_at?new Date(f.expires_at).toISOString():null,is_active:true});if(error)return alert(error.message);setF({code:"",type:"percentage",value:"",minimum_order:"",usage_limit:"",expires_at:""});void q.refetch();}return <Card title="Discount codes" hint="Create controlled promotions with minimum spend and usage limits."><div className="grid gap-3 md:grid-cols-6"><Input placeholder="SAVE10" value={f.code} onChange={e=>setF({...f,code:e.target.value})}/><select className="h-10 rounded-md border border-input bg-background px-3 text-sm" value={f.type} onChange={e=>setF({...f,type:e.target.value})}><option value="percentage">%</option><option value="fixed">Fixed</option></select><Input type="number" placeholder="Value" value={f.value} onChange={e=>setF({...f,value:e.target.value})}/><Input type="number" placeholder="Min order" value={f.minimum_order} onChange={e=>setF({...f,minimum_order:e.target.value})}/><Input type="number" placeholder="Usage limit" value={f.usage_limit} onChange={e=>setF({...f,usage_limit:e.target.value})}/><Button onClick={add}><Plus className="mr-2 size-4"/>Create</Button></div><div className="mt-4 space-y-2">{(q.data??[]).map((d:any)=><div key={d.id} className="flex items-center justify-between rounded-xl bg-secondary/60 p-3"><div><p className="font-semibold">{d.code}</p><p className="text-xs text-muted-foreground">{d.type === "percentage" ? `${d.value}%` : `₦${fmt(d.value)}`} · used {d.usage_count}{d.usage_limit ? `/${d.usage_limit}` : ""}</p></div><span className="text-xs font-semibold">{d.is_active?"Active":"Inactive"}</span></div>)}{!q.data?.length&&<Empty text="No discount codes yet."/>}</div></Card> }

function Loyalty({ storeId }: { storeId: string }) { const q=useQuery({queryKey:["loyalty",storeId],queryFn:async()=>{const {data,error}=await db.from("loyalty_accounts").select("*, customers(name,phone)").eq("store_id",storeId).order("points_balance",{ascending:false}).limit(30);if(error)throw error;return data??[]}});const customers=useQuery({queryKey:["loyalty-customers",storeId],queryFn:async()=>{const {data,error}=await db.from("customers").select("id,name,phone").eq("store_id",storeId).order("name").limit(100);if(error)throw error;return data??[]}});const [f,setF]=useState({customer_id:"",points:"",reason:"Manual adjustment"});async function add(){if(!f.customer_id||!f.points)return;let account=(q.data??[]).find((a:any)=>a.customer_id===f.customer_id);if(!account){const {data,error}=await db.from("loyalty_accounts").insert({store_id:storeId,customer_id:f.customer_id,points_balance:0,lifetime_points:0}).select().single();if(error)return alert(error.message);account=data;}const points=Number(f.points);const next=Math.max(0,Number(account.points_balance)+points);const {error:e1}=await db.from("loyalty_accounts").update({points_balance:next,lifetime_points:Math.max(0,Number(account.lifetime_points)+Math.max(points,0)),updated_at:new Date().toISOString()}).eq("id",account.id);if(e1)return alert(e1.message);const {error:e2}=await db.from("loyalty_transactions").insert({store_id:storeId,loyalty_account_id:account.id,points,reason:f.reason});if(e2)return alert(e2.message);setF({customer_id:"",points:"",reason:"Manual adjustment"});void q.refetch();}return <div className="grid gap-5 lg:grid-cols-[1fr_1.4fr]"><Card title="Adjust loyalty points" hint="Reward customers or correct balances with an audit trail."><div className="space-y-3"><Field label="Customer"><select className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm" value={f.customer_id} onChange={e=>setF({...f,customer_id:e.target.value})}><option value="">Choose customer</option>{(customers.data??[]).map((c:any)=><option key={c.id} value={c.id}>{c.name}{c.phone?` · ${c.phone}`:""}</option>)}</select></Field><Field label="Points (negative removes points)"><Input type="number" value={f.points} onChange={e=>setF({...f,points:e.target.value})}/></Field><Field label="Reason"><Input value={f.reason} onChange={e=>setF({...f,reason:e.target.value})}/></Field><Button onClick={add}>Save adjustment</Button></div></Card><Card title="Customer balances" hint="Highest balances appear first."><div className="space-y-2">{(q.data??[]).map((a:any)=><div key={a.id} className="flex items-center justify-between rounded-xl border border-border p-3"><div><p className="font-semibold">{a.customers?.name ?? "Customer"}</p><p className="text-xs text-muted-foreground">Lifetime {a.lifetime_points}</p></div><span className="font-display text-lg font-bold">{a.points_balance} pts</span></div>)}{!q.data?.length&&<Empty text="No loyalty accounts yet."/>}</div></Card></div> }

function Fulfillment({ storeId }: { storeId: string }) { const orders=useQuery({queryKey:["fulfillment-orders-source",storeId],queryFn:async()=>{const {data,error}=await db.from("online_orders").select("id,order_number,customer_name,total,status,shipping_address,created_at").eq("store_id",storeId).order("created_at",{ascending:false}).limit(30);if(error)throw error;return data??[]}});const f=useQuery({queryKey:["fulfillment",storeId],queryFn:async()=>{const {data,error}=await db.from("fulfillment_orders").select("*").eq("store_id",storeId).order("created_at",{ascending:false}).limit(30);if(error)throw error;return data??[]}});async function ensure(order:any){const {error}=await db.from("fulfillment_orders").upsert({store_id:storeId,order_id:order.id,status:"processing",shipping_address:{raw:order.shipping_address??""}},{onConflict:"store_id,order_id"});if(error)return alert(error.message);void f.refetch();}async function update(id:string,status:string){const patch:any={status,updated_at:new Date().toISOString()};if(status==="delivered")patch.fulfilled_at=new Date().toISOString();const {error}=await db.from("fulfillment_orders").update(patch).eq("id",id).eq("store_id",storeId);if(error)return alert(error.message);void f.refetch();}return <div className="grid gap-5 lg:grid-cols-2"><Card title="Orders waiting for fulfilment" hint="Turn an online order into an operational fulfilment record.">{(orders.data??[]).map((o:any)=><div key={o.id} className="mb-2 flex items-center justify-between rounded-xl border border-border p-3"><div><p className="font-semibold">#{o.order_number}</p><p className="text-xs text-muted-foreground">{o.customer_name} · ₦{fmt(o.total)}</p></div><Button size="sm" onClick={()=>ensure(o)}><PackageCheck className="mr-1 size-4"/>Process</Button></div>)}{!orders.data?.length&&<Empty text="No online orders found."/>}</Card><Card title="Fulfilment queue" hint="Move orders from processing to delivery.">{(f.data??[]).map((x:any)=><div key={x.id} className="mb-2 flex items-center justify-between rounded-xl border border-border p-3"><div><p className="font-semibold">Order {x.order_id.slice(0,8)}</p><p className="text-xs text-muted-foreground">{x.status}{x.tracking_number?` · ${x.tracking_number}`:""}</p></div><div className="flex gap-2">{x.status==="processing"&&<Button size="sm" variant="outline" onClick={()=>update(x.id,"packed")}>Packed</Button>}{x.status==="packed"&&<Button size="sm" variant="outline" onClick={()=>update(x.id,"shipped")}>Shipped</Button>}{x.status==="shipped"&&<Button size="sm" onClick={()=>update(x.id,"delivered")}>Delivered</Button>}</div></div>)}{!f.data?.length&&<Empty text="No fulfilment records yet."/>}</Card></div> }

function Shipping({ storeId }: { storeId: string }) { const q=useQuery({queryKey:["shipping-rates",storeId],queryFn:async()=>{const {data,error}=await db.from("shipping_rates").select("*").eq("store_id",storeId).order("amount");if(error)throw error;return data??[]}});const [f,setF]=useState({name:"",description:"",amount:"",min:"",max:""});async function add(){if(!f.name||f.amount==="")return;const {error}=await db.from("shipping_rates").insert({store_id:storeId,name:f.name,description:f.description||null,amount:Number(f.amount),estimated_days_min:Number(f.min||1),estimated_days_max:Number(f.max||3),is_active:true});if(error)return alert(error.message);setF({name:"",description:"",amount:"",min:"",max:""});void q.refetch();}return <Card title="Shipping rates" hint="Define the delivery options customers can choose at checkout."><div className="grid gap-3 md:grid-cols-5"><Input placeholder="Standard delivery" value={f.name} onChange={e=>setF({...f,name:e.target.value})}/><Input placeholder="Description" value={f.description} onChange={e=>setF({...f,description:e.target.value})}/><Input type="number" placeholder="Amount" value={f.amount} onChange={e=>setF({...f,amount:e.target.value})}/><Input type="number" placeholder="Min days" value={f.min} onChange={e=>setF({...f,min:e.target.value})}/><Button onClick={add}><Plus className="mr-2 size-4"/>Add rate</Button></div><div className="mt-4 grid gap-2 md:grid-cols-2">{(q.data??[]).map((r:any)=><div key={r.id} className="rounded-xl border border-border p-3"><div className="flex justify-between"><p className="font-semibold">{r.name}</p><span className="font-semibold">₦{fmt(r.amount)}</span></div><p className="text-xs text-muted-foreground">{r.description || "Delivery option"} · {r.estimated_days_min}-{r.estimated_days_max} days</p></div>)}</div></Card> }

function Domains({ storeId }: { storeId: string }) { const q=useQuery({queryKey:["custom-domains",storeId],queryFn:async()=>{const {data,error}=await db.from("custom_store_domains").select("*").eq("store_id",storeId).order("created_at",{ascending:false});if(error)throw error;return data??[]}});const [domain,setDomain]=useState("");async function add(){const clean=domain.trim().toLowerCase().replace(/^https?:\\/\\//,"").replace(/\\/$/,"");if(!clean)return;const token=crypto.randomUUID().replaceAll("-","");const {error}=await db.from("custom_store_domains").insert({store_id:storeId,domain:clean,status:"pending",verification_token:token});if(error)return alert(error.message);setDomain("");void q.refetch();}async function remove(id:string){const {error}=await db.from("custom_store_domains").update({status:"removed",updated_at:new Date().toISOString()}).eq("id",id).eq("store_id",storeId);if(error)return alert(error.message);void q.refetch();}return <Card title="Custom domains" hint="Register a domain now; DNS verification/publishing remains a controlled deployment step."><div className="flex gap-3"><Input placeholder="shop.example.com" value={domain} onChange={e=>setDomain(e.target.value)}/><Button onClick={add}><Globe2 className="mr-2 size-4"/>Add domain</Button></div><div className="mt-4 space-y-2">{(q.data??[]).map((d:any)=><div key={d.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-border p-3"><div><p className="font-semibold">{d.domain}</p><p className="text-xs text-muted-foreground">Status: {d.status}</p>{d.status==="pending"&&<p className="mt-1 text-[11px] text-muted-foreground">DNS verification will be completed when domain infrastructure is enabled.</p>}</div>{d.status!=="removed"&&<Button size="sm" variant="outline" onClick={()=>remove(d.id)}>Remove</Button>}</div>)}{!q.data?.length&&<Empty text="No custom domains configured."/>}</div></Card> }

function Segments({ storeId }: { storeId: string }) { const q=useQuery({queryKey:["segments",storeId],queryFn:async()=>{const {data,error}=await db.from("customer_segment_insights").select("*").eq("store_id",storeId);if(error)throw error;return data??[]}});const counts=useMemo(()=>{const out:any={};for(const r of q.data??[])out[r.segment_name]=(out[r.segment_name]??0)+1;return out},[q.data]);return <div className="space-y-5"><Card title="Customer segments" hint="Use behaviour signals to prioritize retention and outreach."><div className="grid gap-3 md:grid-cols-4">{Object.entries(counts).map(([name,count])=><div key={name} className="rounded-xl bg-secondary/60 p-4"><p className="text-xs text-muted-foreground">{name}</p><p className="mt-1 font-display text-2xl font-bold">{String(count)}</p></div>)}{!Object.keys(counts).length&&<Empty text="No segment insights available yet."/>}</div></Card><Card title="Next action" hint="Segment membership is read-only here; use the Customers workspace for customer-level actions."><div className="flex items-center gap-3 rounded-xl border border-border p-4"><Users className="size-5 text-muted-foreground"/><div><p className="font-semibold">Turn segments into campaigns</p><p className="text-xs text-muted-foreground">Target inactive, frequent and high-value customers without changing their underlying records.</p></div></div></Card></div> }
