import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { Bluetooth, CheckCircle2, ExternalLink, HelpCircle, Keyboard, Link2Off, Printer, Radio, ScanLine, Usb, Wifi, XCircle } from "lucide-react";
import { toast } from "sonner";
import { AppShell } from "@/components/shell/AppShell";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import { connectBluetoothPrinter, connectSerialDevice, createEscPosText, isBluetoothSupported, isSecureHardwareContext, isSerialSupported, startKeyboardScanner, writeBluetoothPrinter } from "@/lib/hardware";

export const Route = createFileRoute("/_authenticated/hardware")({ ssr: false, component: HardwarePage });

function Capability({ ok, label, detail }: { ok: boolean; label: string; detail: string }) { return <div className="flex items-start gap-3 rounded-2xl border border-border bg-surface p-4"><span className={cn("mt-0.5 flex size-9 shrink-0 items-center justify-center rounded-full", ok ? "bg-accent-soft" : "bg-secondary")}>{ok ? <CheckCircle2 className="size-5" /> : <XCircle className="size-5 text-muted-foreground" />}</span><div><p className="font-semibold">{label}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{detail}</p></div></div>; }

function HardwarePage() {
  const [scannerState, setScannerState] = useState("Waiting for a scanner…");
  const [bluetoothState, setBluetoothState] = useState("Not connected");
  const [serialState, setSerialState] = useState("Not connected");
  const [printer, setPrinter] = useState<any>(null);
  const [lastScan, setLastScan] = useState("");
  useEffect(() => startKeyboardScanner(({ value }) => { setLastScan(value); setScannerState(`Detected ${value}`); toast.success(`Scanner detected ${value}`); }), []);
  async function pairPrinter() { try { const result = await connectBluetoothPrinter(); setPrinter(result); setBluetoothState(result.writable ? `Connected: ${result.device.name || "Bluetooth device"}` : `Connected: ${result.device.name || "device"} · no writable characteristic`); toast.success("Bluetooth device connected"); } catch (error) { toast.error(error instanceof Error ? error.message : "Bluetooth connection failed"); } }
  async function testPrint() { try { if (!printer?.writable) throw new Error("Connect a writable Bluetooth printer first."); await writeBluetoothPrinter(printer.writable, createEscPosText("STRAP TEST PRINT\nConnection OK\n----------------\nThank you!\n")); toast.success("Test print sent"); } catch (error) { toast.error(error instanceof Error ? error.message : "Test print failed"); } }
  async function pairSerial() { try { const port = await connectSerialDevice(); setSerialState("USB/serial device connected · 9600 baud"); const writer = port.writable?.getWriter(); if (writer) { await writer.write(createEscPosText("STRAP DEVICE TEST\nConnection OK\n")); writer.releaseLock(); } toast.success("Serial device connected"); } catch (error) { toast.error(error instanceof Error ? error.message : "Serial connection failed"); } }
  return <AppShell title="Hardware center">
    <div className="rounded-[2rem] border border-border bg-accent-soft p-6 sm:p-9"><p className="text-label-caps text-muted-foreground">Strap hardware</p><h1 className="mt-2 font-display text-3xl font-bold tracking-tight sm:text-4xl">Connect the tools behind your counter.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">Use USB or Bluetooth scanners, keyboard-wedge scanners and supported Bluetooth/serial receipt printers. Strap tests the browser connection before you use it at checkout.</p><Link to="/help" className="mt-5 inline-flex items-center gap-2 text-sm font-bold underline underline-offset-4"><HelpCircle className="size-4" />Read the hardware setup guide</Link></div>
    <div className="mt-5 grid gap-4 lg:grid-cols-3"><Capability ok={isSecureHardwareContext()} label="Secure connection" detail="Hardware APIs require a secure HTTPS page. Your deployed Strap site satisfies this requirement." /><Capability ok={isBluetoothSupported()} label="Web Bluetooth" detail="Used for compatible Bluetooth Low Energy printers and peripherals." /><Capability ok={isSerialSupported()} label="Web Serial" detail="Used for USB/serial devices and Bluetooth devices that expose a serial port." /></div>
    <div className="mt-5 grid gap-5 lg:grid-cols-2">
      <section className="surface-card p-5 sm:p-6"><div className="flex items-start gap-3"><span className="flex size-11 items-center justify-center rounded-2xl bg-accent-soft"><ScanLine className="size-5" /></span><div><h2 className="font-display text-lg font-bold">Barcode & QR scanners</h2><p className="mt-1 text-sm text-muted-foreground">PC scanners that behave like a keyboard work automatically. USB and Bluetooth HID scanners do not need a special pairing API.</p></div></div><div className="mt-5 rounded-2xl border border-dashed border-border bg-secondary/50 p-5"><p className="text-label-caps text-muted-foreground">Live scanner test</p><p className="mt-2 break-all font-mono text-lg font-bold">{lastScan || "Scan a barcode now…"}</p><p className="mt-2 text-xs text-muted-foreground">{scannerState}</p></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-secondary p-3"><Keyboard className="size-4" /><p className="mt-2 text-sm font-semibold">Keyboard wedge</p><p className="mt-1 text-xs text-muted-foreground">USB/Bluetooth scanners that type the barcode are detected automatically.</p></div><div className="rounded-xl bg-secondary p-3"><Radio className="size-4" /><p className="mt-2 text-sm font-semibold">Camera scanner</p><p className="mt-1 text-xs text-muted-foreground">Use Strap's camera scanner on supported browsers and phones.</p></div></div><Link to="/help" className="mt-4 inline-flex items-center gap-2 text-sm font-semibold">Scanner troubleshooting <ExternalLink className="size-3.5" /></Link></section>
      <section className="surface-card p-5 sm:p-6"><div className="flex items-start gap-3"><span className="flex size-11 items-center justify-center rounded-2xl bg-accent-soft"><Printer className="size-5" /></span><div><h2 className="font-display text-lg font-bold">Bluetooth receipt printer</h2><p className="mt-1 text-sm text-muted-foreground">Pair a compatible BLE printer, discover its writable GATT characteristic and send an ESC/POS test receipt.</p></div></div><div className="mt-5 rounded-2xl border border-border bg-secondary/50 p-4"><p className="text-xs font-semibold text-muted-foreground">Connection</p><p className="mt-1 font-semibold">{bluetoothState}</p></div><div className="mt-4 flex flex-wrap gap-2"><Button onClick={() => void pairPrinter()} disabled={!isBluetoothSupported()}><Bluetooth className="mr-2 size-4" />Connect Bluetooth</Button><Button variant="outline" onClick={() => void testPrint()} disabled={!printer?.writable}><Printer className="mr-2 size-4" />Test print</Button><Button variant="ghost" onClick={() => { setPrinter(null); setBluetoothState("Not connected"); }} disabled={!printer}><Link2Off className="mr-2 size-4" />Disconnect</Button></div><div className="mt-4 rounded-xl border border-accent/30 bg-accent-soft p-4 text-xs leading-5 text-muted-foreground">Important: browser Bluetooth support is for Bluetooth Low Energy GATT devices. Many older thermal printers use Bluetooth Classic/SPP and cannot be controlled directly by a normal browser. Use the Serial option below for devices exposed as a serial port.</div><div className="mt-4 border-t border-border pt-4"><p className="font-semibold">USB / serial printer or scanner</p><p className="mt-1 text-xs text-muted-foreground">Connect devices that expose a serial port at 9600 baud.</p><Button className="mt-3" variant="outline" onClick={() => void pairSerial()} disabled={!isSerialSupported()}><Usb className="mr-2 size-4" />Connect serial device</Button><p className="mt-2 text-xs text-muted-foreground">{serialState}</p></div></section>
    </div>
    <div className="mt-5 flex items-center gap-3 rounded-2xl border border-border bg-surface p-4 text-sm"><Wifi className="size-4" /><span className="flex-1">Need a step-by-step setup?</span><Link to="/help" className="font-bold underline underline-offset-4">Open Strap Help</Link></div>
  </AppShell>;
}
