import { createFileRoute, Link } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { Bluetooth, BookOpen, ChevronDown, CircleHelp, Keyboard, Printer, Search, ScanLine, ShieldCheck, Store, Usb, Zap } from "lucide-react";
import { AppShell } from "@/components/shell/AppShell";

export const Route = createFileRoute("/_authenticated/help")({ ssr: false, component: HelpPage });

const features = [
  ["Stock", ["Search by name/SKU/barcode", "Camera barcode scan", "PC keyboard-wedge scanner", "Category filter", "Low-stock filter", "Out-of-stock filter", "Shelf filter", "Sort by name", "Sort by stock", "Sort by stock value", "Stock-value KPI", "Low-stock KPI", "Out-of-stock KPI", "Bulk select visible", "Bulk stock +1", "Bulk stock -1", "Bulk archive", "CSV stock export", "Product edit", "Product delete"]],
  ["Sell", ["Product search", "Category filter", "Camera scan", "PC scanner auto-add", "Quantity controls", "Remove line", "Hold sale", "Recall held sale", "Persistent held carts", "Payment-method selector", "Cash received", "Change calculator", "Exact-cash shortcut", "Clear cart", "Mobile cart sheet", "Receipt completion preview", "Browser receipt printing", "Receipt designer shortcut", "Sale-complete sound", "Live stock guard"]],
  ["Online catalog", ["Multi-select catalog", "Bulk publish", "Bulk hide", "Bulk feature", "Bulk unfeature", "Status filter", "Category filter", "Name/price sorting", "Catalog search", "Live refresh"]],
  ["Receipt & hardware", ["Live receipt business name", "Receipt header alignment", "Bold receipt branding", "Address visibility", "Phone visibility", "Bluetooth pairing", "Bluetooth test print", "USB/serial device connection"]],
] as const;
const guides = [
  [Store, "Create and configure a store", "Start here", "Create a store, configure the profile, branch and settings, then add your first products."],
  [ScanLine, "Use a barcode scanner on a PC", "Hardware", "Most USB and Bluetooth HID scanners behave like a keyboard. Open Sell or Stock and scan; Kudi detects the rapid barcode keystrokes and processes the value. No browser Bluetooth permission is required for keyboard-wedge scanners."],
  [Bluetooth, "Connect a Bluetooth receipt printer", "Hardware", "Open Hardware Center, choose Connect Bluetooth and select a compatible BLE GATT printer. Kudi discovers writable characteristics and lets you send a test receipt. For Bluetooth Classic/SPP printers, use the Serial device connection on desktop Chrome."],
  [Usb, "Connect a USB/serial scanner or printer", "Hardware", "Open Hardware Center and choose Connect serial device. Chrome will ask you to select the port. Kudi opens it at 9600 baud and sends a small device test."],
  [Printer, "Design and print receipts", "Sales", "After a sale, choose Print for the browser print flow or Design receipt to open the fresh receipt designer tab. The designer updates its preview live."],
  [Zap, "Publish many products at once", "Online store", "Open Online catalog, search or filter the products you want, select them, then use Publish, Hide, Feature or Unfeature from the bulk toolbar."],
  [ShieldCheck, "Understand permissions", "Account", "Store owners and managers can perform management actions. Kudi keeps destructive and catalog operations behind the existing role checks."],
] as const;

function HelpPage() {
  const [query, setQuery] = useState(""); const [open, setOpen] = useState<string | null>(null);
  const featureCount = features.reduce((n, [, list]) => n + list.length, 0);
  const filteredGuides = useMemo(() => guides.filter((g) => `${g[1]} ${g[2]} ${g[3]}`.toLowerCase().includes(query.toLowerCase())), [query]);
  return <AppShell title="Help & guides">
    <div className="overflow-hidden rounded-[2rem] border border-border bg-surface shadow-lift"><div className="bg-accent-soft p-6 sm:p-10"><p className="text-label-caps text-muted-foreground">Kudi documentation</p><h1 className="mt-2 font-display text-3xl font-bold tracking-tight sm:text-4xl">Everything you need to run Kudi.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">Step-by-step procedures, hardware setup and a map of the current feature set. Search this page whenever you get stuck.</p><label className="relative mt-6 block max-w-xl"><Search className="absolute left-4 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><input className="field h-12 pl-11" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search Kudi help…" /></label></div>
      <div className="grid gap-3 p-5 sm:grid-cols-3"><div className="rounded-2xl bg-secondary p-4"><BookOpen className="size-5" /><p className="mt-3 text-2xl font-bold">{featureCount}</p><p className="text-xs text-muted-foreground">active documented features</p></div><div className="rounded-2xl bg-secondary p-4"><CircleHelp className="size-5" /><p className="mt-3 text-2xl font-bold">{guides.length}</p><p className="text-xs text-muted-foreground">workflow guides</p></div><Link to="/hardware" className="rounded-2xl bg-accent p-4 transition-transform hover:-translate-y-0.5"><Bluetooth className="size-5" /><p className="mt-3 font-bold">Hardware Center</p><p className="text-xs opacity-70">Connect scanners and printers</p></Link></div>
      <div className="border-t border-border"><div className="p-5 sm:p-6"><p className="text-label-caps text-muted-foreground">Guides</p><div className="mt-3 grid gap-px overflow-hidden rounded-2xl border border-border sm:grid-cols-2">{filteredGuides.map(([Icon,title,category,text]) => { const expanded = open === title; return <article key={title} className="bg-surface p-5"><button type="button" className="flex w-full items-start gap-3 text-left" onClick={() => setOpen(expanded ? null : title)}><span className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-accent-soft"><Icon className="size-5" /></span><span className="min-w-0 flex-1"><span className="text-label-caps text-muted-foreground">{category}</span><span className="mt-1 block font-display font-semibold">{title}</span></span><ChevronDown className={`mt-1 size-4 transition-transform ${expanded ? "rotate-180" : ""}`} /></button>{expanded && <div className="mt-4 pl-13 text-sm leading-6 text-muted-foreground">{text}</div>}</article>; })}</div></div>
      <div className="border-t border-border p-5 sm:p-6"><div className="flex items-center gap-3"><Zap className="size-5" /><div><h2 className="font-display text-lg font-bold">Current Kudi feature map</h2><p className="text-sm text-muted-foreground">These are the 57 active capabilities covered by this release.</p></div></div><div className="mt-5 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{features.map(([group,list]) => <section key={group}><h3 className="font-display font-semibold">{group}</h3><ol className="mt-2 space-y-1.5 text-sm text-muted-foreground">{list.map((item,i)=><li key={item} className="flex gap-2"><span className="w-5 shrink-0 text-xs font-bold text-foreground">{i+1}.</span><span>{item}</span></li>)}</ol></section>)}</div></div>
      <div className="border-t border-border bg-secondary/50 p-5 text-sm"><p className="font-semibold">Hardware note</p><p className="mt-1 leading-6 text-muted-foreground">Browser hardware APIs are permissioned and browser-dependent. Web Bluetooth is for BLE GATT peripherals, while Chrome desktop can use Web Serial for Bluetooth Classic RFCOMM/SPP devices and serial hardware. If a printer does not appear, check that it is paired with the operating system and that Chrome has permission.</p><Link to="/hardware" className="mt-3 inline-flex items-center gap-2 font-bold underline underline-offset-4">Open Hardware Center <Bluetooth className="size-4" /></Link></div>
    </div>
  </AppShell>;
}
