import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { AlertTriangle, BarChart3, Package, TrendingUp, Users } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { AppShell } from "@/components/shell/AppShell";
import { useStoreContext } from "@/components/shell/StoreProvider";
import { Skeleton } from "@/components/ui/skeleton";
import { formatMoney } from "@/lib/currency";

export const Route = createFileRoute("/_authenticated/insights")({ component: InsightsPage });

function InsightsPage() {
  const { store, branch } = useStoreContext();
  const storeId = store?.id;
  const currency = store?.currency ?? "NGN";
  const query = useQuery({ queryKey: ["business-insights", storeId, branch?.id], enabled: Boolean(storeId), queryFn: async () => { const [sales, stock, customers] = await Promise.all([supabase.from("sales").select("id,total,created_at").eq("store_id", storeId as string).order("created_at", { ascending: false }).limit(500), supabase.from("branch_stock").select("quantity,products!inner(name,low_stock_threshold)").eq("store_id", storeId as string).eq("branch_id", branch?.id ?? ""), supabase.from("customers").select("id,created_at").eq("store_id", storeId as string)]); if (sales.error) throw new Error(sales.error.message); if (stock.error) throw new Error(stock.error.message); if (customers.error) throw new Error(customers.error.message); return { sales: sales.data ?? [], stock: stock.data ?? [], customers: customers.data ?? [] }; } });
  const data = query.data;
  const revenue = data?.sales.reduce((sum, sale) => sum + Number(sale.total), 0) ?? 0;
  const low = data?.stock.filter((row: any) => row.quantity <= row.products.low_stock_threshold).length ?? 0;
  const activeCustomers = data?.customers.length ?? 0;
  const avg = data?.sales.length ? revenue / data.sales.length : 0;
  return <AppShell title="Business insights"><div className="space-y-6"><section className="relative overflow-hidden rounded-[2rem] border border-border bg-foreground px-6 py-7 text-background sm:px-8"><div className="pointer-events-none absolute -right-24 -top-24 size-72 rounded-full bg-accent/20 blur-3xl" /><div className="relative"><p className="text-label-caps text-background/50">Decision workspace</p><h2 className="mt-2 font-display text-3xl font-bold tracking-tight">Know what deserves your attention.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-background/60">Kudi turns your sales, customers and inventory into simple signals you can act on.</p></div></section><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{query.isLoading ? [1,2,3,4].map((i) => <div key={i} className="surface-card p-5"><Skeleton className="h-8 w-24" /><Skeleton className="mt-4 h-8 w-32" /></div>) : <><Metric icon={<TrendingUp className="size-4" />} label="Tracked revenue" value={formatMoney(revenue, currency)} hint={`${data?.sales.length ?? 0} recent sales`} /><Metric icon={<BarChart3 className="size-4" />} label="Average sale" value={formatMoney(avg, currency)} hint="Across tracked sales" /><Metric icon={<Package className="size-4" />} label="Stock alerts" value={String(low)} hint={low ? "Needs attention" : "Looks healthy"} warning={Boolean(low)} /><Metric icon={<Users className="size-4" />} label="Customers" value={String(activeCustomers)} hint="Customer relationships" /></>}</div><div className="grid gap-5 lg:grid-cols-2"><section className="surface-card p-6"><div className="flex items-center gap-3"><span className="flex size-10 items-center justify-center rounded-xl bg-accent-soft"><AlertTriangle className="size-5" /></span><div><p className="text-label-caps text-muted-foreground">Attention</p><h3 className="font-display text-lg font-semibold">What needs action</h3></div></div><div className="mt-5 space-y-3">{low ? <div className="rounded-xl border border-accent/20 bg-accent-soft p-4 text-sm"><strong>{low} inventory item{low === 1 ? "" : "s"}</strong> are at or below their threshold.</div> : <div className="rounded-xl border border-border bg-secondary/40 p-4 text-sm text-muted-foreground">No urgent inventory signal right now.</div>}</div></section><section className="surface-card p-6"><div className="flex items-center gap-3"><span className="flex size-10 items-center justify-center rounded-xl bg-secondary"><TrendingUp className="size-5" /></span><div><p className="text-label-caps text-muted-foreground">Growth signal</p><h3 className="font-display text-lg font-semibold">Sales momentum</h3></div></div><p className="mt-5 text-sm leading-6 text-muted-foreground">Use the reports workspace for deeper time-based comparisons. This page is intentionally focused on fast operational signals.</p></section></div></div></AppShell>;
}
function Metric({ icon, label, value, hint, warning = false }: { icon: React.ReactNode; label: string; value: string; hint: string; warning?: boolean }) { return <div className={`surface-card p-5 ${warning ? "border-accent/30" : ""}`}><p className="text-label-caps flex items-center gap-1.5 text-muted-foreground">{icon}{label}</p><p className={`numeric mt-3 text-2xl font-bold ${warning ? "text-accent-ink" : ""}`}>{value}</p><p className="mt-1 text-xs text-muted-foreground">{hint}</p></div>; }
