import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { AlignCenter, AlignLeft, Bluetooth, Bold, Printer, Save, Share2, Type, Wifi } from "lucide-react";
import { useStoreContext } from "@/components/shell/StoreProvider";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";

export const Route = createFileRoute("/_authenticated/receipt-designer")({ ssr: false, component: ReceiptDesignerPage });
type Settings = { name: string; showAddress: boolean; showPhone: boolean; align: "left" | "center"; bold: boolean };
const KEY = "kudi-receipt-settings:";

function ReceiptDesignerPage() {
  const { store } = useStoreContext();
  const storeId = store?.id ?? "preview";
  const defaults = useMemo<Settings>(() => ({ name: store?.name ?? "KUDI STORE", showAddress: true, showPhone: true, align: "center", bold: true }), [store?.name]);
  const [settings, setSettings] = useState<Settings>(defaults);
  const [saved, setSaved] = useState(false);
  useEffect(() => { try { const raw = localStorage.getItem(`${KEY}${storeId}`); if (raw) setSettings({ ...defaults, ...(JSON.parse(raw) as Partial<Settings>) }); } catch {} }, [defaults, storeId]);
  const update = <K extends keyof Settings>(key: K, value: Settings[K]) => { setSettings((s) => ({ ...s, [key]: value })); setSaved(false); };
  const save = () => { try { localStorage.setItem(`${KEY}${storeId}`, JSON.stringify(settings)); setSaved(true); toast.success("Receipt design saved on this device."); } catch { toast.error("Could not save the receipt design."); } };
  const share = async () => { try { const text = `${settings.name}\nReceipt preview for your Kudi store.`; if (navigator.share) await navigator.share({ title: `${settings.name} receipt`, text }); else await navigator.clipboard.writeText(text); toast.success(navigator.share ? "Receipt preview ready to share." : "Receipt preview copied."); } catch {} };
  return <main className="min-h-screen bg-background p-4 sm:p-8 print:bg-white print:p-0"><div className="mx-auto max-w-6xl">
    <header className="flex flex-wrap items-center justify-between gap-4 border-b border-border pb-5 print:hidden"><div><p className="text-label-caps text-muted-foreground">Kudi · Receipt printing</p><h1 className="mt-1 font-display text-2xl font-bold">Receipt designer</h1><p className="mt-1 text-sm text-muted-foreground">Design, save, print and share a customer-ready receipt.</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => void share()}><Share2 className="mr-2 size-4" />Share</Button><Button variant="outline" onClick={() => window.print()}><Printer className="mr-2 size-4" />Print</Button><Button onClick={save}><Save className="mr-2 size-4" />{saved ? "Saved" : "Save design"}</Button></div></header>
    <div className="mt-6 grid gap-6 lg:grid-cols-[1fr_380px]">
      <section className="rounded-3xl border border-border bg-surface p-5 shadow-lift print:border-0 print:p-0 print:shadow-none"><div className="flex items-center justify-between print:hidden"><div><h2 className="font-display font-semibold">Preview</h2><p className="text-xs text-muted-foreground">The layout is optimized for standard receipt printing.</p></div><Printer className="size-5 text-muted-foreground" /></div><div className="mt-6 flex min-h-[650px] items-start justify-center rounded-2xl bg-secondary/70 p-5 sm:p-10 print:mt-0 print:min-h-0 print:bg-white print:p-0"><article className={`w-[300px] bg-white px-6 py-7 text-black shadow-xl print:w-[80mm] print:shadow-none ${settings.align === "center" ? "text-center" : "text-left"}`}><h3 className={`text-xl ${settings.bold ? "font-black" : "font-medium"}`}>{settings.name || "YOUR STORE"}</h3>{settings.showAddress && <p className="mt-1 text-[10px]">Store address</p>}{settings.showPhone && <p className="text-[10px]">Store phone</p>}<div className="my-5 border-t border-dashed border-black/40" /><div className="space-y-2 text-left text-[11px]"><div className="flex justify-between"><span>Product A × 2</span><span>₦8,000</span></div><div className="flex justify-between"><span>Product B × 1</span><span>₦4,500</span></div></div><div className="my-4 border-t border-dashed border-black/40" /><div className="flex justify-between text-sm font-bold"><span>Total</span><span>₦12,500</span></div><p className="mt-7 text-[10px]">Thank you for shopping with us.</p></article></div></section>
      <aside className="rounded-3xl border border-border bg-surface p-5 shadow-lift print:hidden"><h2 className="font-display font-semibold">Receipt settings</h2><div className="mt-5 space-y-5"><label className="block space-y-2"><span className="text-sm font-semibold">Business name</span><input className="field" value={settings.name} onChange={(e) => update("name", e.target.value)} maxLength={80} /></label><div><span className="text-sm font-semibold">Header alignment</span><div className="mt-2 flex gap-2"><button onClick={() => update("align", "left")} className={`flex min-h-11 flex-1 items-center justify-center gap-2 rounded-xl border p-3 ${settings.align === "left" ? "border-foreground bg-secondary" : "border-border"}`}><AlignLeft className="size-4" />Left</button><button onClick={() => update("align", "center")} className={`flex min-h-11 flex-1 items-center justify-center gap-2 rounded-xl border p-3 ${settings.align === "center" ? "border-foreground bg-secondary" : "border-border"}`}><AlignCenter className="size-4" />Center</button></div></div><div className="space-y-2"><Toggle label="Bold business name" icon={<Bold className="size-4" />} value={settings.bold} onChange={(v) => update("bold", v)} /><Toggle label="Show address" icon={<Type className="size-4" />} value={settings.showAddress} onChange={(v) => update("showAddress", v)} /><Toggle label="Show phone" icon={<Wifi className="size-4" />} value={settings.showPhone} onChange={(v) => update("showPhone", v)} /></div><div className="rounded-2xl border border-dashed border-border bg-secondary/60 p-4"><p className="flex items-center gap-2 text-sm font-semibold"><Bluetooth className="size-4" /> Printer compatibility</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Browser print works now. Direct Bluetooth pairing remains hardware-dependent.</p></div></div></aside>
    </div></div></main>;
}
function Toggle({ label, icon, value, onChange }: { label: string; icon: React.ReactNode; value: boolean; onChange: (v: boolean) => void }) { return <button type="button" onClick={() => onChange(!value)} className="flex min-h-11 w-full items-center gap-3 rounded-xl border border-border p-3 text-left"><span className="flex size-8 items-center justify-center rounded-lg bg-accent-soft">{icon}</span><span className="flex-1 text-sm font-medium">{label}</span><span className={`h-5 w-9 rounded-full p-0.5 ${value ? "bg-foreground" : "bg-border"}`}><span className={`block size-4 rounded-full bg-background transition-transform ${value ? "translate-x-4" : ""}`} /></span></button>; }
