import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { AlignCenter, AlignLeft, Bluetooth, Bold, Printer, Save, Type, Wifi } from "lucide-react";
import { useStoreContext } from "@/components/shell/StoreProvider";

export const Route = createFileRoute("/_authenticated/receipt-designer")({ ssr: false, component: ReceiptDesignerPage });

function ReceiptDesignerPage() {
  const { store } = useStoreContext();
  const [name, setName] = useState(store?.name ?? "KUDI STORE");
  const [showAddress, setShowAddress] = useState(true);
  const [showPhone, setShowPhone] = useState(true);
  const [align, setAlign] = useState<"left" | "center">("center");
  const [bold, setBold] = useState(true);
  const [saved, setSaved] = useState(false);
  return <main className="min-h-screen bg-background p-4 sm:p-8"><div className="mx-auto max-w-6xl"><header className="flex flex-wrap items-center justify-between gap-4 border-b border-border pb-5"><div><p className="text-label-caps text-muted-foreground">Kudi Labs · Receipt printing</p><h1 className="mt-1 font-display text-2xl font-bold">Receipt designer</h1><p className="mt-1 text-sm text-muted-foreground">Design now. Bluetooth printing is coming soon.</p></div><div className="flex gap-2"><span className="inline-flex items-center gap-2 rounded-full bg-accent-soft px-3 py-2 text-xs font-semibold"><Bluetooth className="size-4" /> Bluetooth soon</span><button onClick={() => { setSaved(true); setTimeout(() => setSaved(false), 1800); }} className="inline-flex items-center gap-2 rounded-xl bg-foreground px-4 py-2 text-sm font-semibold text-background"><Save className="size-4" /> {saved ? "Saved" : "Save design"}</button></div></header>
      <div className="mt-6 grid gap-6 lg:grid-cols-[1fr_380px]">
        <section className="rounded-3xl border border-border bg-surface p-5 shadow-lift sm:p-7"><div className="flex items-center justify-between"><div><h2 className="font-display font-semibold">Canvas</h2><p className="text-xs text-muted-foreground">Your receipt updates live.</p></div><Printer className="size-5 text-muted-foreground" /></div><div className="mt-6 flex min-h-[650px] items-start justify-center rounded-2xl bg-secondary/70 p-5 sm:p-10"><article className={`w-[300px] bg-white px-6 py-7 text-black shadow-xl ${align === "center" ? "text-center" : "text-left"}`}><h3 className={`text-xl ${bold ? "font-black" : "font-medium"}`}>{name || "YOUR STORE"}</h3>{showAddress && <p className="mt-1 text-[10px]">12 Market Street · Lagos</p>}{showPhone && <p className="text-[10px]">0800 000 0000</p>}<div className="my-5 border-t border-dashed border-black/40" /><div className="space-y-2 text-left text-[11px]"><div className="flex justify-between"><span>Product A × 2</span><span>₦8,000</span></div><div className="flex justify-between"><span>Product B × 1</span><span>₦4,500</span></div></div><div className="my-4 border-t border-dashed border-black/40" /><div className="flex justify-between text-sm font-bold"><span>Total</span><span>₦12,500</span></div><p className="mt-7 text-[10px]">Thank you for shopping with us.</p></article></div></section>
        <aside className="rounded-3xl border border-border bg-surface p-5 shadow-lift"><h2 className="font-display font-semibold">Receipt settings</h2><div className="mt-5 space-y-5"><label className="block space-y-2"><span className="text-sm font-semibold">Business name</span><input className="field" value={name} onChange={(e) => setName(e.target.value)} /></label><div><span className="text-sm font-semibold">Header alignment</span><div className="mt-2 flex gap-2"><button onClick={() => setAlign("left")} className={`flex flex-1 items-center justify-center gap-2 rounded-xl border p-3 ${align === "left" ? "border-foreground bg-secondary" : "border-border"}`}><AlignLeft className="size-4" />Left</button><button onClick={() => setAlign("center")} className={`flex flex-1 items-center justify-center gap-2 rounded-xl border p-3 ${align === "center" ? "border-foreground bg-secondary" : "border-border"}`}><AlignCenter className="size-4" />Center</button></div></div><div className="space-y-2"><Toggle label="Bold business name" icon={<Bold className="size-4" />} value={bold} onChange={setBold} /><Toggle label="Show address" icon={<Type className="size-4" />} value={showAddress} onChange={setShowAddress} /><Toggle label="Show phone" icon={<Wifi className="size-4" />} value={showPhone} onChange={setShowPhone} /></div><div className="rounded-2xl border border-dashed border-border bg-secondary/60 p-4"><p className="flex items-center gap-2 text-sm font-semibold"><Bluetooth className="size-4" /> Bluetooth printers</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Printer pairing and direct printing will be enabled here in the upcoming release. Your design is ready for it.</p></div></div></aside>
      </div></div></main>;
}
function Toggle({ label, icon, value, onChange }: { label: string; icon: React.ReactNode; value: boolean; onChange: (v: boolean) => void }) { return <button type="button" onClick={() => onChange(!value)} className="flex w-full items-center gap-3 rounded-xl border border-border p-3 text-left"><span className="flex size-8 items-center justify-center rounded-lg bg-accent-soft">{icon}</span><span className="flex-1 text-sm font-medium">{label}</span><span className={`h-5 w-9 rounded-full p-0.5 ${value ? "bg-foreground" : "bg-border"}`}><span className={`block size-4 rounded-full bg-background transition-transform ${value ? "translate-x-4" : ""}`} /></span></button>; }
