import { createFileRoute } from "@tanstack/react-router";
import { ArrowRight, Bell, ChevronRight, CreditCard, Database, Globe2, KeyRound, Monitor, Palette, Receipt, Shield, Settings2, Store, Users, Zap } from "lucide-react";
import { useEffect, useState } from "react";
import { Link } from "@tanstack/react-router";
import { toast } from "sonner";
import { AppShell } from "@/components/shell/AppShell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { onlineSupabase } from "@/integrations/supabase/online-client";
import { useStoreContext } from "@/components/shell/StoreProvider";

export const Route = createFileRoute("/_authenticated/settings")({ component: SettingsPage });
const SETTINGS = [
  [Store, "Store profile", "Business name, address, contact details and public store identity."], [Palette, "Store appearance", "Branding, theme, colors, typography and storefront presentation."], [Users, "Staff & permissions", "Roles, access boundaries, staff management and account controls."], [Bell, "Notifications", "Order, inventory, customer and operational notification preferences."], [Receipt, "Receipts", "Receipt layout, business details, footer text and printing preferences."], [Globe2, "Online store", "Catalogue visibility, storefront behaviour and customer-facing options."], [Zap, "Checkout & sales", "POS behaviour, cart defaults, tax display and checkout preferences."], [Database, "Inventory", "Stock alerts, valuation preferences and inventory behaviour."], [Shield, "Security", "Password, active sessions and account security."], [CreditCard, "Payments", "Payment configuration is not enabled yet."],
] as const;

function SettingsPage(){
 const {store}=useStoreContext(); const [email,setEmail]=useState(""); const [current,setCurrent]=useState(""); const [next,setNext]=useState(""); const [confirm,setConfirm]=useState(""); const [saving,setSaving]=useState(false); const [sessionActive,setSessionActive]=useState(false);
 useEffect(()=>{void onlineSupabase.auth.getUser().then(({data})=>setEmail(data.user?.email??""));void onlineSupabase.auth.getSession().then(({data})=>setSessionActive(Boolean(data.session)));},[]);
 async function changePassword(){if(next.length<8)return toast.error("Use at least 8 characters for your new password.");if(next!==confirm)return toast.error("The new passwords do not match.");setSaving(true);if(email&&current){const {error}=await onlineSupabase.auth.signInWithPassword({email,password:current});if(error){setSaving(false);return toast.error("Current password is incorrect.");}}const {error}=await onlineSupabase.auth.updateUser({password:next});setSaving(false);if(error)return toast.error(error.message);setCurrent("");setNext("");setConfirm("");toast.success("Password changed successfully.");}
 async function signOutOthers(){const {error}=await onlineSupabase.auth.signOut({scope:"others"});if(error)toast.error(error.message);else toast.success("Other active sessions have been signed out.");}
 return <AppShell title="Settings"><main className="mx-auto max-w-6xl space-y-8"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-label-caps text-accent-ink">Control centre</p><h2 className="mt-2 font-display text-3xl font-bold tracking-tight sm:text-4xl">Settings</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">Everything that controls your Strap account and store, organised in one full workspace.</p></div><Link to="/advanced-settings" className="inline-flex items-center justify-center gap-2 rounded-xl bg-foreground px-4 py-3 text-sm font-semibold text-background"><Settings2 className="size-4"/>Advanced settings<ArrowRight className="size-4"/></Link></div>
 <section className="rounded-2xl border border-border bg-surface p-6 shadow-sm"><div className="flex items-center gap-3"><span className="flex size-10 items-center justify-center rounded-xl bg-accent-soft"><Store className="size-5"/></span><div><h3 className="font-semibold">{store?.name??"Your store"}</h3><p className="text-sm text-muted-foreground">Store-wide configuration and account controls</p></div></div><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{SETTINGS.map(([Icon,title,body])=><Link key={title} to="/advanced-settings" className="group rounded-2xl border border-border bg-background p-5 hover:-translate-y-0.5 hover:border-accent/40"><div className="flex items-start justify-between"><span className="flex size-10 items-center justify-center rounded-xl bg-accent-soft text-accent-ink"><Icon className="size-5"/></span><ChevronRight className="size-4 text-muted-foreground transition group-hover:translate-x-1"/></div><h4 className="mt-4 font-semibold">{title}</h4><p className="mt-2 text-sm leading-6 text-muted-foreground">{body}</p></Link>)}</div></section>
 <section className="rounded-2xl border border-border bg-surface p-6 shadow-sm"><div className="flex items-start gap-3"><span className="flex size-10 items-center justify-center rounded-xl bg-accent-soft"><KeyRound className="size-5"/></span><div><h3 className="font-semibold">Account & password</h3><p className="mt-1 text-sm text-muted-foreground">Signed in as {email||"your account"}. Change your password without leaving Settings.</p></div></div><div className="mt-6 grid gap-4 md:grid-cols-3"><Input type="password" placeholder="Current password" value={current} onChange={e=>setCurrent(e.target.value)}/><Input type="password" placeholder="New password" value={next} onChange={e=>setNext(e.target.value)}/><Input type="password" placeholder="Confirm new password" value={confirm} onChange={e=>setConfirm(e.target.value)}/></div><Button className="mt-4" onClick={()=>void changePassword()} disabled={saving}>{saving?"Updating…":"Change password"}</Button></section>
 <section className="rounded-2xl border border-border bg-surface p-6 shadow-sm"><div className="flex items-start justify-between gap-4"><div className="flex items-start gap-3"><span className="flex size-10 items-center justify-center rounded-xl bg-accent-soft"><Monitor className="size-5"/></span><div><h3 className="font-semibold">Active computers & sessions</h3><p className="mt-1 text-sm text-muted-foreground">This browser session is {sessionActive?"active":"not available"}. Revoke other signed-in sessions whenever you need to.</p></div></div><span className="text-xs font-semibold text-emerald-700">Active</span></div><Button variant="outline" className="mt-5" onClick={()=>void signOutOthers()}>Sign out other computers</Button><p className="mt-3 text-xs text-muted-foreground">Session tokens are managed securely by Supabase. Detailed device history requires dedicated audit-session storage and will be added without exposing passwords or tokens.</p></section>
 </main></AppShell>;
}
