import { createFileRoute } from "@tanstack/react-router";
import { ChevronDown, ChevronUp, Eye, GripVertical, Image as ImageIcon, LayoutTemplate, Monitor, Palette, Plus, Redo2, Save, Smartphone, Tablet, Trash2, Undo2, Type, Settings2, Sparkles, Layers3 } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";
import { onlineSupabase } from "@/integrations/supabase/online-client";
import { useStoreContext } from "@/components/shell/StoreProvider";
import { AppShell } from "@/components/shell/AppShell";
import { Button } from "@/components/ui/button";

export const Route = createFileRoute("/_authenticated/store-editor")({ component: StoreEditor });

type Section = { id: string; type: string; title: string; text: string; visible: boolean; background: string; textColor: string; image?: string; button?: string };
type Device = "desktop" | "tablet" | "mobile";

const LIBRARY: Array<Pick<Section, "type" | "title" | "text" | "background" | "textColor"> & { label: string }> = [
 { type:"announcement", label:"Announcement", title:"Free shipping on orders over $100", text:"Add a short store-wide message.", background:"#111111", textColor:"#ffffff" },
 { type:"hero", label:"Hero", title:"Your next favorite thing", text:"Tell visitors what makes your business worth discovering.", background:"#f4f1ea", textColor:"#111111" },
 { type:"featured", label:"Featured products", title:"Featured products", text:"Show your best products first.", background:"#ffffff", textColor:"#111111" },
 { type:"grid", label:"Product grid", title:"Shop the collection", text:"A flexible product showcase.", background:"#ffffff", textColor:"#111111" },
 { type:"categories", label:"Categories", title:"Shop by category", text:"Help customers find what they need faster.", background:"#f7f7f5", textColor:"#111111" },
 { type:"banner", label:"Promo banner", title:"A reason to come back", text:"Highlight a promotion, launch or seasonal drop.", background:"#111111", textColor:"#ffffff" },
 { type:"gallery", label:"Gallery", title:"Made for your world", text:"Tell your story visually.", background:"#f4f1ea", textColor:"#111111" },
 { type:"about", label:"About", title:"Built by people who care", text:"Introduce the people and story behind your business.", background:"#ffffff", textColor:"#111111" },
 { type:"testimonials", label:"Testimonials", title:"Loved by customers", text:"Add social proof that builds confidence.", background:"#f7f7f5", textColor:"#111111" },
 { type:"newsletter", label:"Newsletter", title:"Stay in the loop", text:"Invite visitors to hear about launches and offers.", background:"#111111", textColor:"#ffffff" },
 { type:"faq", label:"FAQ", title:"Questions, answered", text:"Reduce friction before checkout.", background:"#ffffff", textColor:"#111111" },
 { type:"contact", label:"Contact", title:"We are here to help", text:"Give customers a clear way to reach you.", background:"#f7f7f5", textColor:"#111111" },
 { type:"custom", label:"Custom section", title:"Make it yours", text:"Start from a blank section and shape it your way.", background:"#ffffff", textColor:"#111111" },
];

const starter: Section[] = [
 { id:"hero-1", type:"hero", title:"Your store. Your world.", text:"Create a storefront that feels unmistakably yours.", visible:true, background:"#f4f1ea", textColor:"#111111", button:"Shop now" },
 { id:"featured-1", type:"featured", title:"Featured products", text:"Put your best products in the spotlight.", visible:true, background:"#ffffff", textColor:"#111111" },
 { id:"about-1", type:"about", title:"Built by people who care", text:"Share your story and give customers a reason to believe in your brand.", visible:true, background:"#f7f7f5", textColor:"#111111" },
];

function uid() { return `${Date.now()}-${Math.random().toString(36).slice(2,8)}`; }

function StoreEditor() {
 const { store, role } = useStoreContext();
 const canEdit = role === "owner" || role === "manager";
 const [sections, setSections] = useState<Section[]>(starter);
 const [selected, setSelected] = useState<string>(starter[0].id);
 const [device, setDevice] = useState<Device>("desktop");
 const [saving, setSaving] = useState(false);
 const [showLibrary, setShowLibrary] = useState(false);
 const [history, setHistory] = useState<Section[][]>([]);
 const [future, setFuture] = useState<Section[][]>([]);
 const current = sections.find(s => s.id === selected) ?? sections[0];
 const width = device === "mobile" ? "max-w-[390px]" : device === "tablet" ? "max-w-[760px]" : "max-w-[1120px]";

 useEffect(() => { if (!store) return; (async()=>{ const {data}=await onlineSupabase.from("storefront_editor_layouts").select("draft,published").eq("store_id",store.id).maybeSingle(); const draft=(data?.draft as {sections?:Section[]}|null)?.sections; if (draft?.length) { setSections(draft); setSelected(draft[0].id); } })(); }, [store]);

 function commit(next: Section[]) { setHistory(h=>[...h.slice(-29), sections]); setFuture([]); setSections(next); }
 function update(patch: Partial<Section>) { if(!current)return; commit(sections.map(s=>s.id===current.id?{...s,...patch}:s)); }
 function add(template: typeof LIBRARY[number]) { const s:Section={...template,id:uid(),visible:true}; commit([...sections,s]); setSelected(s.id); setShowLibrary(false); }
 function remove(){ if(!current)return; const next=sections.filter(s=>s.id!==current.id); commit(next); setSelected(next[0]?.id??""); }
 function move(delta:number){ if(!current)return; const i=sections.findIndex(s=>s.id===current.id); const j=i+delta; if(j<0||j>=sections.length)return; const next=[...sections]; [next[i],next[j]]=[next[j],next[i]]; commit(next); }
 function undo(){const previous=history.at(-1);if(!previous)return;setFuture(f=>[sections,...f]);setHistory(h=>h.slice(0,-1));setSections(previous);setSelected(previous[0]?.id??"");}
 function redo(){const next=future[0];if(!next)return;setHistory(h=>[...h,sections]);setFuture(f=>f.slice(1));setSections(next);setSelected(next[0]?.id??"");}
 async function save(publish=false){ if(!store||!canEdit)return; setSaving(true); const payload={sections}; const {error}=await onlineSupabase.from("storefront_editor_layouts").upsert({store_id:store.id,draft:payload, ...(publish?{published:payload,published_at:new Date().toISOString()}:{}),updated_at:new Date().toISOString()},{onConflict:"store_id"}); if(error) toast.error(error.message); else toast.success(publish?"Storefront published":"Draft saved"); setSaving(false); }
 if(!canEdit)return <AppShell title="Store Editor"><div className="p-8"><h1 className="text-2xl font-bold">Owner or manager access required</h1></div></AppShell>;
 return <AppShell title="Store Editor"><div className="-mx-4 -my-6 flex min-h-[calc(100vh-5rem)] flex-col overflow-hidden border-y border-border bg-muted/20 md:-mx-6 md:flex-row">
   <aside className="w-full shrink-0 border-b border-border bg-background md:w-64 md:border-b-0 md:border-r"><div className="flex items-center justify-between border-b border-border p-4"><div><p className="text-[10px] font-bold uppercase tracking-widest text-muted-foreground">Design</p><h2 className="font-semibold">Store editor</h2></div><Button size="icon" variant="ghost" onClick={()=>setShowLibrary(v=>!v)}><Plus className="size-4"/></Button></div><div className="max-h-64 space-y-1 overflow-auto p-3 md:max-h-[calc(100vh-9rem)]">{sections.map((s,i)=><button key={s.id} onClick={()=>setSelected(s.id)} className={`group flex w-full items-center gap-2 rounded-xl border p-2 text-left transition ${selected===s.id?"border-foreground bg-muted":"border-transparent hover:bg-muted/70"}`}><GripVertical className="size-4 text-muted-foreground"/><span className="min-w-0 flex-1"><span className="block truncate text-xs font-semibold">{s.title}</span><span className="block text-[10px] capitalize text-muted-foreground">{s.type}</span></span><span className="text-[10px] text-muted-foreground">{i+1}</span></button>)}<button onClick={()=>setShowLibrary(true)} className="mt-2 flex w-full items-center justify-center gap-2 rounded-xl border border-dashed border-border p-3 text-xs font-semibold hover:bg-muted"><Plus className="size-4"/> Add section</button></div></aside>
   <main className="min-w-0 flex-1 overflow-auto"><header className="sticky top-0 z-20 flex flex-wrap items-center justify-between gap-3 border-b border-border bg-background/95 px-4 py-3 backdrop-blur"><div className="flex items-center gap-1"><Button size="icon" variant="ghost" disabled={!history.length} onClick={undo}><Undo2 className="size-4"/></Button><Button size="icon" variant="ghost" disabled={!future.length} onClick={redo}><Redo2 className="size-4"/></Button><span className="mx-2 hidden h-5 w-px bg-border sm:block"/><div className="flex rounded-lg border border-border p-1"><Button size="icon" variant={device==="desktop"?"secondary":"ghost"} onClick={()=>setDevice("desktop")}><Monitor className="size-4"/></Button><Button size="icon" variant={device==="tablet"?"secondary":"ghost"} onClick={()=>setDevice("tablet")}><Tablet className="size-4"/></Button><Button size="icon" variant={device==="mobile"?"secondary":"ghost"} onClick={()=>setDevice("mobile")}><Smartphone className="size-4"/></Button></div></div><div className="flex items-center gap-2"><Button variant="outline" onClick={()=>toast.message("Preview uses the current draft.")}><Eye className="mr-2 size-4"/>Preview</Button><Button variant="outline" disabled={saving} onClick={()=>void save(false)}><Save className="mr-2 size-4"/>Save draft</Button><Button disabled={saving} onClick={()=>void save(true)}>{saving?"Saving…":"Publish"}</Button></div></header>
   <div className="flex min-h-[calc(100vh-9rem)] justify-center p-4 md:p-8"><div className={`w-full ${width} overflow-hidden rounded-2xl border border-border bg-white shadow-2xl transition-all`}><div className="border-b bg-background px-6 py-3 text-xs font-semibold text-muted-foreground">{store?.name ?? "Your store"}<span className="ml-2 rounded-full bg-muted px-2 py-1 text-[9px] uppercase tracking-wider">Draft</span></div>{sections.filter(s=>s.visible).map(s=><section key={s.id} onClick={()=>setSelected(s.id)} className={`relative min-h-36 cursor-pointer border-b-2 border-transparent px-6 py-12 transition hover:border-dashed hover:border-foreground/30 ${selected===s.id?"ring-2 ring-inset ring-foreground":""}`} style={{background:s.background,color:s.textColor}}><div className="mx-auto max-w-3xl"><p className="mb-2 text-[10px] font-bold uppercase tracking-[.18em] opacity-60">{s.type}</p><h3 className="text-3xl font-bold tracking-tight">{s.title}</h3><p className="mt-3 max-w-2xl text-sm leading-6 opacity-75">{s.text}</p>{s.button&&<button className="mt-5 rounded-full bg-black px-5 py-2 text-sm font-semibold text-white">{s.button}</button>}<div className="mt-8 grid grid-cols-2 gap-3 md:grid-cols-4">{[1,2,3,4].slice(0,s.type==="hero"?3:4).map(n=><div key={n} className="aspect-[4/3] rounded-xl border border-current/10 bg-black/5" />)}</div></div></section>)}</div></div></main>
   <aside className="hidden w-80 shrink-0 border-l border-border bg-background lg:block"><div className="border-b border-border p-4"><div className="flex items-center gap-2"><Settings2 className="size-4"/><span className="font-semibold">Design controls</span></div><p className="mt-1 text-xs text-muted-foreground">Edit the selected section without leaving the canvas.</p></div>{current?<div className="space-y-5 p-4"><div><label className="mb-1 block text-xs font-semibold">Section name</label><input value={current.title} onChange={e=>update({title:e.target.value})} className="w-full rounded-lg border border-border bg-background px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-foreground/20"/></div><div><label className="mb-1 block text-xs font-semibold">Text</label><textarea value={current.text} onChange={e=>update({text:e.target.value})} rows={4} className="w-full resize-none rounded-lg border border-border bg-background px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-foreground/20"/></div><div><label className="mb-1 block text-xs font-semibold">CTA label</label><input value={current.button??""} onChange={e=>update({button:e.target.value||undefined})} placeholder="Optional" className="w-full rounded-lg border border-border bg-background px-3 py-2 text-sm"/></div><div className="grid grid-cols-2 gap-3"><label className="text-xs font-semibold">Background<input type="color" value={current.background} onChange={e=>update({background:e.target.value})} className="mt-2 h-10 w-full cursor-pointer rounded-lg border"/></label><label className="text-xs font-semibold">Text<input type="color" value={current.textColor} onChange={e=>update({textColor:e.target.value})} className="mt-2 h-10 w-full cursor-pointer rounded-lg border"/></label></div><div className="grid grid-cols-2 gap-2"><Button variant="outline" onClick={()=>move(-1)}><ChevronUp className="mr-2 size-4"/>Move up</Button><Button variant="outline" onClick={()=>move(1)}><ChevronDown className="mr-2 size-4"/>Move down</Button></div><Button variant="outline" className="w-full" onClick={()=>update({visible:!current.visible})}>{current.visible?"Hide section":"Show section"}</Button><Button variant="destructive" className="w-full" onClick={remove}><Trash2 className="mr-2 size-4"/>Delete section</Button></div>:<div className="p-6 text-sm text-muted-foreground">Select a section to edit it.</div>}</aside>
   {showLibrary&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4" onClick={()=>setShowLibrary(false)}><div className="max-h-[80vh] w-full max-w-3xl overflow-auto rounded-2xl border border-border bg-background p-5 shadow-2xl" onClick={e=>e.stopPropagation()}><div className="mb-5 flex items-center justify-between"><div><h2 className="text-xl font-bold">Add a section</h2><p className="text-sm text-muted-foreground">Build your storefront from reusable sections.</p></div><Button variant="ghost" onClick={()=>setShowLibrary(false)}>Close</Button></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{LIBRARY.map(t=><button key={t.type} onClick={()=>add(t)} className="rounded-xl border border-border p-4 text-left transition hover:-translate-y-0.5 hover:border-foreground hover:shadow-lg"><span className="flex size-9 items-center justify-center rounded-lg bg-muted"><Layers3 className="size-4"/></span><h3 className="mt-3 font-semibold">{t.label}</h3><p className="mt-1 text-xs leading-5 text-muted-foreground">{t.text}</p></button>)}</div></div></div>}
 </div></AppShell>;
}
