import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft, Check, LockKeyhole } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";

const plans = [{ code: "business", name: "Business", monthly: 3000, yearly: 28800, features: ["Online store", "Staff & permissions", "Multiple branches", "Data export"] }, { code: "pro", name: "Pro", monthly: 5000, yearly: 48000, features: ["Everything in Business", "Advanced inventory", "Advanced reports", "More operational controls"] }];

export const Route = createFileRoute("/_authenticated/upgrade")({ component: UpgradePage });
function UpgradePage() { const [billing,setBilling]=useState<"month"|"year">("month"); return <main className="min-h-screen bg-background px-4 py-10 sm:px-6"><div className="mx-auto max-w-5xl"><Link to="/dashboard" className="inline-flex items-center gap-2 text-sm font-semibold text-muted-foreground hover:text-foreground"><ArrowLeft className="size-4"/>Back to Strap</Link><div className="mt-10 max-w-2xl"><span className="inline-flex size-11 items-center justify-center rounded-2xl bg-accent-soft text-accent-ink"><LockKeyhole className="size-5"/></span><h1 className="mt-5 font-display text-4xl font-bold tracking-tight sm:text-5xl">Unlock more of Strap.</h1><p className="mt-4 text-base leading-7 text-muted-foreground">This workspace feature is not included in your current plan. Upgrade when you are ready. Paid features stay locked until payment is confirmed.</p></div><div className="mt-8 inline-flex rounded-xl border border-border bg-secondary/40 p-1"><button type="button" onClick={()=>setBilling("month")} className={`rounded-lg px-4 py-2 text-sm font-semibold ${billing==="month"?"bg-background shadow-sm":"text-muted-foreground"}`}>Monthly</button><button type="button" onClick={()=>setBilling("year")} className={`rounded-lg px-4 py-2 text-sm font-semibold ${billing==="year"?"bg-background shadow-sm":"text-muted-foreground"}`}>Yearly · save 20%</button></div><div className="mt-6 grid gap-4 md:grid-cols-2">{plans.map(p=><section key={p.code} className="rounded-3xl border border-border bg-background p-6 shadow-sm"><p className="text-xs font-bold uppercase tracking-[.15em] text-accent-ink">{p.name}</p><p className="mt-3 font-display text-3xl font-bold">₦{(billing==="year"?p.yearly:p.monthly).toLocaleString()}<span className="text-sm font-medium text-muted-foreground">/{billing}</span></p><div className="mt-6 space-y-3">{p.features.map(f=><p key={f} className="flex gap-2 text-sm"><Check className="mt-0.5 size-4 text-accent-ink"/>{f}</p>)}</div><Link to="/settings/payments" className="mt-7 inline-flex h-11 w-full items-center justify-center rounded-xl bg-foreground px-4 text-sm font-semibold text-background hover:bg-accent hover:text-accent-foreground">Review upgrade</Link></section>)}</div><p className="mt-6 text-xs leading-5 text-muted-foreground">Payment provider setup is pending. Once KoraPay is connected, the same upgrade flow will confirm payment before paid entitlements are activated.</p></div></main>; }
