import { useEffect, useState } from "react";
import { Check, Moon, Monitor, Sun } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Switch } from "@/components/ui/switch";
import { supabase } from "@/integrations/supabase/client";
import { useTheme } from "@/components/shell/ThemeProvider";
import { cn } from "@/lib/utils";

const options = [{ id: "system", title: "Use device setting", description: "Follow the phone or computer's light/dark preference.", icon: Monitor }, { id: "light", title: "Light", description: "A bright workspace with Strap's warm neutral palette.", icon: Sun }, { id: "dark", title: "Dark", description: "A focused dark workspace for low-light environments.", icon: Moon }] as const;

export function AppearanceSettingsPage() {
  const { theme, setTheme } = useTheme();
  const [saving, setSaving] = useState(false);
  const [compact, setCompact] = useState(false);
  useEffect(() => { void supabase.auth.getUser().then(async ({ data }) => { if (!data.user) return; const { data: profile } = await supabase.from("profiles").select("theme_preference").eq("id", data.user.id).maybeSingle(); if (profile?.theme_preference === "system" || profile?.theme_preference === "light" || profile?.theme_preference === "dark") setTheme(profile.theme_preference); }); }, [setTheme]);
  async function choose(value: "system" | "light" | "dark") { setTheme(value); setSaving(true); try { const { data } = await supabase.auth.getUser(); if (!data.user) return; const { error } = await supabase.from("profiles").update({ theme_preference: value }).eq("id", data.user.id); if (error) throw new Error(error.message); toast.success("Appearance preference saved."); } catch (error) { toast.error(error instanceof Error ? error.message : "Could not save appearance."); } finally { setSaving(false); } }
  return <div className="space-y-6"><div className="rounded-[28px] border border-border bg-foreground p-6 text-background shadow-float sm:p-8"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-background/45">Preferences</p><h2 className="mt-2 font-display text-3xl font-bold tracking-tight">Make Strap feel right.</h2><p className="mt-2 max-w-xl text-sm leading-6 text-background/60">Theme changes apply across the authenticated workspace and are remembered for this account.</p></div><section className="rounded-2xl border border-border bg-background p-5 sm:p-6"><div><h3 className="font-semibold">Theme</h3><p className="mt-1 text-sm text-muted-foreground">Choose how Strap should look on every screen.</p></div><div className="mt-5 grid gap-3 md:grid-cols-3">{options.map(({ id,title,description,icon:Icon })=><button key={id} type="button" disabled={saving} onClick={()=>void choose(id)} className={cn("rounded-2xl border p-4 text-left transition hover:-translate-y-0.5 hover:shadow-md",theme===id?"border-foreground bg-accent-soft":"border-border bg-surface hover:border-foreground/20")}><div className="flex items-center justify-between"><span className="flex size-10 items-center justify-center rounded-xl bg-secondary"><Icon className="size-5"/></span>{theme===id&&<span className="flex size-6 items-center justify-center rounded-full bg-foreground text-background"><Check className="size-3.5"/></span>}</div><p className="mt-4 font-semibold">{title}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{description}</p></button>)}</div></section><section className="rounded-2xl border border-border bg-background p-5 sm:p-6"><div className="flex items-center justify-between gap-4"><div><h3 className="font-semibold">Compact workspace</h3><p className="mt-1 text-sm leading-5 text-muted-foreground">Reduce vertical spacing on dense tables and lists.</p></div><Switch checked={compact} onCheckedChange={setCompact}/></div><p className="mt-3 text-xs text-muted-foreground">This preference is visual only and does not change data or permissions.</p></section><div className="rounded-xl border border-border bg-secondary/40 p-4 text-xs leading-5 text-muted-foreground">The public landing page follows the device preference when no account preference is available. Private workspace pages follow the account preference.</div><Button variant="outline" disabled className="hidden">Save</Button></div>;
}
