import { useEffect, useState } from "react";
import { CheckCircle2, Copy, Globe2, Loader2, Plus, RefreshCw } from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { useStoreContext } from "@/components/shell/StoreProvider";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { CardSection } from "@/components/settings/SettingsPrimitives";

export function CustomDomainsPanel(){const {store,role}=useStoreContext();const [domains,setDomains]=useState<any[]>([]);const [hostname,setHostname]=useState("");const [busy,setBusy]=useState(false);const canManage=role==="owner"||role==="manager";
 async function load(){if(!store?.id)return;const {data,error}=await (supabase as any).from("store_custom_domains").select("*").eq("store_id",store.id).neq("status","removed").order("created_at");if(error)toast.error(error.message);setDomains(data||[])} useEffect(()=>{void load()},[store?.id]);
 async function add(){if(!store?.id||!hostname.trim()||!canManage)return;setBusy(true);try{const host=hostname.trim().toLowerCase().replace(/^https?:\/\//,"").replace(/\/$/,"");const value=`strap-verify=${crypto.randomUUID().replaceAll("-","")}`;const {error}=await (supabase as any).from("store_custom_domains").upsert({store_id:store.id,hostname:host,status:"pending",verification_type:"TXT",verification_name:`_strap.${host}`,verification_value:value,updated_at:new Date().toISOString()},{onConflict:"store_id,hostname"});if(error)throw new Error(error.message);setHostname("");await load();toast.success("Domain added. Add the TXT record shown below, then verify it.")}catch(e){toast.error(e instanceof Error?e.message:"Could not add domain")}finally{setBusy(false)}}
 async function verify(domain:any){setBusy(true);try{const {data,error}=await supabase.functions.invoke("custom-domain-verify",{body:{store_id:store?.id,hostname:domain.hostname}});if(error)throw error;if(data?.verified)toast.success("Domain verified");else toast.error("TXT record not found yet");await load()}catch(e){toast.error(e instanceof Error?e.message:"Verification failed")}finally{setBusy(false)}}
 return <CardSection title="Custom domains" description="Connect a domain you own. Strap verifies ownership with a DNS TXT record before activation."><div className="flex gap-2"><Input value={hostname} onChange={e=>setHostname(e.target.value)} placeholder="shop.example.com" disabled={!canManage}/><Button onClick={()=>void add()} disabled={!canManage||busy||!hostname.trim()}><Plus className="mr-2 size-4"/>Add</Button></div><div className="mt-4 space-y-3">{domains.length===0?<div className="rounded-xl border border-dashed border-border p-5 text-sm text-muted-foreground">No custom domain connected yet.</div>:domains.map(domain=><div key={domain.id} className="rounded-2xl border border-border p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><span className="flex size-9 items-center justify-center rounded-xl bg-secondary"><Globe2 className="size-4"/></span><div><p className="font-semibold">{domain.hostname}</p><p className="text-xs capitalize text-muted-foreground">{domain.status}</p></div></div><Button variant="outline" size="sm" onClick={()=>void verify(domain)} disabled={!canManage||busy||domain.status==="verified"}>{busy?<Loader2 className="mr-2 size-3.5 animate-spin"/>:<RefreshCw className="mr-2 size-3.5"/>}{domain.status==="verified"?"Verified":"Verify DNS"}</Button></div>{domain.status!=="verified"&&<div className="mt-3 rounded-xl bg-secondary/50 p-3"><p className="text-xs font-bold uppercase tracking-[.12em] text-muted-foreground">Add this TXT record</p><div className="mt-2 grid gap-2 text-xs"><div><span className="text-muted-foreground">Name</span><p className="font-mono">{domain.verification_name}</p></div><div><span className="text-muted-foreground">Value</span><div className="flex items-center gap-2"><p className="min-w-0 flex-1 break-all font-mono">{domain.verification_value}</p><button onClick={()=>{void navigator.clipboard?.writeText(domain.verification_value)}} aria-label="Copy TXT value"><Copy className="size-3.5"/></button></div></div></div></div>}{domain.status==="verified"&&<p className="mt-3 flex items-center gap-2 text-xs font-semibold text-accent-ink"><CheckCircle2 className="size-4"/>Ownership verified. Final domain activation requires the hosting provider to accept the hostname.</p>}</div>)}</div></CardSection>}
