import { Link, Outlet, useLocation, useNavigate } from "@tanstack/react-router";
import { ArrowLeft, Bell, ChevronRight, CreditCard, Database, Globe2, KeyRound, Laptop, Menu, Palette, Receipt, ShieldCheck, SlidersHorizontal, Store, Users, WalletCards, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { AppShell } from "@/components/shell/AppShell";
import { Button } from "@/components/ui/button";
import { Sheet, SheetContent, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { cn } from "@/lib/utils";

const items = [
  { path: "/settings/store-profile", title: "Store profile", description: "Business identity, contact and regional settings", icon: Store, group: "Store" },
  { path: "/settings/appearance", title: "Store appearance", description: "Branding, typography and storefront style", icon: Palette, group: "Store" },
  { path: "/settings/online-store", title: "Online store", description: "Publishing, catalogue and SEO", icon: Globe2, group: "Store" },
  { path: "/settings/receipts", title: "Receipts", description: "Receipt identity, content and printing", icon: Receipt, group: "Commerce" },
  { path: "/settings/checkout", title: "Checkout & sales", description: "Checkout, discounts, tax and POS behaviour", icon: CreditCard, group: "Commerce" },
  { path: "/settings/inventory", title: "Inventory", description: "Stock, valuation, branches and alerts", icon: Database, group: "Commerce" },
  { path: "/settings/payments", title: "Payments", description: "Payment infrastructure", icon: WalletCards, group: "Commerce" },
  { path: "/settings/staff", title: "Staff & permissions", description: "Team members, roles and access", icon: Users, group: "Team" },
  { path: "/settings/notifications", title: "Notifications", description: "Operational notification preferences", icon: Bell, group: "Team" },
  { path: "/settings/security", title: "Security", description: "Account protection and sessions", icon: ShieldCheck, group: "Security" },
  { path: "/settings/password", title: "Change password", description: "Verify email and change password", icon: KeyRound, group: "Account" },
  { path: "/settings/sessions", title: "Active sessions", description: "Review and revoke authenticated sessions", icon: Laptop, group: "Account" },
  { path: "/settings/advanced", title: "Advanced", description: "Deeper operational and developer controls", icon: SlidersHorizontal, group: "Advanced" },
] as const;
function grouped() { const result = new Map<string, typeof items[number][]>(); for (const item of items) result.set(item.group, [...(result.get(item.group) ?? []), item]); return [...result.entries()]; }
function findAction(label: string) { return [...document.querySelectorAll<HTMLButtonElement>("button")].find(button => button.textContent?.trim() === label); }

export function SettingsShell() {
  const location = useLocation();
  if (location.pathname !== "/settings") return <FocusedSettingsPage />;
  return <AppShell title="Settings"><div className="mx-auto max-w-7xl space-y-6"><header className="border-b border-border pb-5 sm:pb-6"><p className="text-label-caps text-accent-ink">Strap settings</p><h1 className="mt-2 font-display text-4xl font-bold tracking-tight">Settings</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-muted-foreground">Manage your account, store and commerce preferences from one focused workspace.</p></header><div className="grid gap-5 lg:grid-cols-[248px_minmax(0,1fr)] lg:gap-6"><aside className="h-fit rounded-2xl border border-border bg-surface p-2 lg:sticky lg:top-24"><nav aria-label="Settings navigation"><Link to="/settings" className="mb-2 flex items-center gap-2.5 rounded-xl bg-accent-soft px-3 py-2.5 text-sm font-semibold text-accent-ink"><SlidersHorizontal className="size-4"/>Settings home</Link>{grouped().map(([group,groupItems])=><div key={group} className="mb-2"><p className="px-3 pb-1 pt-3 text-[10px] font-bold uppercase tracking-[0.16em] text-muted-foreground">{group}</p>{groupItems.map(item=>{const Icon=item.icon;return <Link key={item.path} to={item.path} className="group flex items-center gap-2.5 rounded-xl px-3 py-2.5 hover:bg-secondary"><Icon className="size-4 shrink-0"/><span className="min-w-0 flex-1 truncate text-sm font-semibold">{item.title}</span><ChevronRight className="size-3.5 opacity-0 group-hover:opacity-60"/></Link>})}</div>)}</nav></aside><main className="min-w-0"><Outlet/></main></div></div></AppShell>;
}

function FocusedSettingsPage() {
  const location = useLocation(); const navigate = useNavigate(); const [menuOpen,setMenuOpen]=useState(false); const [dirty,setDirty]=useState(false); const [confirmOpen,setConfirmOpen]=useState(false); const [pendingPath,setPendingPath]=useState<string|null>(null); const current=useMemo(()=>items.find(item=>location.pathname===item.path),[location.pathname]);
  useEffect(()=>{ const onChange=()=>setDirty(true); const onClick=(event:MouseEvent)=>{ const target=event.target as HTMLElement|null; const clickedButton=target?.closest("button"); if(clickedButton && /^(save|save changes|saving)/i.test(clickedButton.textContent?.trim()??"")) setTimeout(()=>setDirty(false),0); const anchor=target?.closest("a[href]") as HTMLAnchorElement|null; if(!anchor||!anchor.pathname.startsWith("/settings")||!dirty)return; event.preventDefault(); event.stopPropagation(); setPendingPath(anchor.pathname+anchor.search+anchor.hash); setConfirmOpen(true); }; const beforeUnload=(event:BeforeUnloadEvent)=>{if(!dirty)return;event.preventDefault();event.returnValue="";}; document.addEventListener("input",onChange,true);document.addEventListener("change",onChange,true);document.addEventListener("click",onClick,true);window.addEventListener("beforeunload",beforeUnload);return()=>{document.removeEventListener("input",onChange,true);document.removeEventListener("change",onChange,true);document.removeEventListener("click",onClick,true);window.removeEventListener("beforeunload",beforeUnload)}; },[dirty]);
  const requestNavigation=(path:string)=>{if(!dirty){void navigate({to:path});return;}setPendingPath(path);setConfirmOpen(true);};
  const discardAndGo=()=>{findAction("Discard")?.click();setDirty(false);setConfirmOpen(false);setMenuOpen(false);const path=pendingPath;setPendingPath(null);if(path)void navigate({to:path});};
  const saveAndGo=()=>{findAction("Save changes")?.click();setDirty(false);setConfirmOpen(false);setMenuOpen(false);setPendingPath(null);};
  const title=current?.title??"Settings";
  return <div className="min-h-[100dvh] bg-background"><header className="sticky top-0 z-40 border-b border-border/80 bg-background/95 backdrop-blur-sm"><div className="mx-auto flex h-16 max-w-6xl items-center justify-between gap-3 px-4 sm:h-[72px] sm:px-6"><button type="button" onClick={()=>requestNavigation("/settings")} className="flex size-10 shrink-0 items-center justify-center rounded-xl border border-border bg-surface hover:bg-secondary" aria-label="Back to settings"><ArrowLeft className="size-4"/></button><div className="min-w-0 flex-1 text-center"><p className="truncate text-[10px] font-bold uppercase tracking-[0.16em] text-muted-foreground">Settings</p><h1 className="truncate text-sm font-bold sm:text-base">{title}</h1></div><button type="button" onClick={()=>setMenuOpen(true)} className="flex size-10 shrink-0 items-center justify-center rounded-xl border border-border bg-surface hover:bg-secondary" aria-label="Open settings navigation"><Menu className="size-4"/></button></div></header><main className="mx-auto w-full max-w-4xl px-4 py-7 pb-28 sm:px-6 sm:py-10">{current&&<div className="mb-7"><p className="text-label-caps text-accent-ink">{current.group}</p><h2 className="mt-2 font-display text-3xl font-bold tracking-tight sm:text-4xl">{current.title}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">{current.description}</p></div>}<Outlet/></main>{dirty&&<div className="fixed inset-x-0 bottom-0 z-50 border-t border-border bg-background/95 px-4 py-3 shadow-[0_-10px_30px_rgba(0,0,0,.08)] backdrop-blur"><div className="mx-auto flex max-w-4xl items-center justify-between gap-3"><div><p className="text-sm font-semibold">Unsaved changes</p><p className="hidden text-xs text-muted-foreground sm:block">Save your changes before leaving this setting.</p></div><div className="flex gap-2"><Button variant="ghost" onClick={()=>findAction("Discard")?.click()} className="rounded-xl">Discard</Button><Button onClick={()=>findAction("Save changes")?.click()} className="rounded-xl">Save changes</Button></div></div></div>}
    <Sheet open={menuOpen} onOpenChange={setMenuOpen}><SheetContent side="right" className="flex h-[100dvh] w-full max-w-none flex-col p-0 sm:w-[420px]"><SheetHeader className="border-b border-border/70 px-5 pb-5 pt-6 text-left"><SheetTitle className="text-xl">Settings</SheetTitle><p className="mt-1 text-xs text-muted-foreground">Jump to another setting section.</p></SheetHeader><div className="flex-1 overflow-y-auto p-4">{grouped().map(([group,groupItems])=><section key={group} className="mb-5"><p className="px-2 pb-2 text-[10px] font-bold uppercase tracking-[0.16em] text-muted-foreground">{group}</p><div className="space-y-1">{groupItems.map(item=>{const Icon=item.icon;return <button key={item.path} type="button" onClick={()=>requestNavigation(item.path)} className={cn("flex w-full items-center gap-3 rounded-2xl p-3 text-left hover:bg-secondary",location.pathname===item.path&&"bg-accent-soft")}><span className="flex size-9 items-center justify-center rounded-xl bg-secondary"><Icon className="size-4"/></span><span className="min-w-0 flex-1"><span className="block text-sm font-semibold">{item.title}</span><span className="mt-0.5 block truncate text-xs text-muted-foreground">{item.description}</span></span><ChevronRight className="size-4 text-muted-foreground"/></button>})}</div></section>)}</div></SheetContent></Sheet>
    {confirmOpen&&<div className="fixed inset-0 z-[100] flex items-end justify-center bg-foreground/30 p-4 sm:items-center"><div role="dialog" aria-modal="true" aria-labelledby="unsaved-title" className="w-full max-w-md rounded-3xl border border-border bg-background p-5 shadow-2xl sm:p-6"><div className="flex items-start gap-3"><span className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-secondary"><SlidersHorizontal className="size-5"/></span><div><h2 id="unsaved-title" className="font-display text-lg font-bold">Unsaved changes</h2><p className="mt-1.5 text-sm leading-6 text-muted-foreground">You have changes that haven't been saved. Would you like to save them before leaving?</p></div></div><div className="mt-6 grid gap-2 sm:grid-cols-3"><Button variant="ghost" onClick={()=>{setConfirmOpen(false);setPendingPath(null)}} className="rounded-xl">Keep editing</Button><Button variant="outline" onClick={discardAndGo} className="rounded-xl">Discard</Button><Button onClick={saveAndGo} className="rounded-xl">Save</Button></div></div></div>}
  </div>;
}

export function SettingsHomeShell() { return <div className="space-y-6"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{items.map(item=>{const Icon=item.icon;return <Link key={item.path} to={item.path} className="group rounded-2xl border border-border bg-background p-5 transition hover:-translate-y-0.5 hover:border-accent/40 hover:shadow-sm"><div className="flex items-start justify-between"><span className="flex size-10 items-center justify-center rounded-xl bg-accent-soft text-accent-ink"><Icon className="size-5"/></span><ChevronRight className="size-4 text-muted-foreground transition group-hover:translate-x-1"/></div><h2 className="mt-4 font-semibold">{item.title}</h2><p className="mt-1.5 text-sm leading-6 text-muted-foreground">{item.description}</p></Link>})}</div></div>; }
